--- GENERATED by tools/gen-knot.py — do not edit.
------------------------------------------------------------------------
-- OCP-0009 · EXAMPLES — ★★★ `_⊢ty_ / _⊢_∷_` IS A WELL-FORMED DESCRIPTION.
--
-- ⚠⚠ THIS MODULE NEEDS THE **COMPACTING COLLECTOR**.
--
--   MEASURED 2026-08-31, the commit that added `⊢app`/`⊢pair`/`⊢snd`/
--   `⊢jsub`: `JudgeWfA` OOM-KILLED (143) on the default `-A64m` and
--   passed on `-A64m -c` at 179s.  `JudgeWfB` passed either way at 74s.
--   ⚠ Four rows moved it across the cap — and the two halves hold the
--     SAME number of rows, so the count is not what separates them.
--     `_⊢ty_`/`_⊢_∷_`'s index has FIVE components and the A half's rows
--     carry the deeper telescopes.
--
--   ⚠ BEFORE THIS MARKER THE MODULE WAS GREEN ONLY BY THE SWEEP'S
--     RETRY: `tools/sweep.sh` takes the OOM kill, then re-runs with
--     `-c`.  That is a pass, but it costs an OOM every sweep and it
--     hides the cost from anyone checking the module directly.
--
--   `tools/sweep.sh` greps this header for the phrase above and
--   switches collectors on its own (`needs_c`), which is why the words
--   are spelled out rather than described.
--
-- ⚠⚠ THE RULES ARE **PARSED OUT OF `Spec/Typing.agda`**, not transcribed.
--   A hand-written table is one chance per row to name the wrong
--   variable — the error class `Knot/LookupGen` exists to catch, and one
--   an `ICon` never reveals, because it type-checks with ANY in-scope
--   variable of the right type.  The Agda-former → knot-constructor map
--   comes from `KNOT`'s own `decl` strings, so nothing is typed twice.
--
-- ★ ANY RULE THAT DID NOT TRANSLATE IS NAMED BELOW.  Emitting a subset
--   silently is `verification-that-covers-less-than-it-claims`.
------------------------------------------------------------------------

{-# OPTIONS --safe #-}
module DirectedHoTT.Examples.Knot.Judge.CodePi where
open import normalizer.Syntax.Types using ( _≡_; refl )
open import DirectedHoTT.Spec.Typing using ( Θ₀; ρ₀; x₀; _,,_ )
open import DirectedHoTT.Spec.Syntax using ( thinR; keep; app; renTm )
open import Agda.Builtin.Nat using ( zero; suc ) renaming ( Nat to ℕ )
open import DirectedHoTT.Spec.Syntax
  using ( Cx; ε; _∙; RTy; RTm; var; vz; vs; pair; fst; snd; nsuc; nzero
        ; El; IMu; Σ'; Nat
        ; ⌜Nat⌝; ⌜Id⌝; ⌜IMu⌝; jsub; ICon; IDesc; iι; iρ; iκ; inil; _◂_; εwkTy )
open import DirectedHoTT.Spec.Typing
  using ( Ctx; ◇; _▹_; ⌊_⌋; _⊢_∷_; _⊢ty_
        ; IConWf; iwf-ι; iwf-κ; iwf-ρ; ICodeWf; icw-clo; icw-ford; icw-imu
        ; IDescWf; idwf-nil; idwf-cons
        ; ⊢var; here; there; ⊢fst; ⊢snd; ⊢nsuc; ⊢nzero
        ; ⊢⌜Nat⌝; ⊢⌜Id⌝; ⊢⌜IMu⌝; ⊢jsub
        ; ⊢pair; ty-Σ; ty-Nat; ty-IMu
        ; ξ-pairˡ; ξ-pairʳ; ξ-nsuc; βfst; βsnd )
open import DirectedHoTT.Examples.Knot.Sorts
  using ( IPair; sTy; sTm; sDesc; sDCon; sIDesc; sICon; sVar
        ; toI; fromI; ⊢ixP; ⊢sTy; ⊢sTm; ⊢sDesc; ⊢sDCon; ⊢sIDesc; ⊢sICon; ⊢sVar
        ; num; ⊢num )
open import DirectedHoTT.Examples.Knot.Desc using ( KnotD )
open import DirectedHoTT.Examples.Knot.Wf using ( KnotWf )
open import DirectedHoTT.Examples.Knot.Ctors
open import DirectedHoTT.Examples.Knot.CtorsV
open import DirectedHoTT.Examples.Knot.Build using ( Var-vzK; Var-vsK; ⊢Var-vzKt; ⊢Var-vsKt )
open import DirectedHoTT.Examples.Knot.WkSub using ( wkTmK; ⊢wkTmK; wkTyK; ⊢wkTyK )
open import DirectedHoTT.Lib.ICast using ( toMu; fromMu; fordAs; muFwd )
open import DirectedHoTT.Lib.ArithComm using ( symN; ⊢symN )
open import DirectedHoTT.Metatheory.SubjectReduction using ( ⊢wk )
open import DirectedHoTT.Examples.Knot.Single using ( singleK; ⊢singleK )
open import DirectedHoTT.Examples.Knot.SubApp
  using ( subTmAtK; subTyAtK; ⊢subTmAtK; ⊢subTyAtK )
open import DirectedHoTT.Examples.Knot.SubMot using ( extNK; ⊢extNK )
open import DirectedHoTT.Examples.Knot.Pw using ( pwK; ⊢pwK )
open import DirectedHoTT.Examples.Knot.Stk
  using ( stkAK; ⊢stkAK; stkCK; ⊢stkCK; flatK; ⊢flatK )
open import DirectedHoTT.Examples.Knot.Nrs using ( nrsSubK; ⊢nrsSubK )
open import DirectedHoTT.Examples.Knot.PwBody using ( pwBodyK; ⊢pwBodyK )
open import DirectedHoTT.Examples.Knot.ThinD
  using ( ThinD; ThinWf; Thin-doneK; ⊢Thin-doneK; Thin-keepK; ⊢Thin-keepK
        ; Thin-dropK; ⊢Thin-dropK )
open import DirectedHoTT.Examples.Knot.ThinRen using ( thinTmK; ⊢thinTmK )
open import DirectedHoTT.Examples.Knot.CtxD using ( ctxAtK; ⊢ctxAtK )
open import DirectedHoTT.Examples.Knot.CtxD
  using ( CtxD; INat; CtxWf; Ctx-extK; ⊢Ctx-extKt; Ctx-empK; ⊢Ctx-empK )
open import DirectedHoTT.Examples.Knot.EWk using ( εwkK; ⊢εwkK; isingleK; ⊢isingleK )
open import DirectedHoTT.Examples.Knot.SubMot
  using ( sortMap-ty; sortMap-tm; sortMap-desc; sortMap-dcon
        ; sortMap-idesc; sortMap-icon; sortMap-var )
open import DirectedHoTT.Examples.Knot.Lookup using ( LkD; ILk; LkWf )
open import DirectedHoTT.Examples.Knot.ConvRows using ( ConvD; IConv )
open import DirectedHoTT.Examples.Knot.ConvWf using ( ConvWf )
open import DirectedHoTT.Examples.Knot.NoNatCRows using ( NoNatCD; INoNatC )
open import DirectedHoTT.Examples.Knot.NoNatCWf using ( NoNatCWf )
open import DirectedHoTT.Examples.Knot.InDRows using ( InDD; IInD )
open import DirectedHoTT.Examples.Knot.InDWf using ( InDWf )
open import DirectedHoTT.Examples.Knot.InIDRows using ( InIDD; IInID )
open import DirectedHoTT.Examples.Knot.InIDWf using ( InIDWf )
open import DirectedHoTT.Examples.Knot.IxD
  using ( IxD; IxWf; IxNoneK; ⊢IxNoneK; IxDConK; ⊢IxDConK; IxDescK; ⊢IxDescK
        ; IxIConK; ⊢IxIConK; IxIDescK; ⊢IxIDescK )
open import DirectedHoTT.Examples.Knot.JudgeRows

-- ⊢⌜Π⌝
-- ★ the telescope: the family, the index, then each field
--   read through the thinning that skips the family.
TelJΦ0 : Ctx
TelJΦ0 = Θ₀ IJudge
GJΦ0 : RTm ⌊ TelJΦ0 ⌋
GJΦ0 = ⌜Nat⌝
TelJΦ1 : Ctx
TelJΦ1 = TelJΦ0 ▹ El GJΦ0
GJΦ1 : RTm ⌊ TelJΦ1 ⌋
GJΦ1 = ⌜IMu⌝ CtxD INat (var vz)
TelJΦ2 : Ctx
TelJΦ2 = TelJΦ1 ▹ El GJΦ1
GJΦ2 : RTm ⌊ TelJΦ2 ⌋
GJΦ2 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs vz)))
TelJΦ3 : Ctx
TelJΦ3 = TelJΦ2 ▹ El GJΦ2
GJΦ3 : RTm ⌊ TelJΦ3 ⌋
GJΦ3 = ⌜IMu⌝ KnotD IPair (pair sTm (nsuc (var (vs (vs vz)))))
TelJΦ4 : Ctx
TelJΦ4 = TelJΦ3 ▹ El GJΦ3
GJΦ4 : RTm ⌊ TelJΦ4 ⌋
GJΦ4 = pair (var (vs (vs (vs vz)))) (pair (var (vs (vs vz))) (pair (var (vs vz)) (pair Ty-UK (pair (num 1) (IxNoneK (var (vs (vs (vs vz)))))))))
TelJΦ5 : Ctx
TelJΦ5 = TelJΦ4 ▹ El (app (var (vs (vs (vs (vs x₀))))) GJΦ4)
GJΦ5 : RTm ⌊ TelJΦ5 ⌋
GJΦ5 = pair (nsuc (var (vs (vs (vs (vs vz)))))) (pair (Ctx-extK (var (vs (vs (vs (vs vz))))) (var (vs (vs (vs vz)))) (Ty-ElK (var (vs (vs vz))))) (pair (var (vs vz)) (pair Ty-UK (pair (num 1) (IxNoneK (nsuc (var (vs (vs (vs (vs vz)))))))))))
TelJΦ6 : Ctx
TelJΦ6 = TelJΦ5 ▹ El (app (var (vs (vs (vs (vs (vs x₀)))))) GJΦ5)
GJΦ6 : RTm ⌊ TelJΦ6 ⌋
GJΦ6 = ⌜Id⌝ ⌜Nat⌝ (fst (var (vs (vs (vs (vs (vs (vs vz)))))))) (var (vs (vs (vs (vs (vs vz))))))
TelJΦ7 : Ctx
TelJΦ7 = TelJΦ6 ▹ El GJΦ6
GJΦ7 : RTm ⌊ TelJΦ7 ⌋
GJΦ7 = ⌜Id⌝ (⌜IMu⌝ CtxD INat (fst (var (vs (vs (vs (vs (vs (vs (vs vz)))))))))) (fst (snd (var (vs (vs (vs (vs (vs (vs (vs vz)))))))))) (jsub (⌜IMu⌝ CtxD INat (var vz)) (symN (fst (var (vs (vs (vs (vs (vs (vs (vs vz))))))))) (var vz)) (var (vs (vs (vs (vs (vs vz)))))))
TelJΦ8 : Ctx
TelJΦ8 = TelJΦ7 ▹ El GJΦ7
GJΦ8 : RTm ⌊ TelJΦ8 ⌋
GJΦ8 = ⌜Id⌝ (⌜IMu⌝ KnotD IPair (pair sTm (fst (var (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))) (fst (snd (snd (var (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))) (jsub (⌜IMu⌝ KnotD IPair (pair sTm (var vz))) (symN (fst (var (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))) (var (vs vz))) (Tm-cPiK (var (vs (vs (vs (vs (vs vz)))))) (var (vs (vs (vs (vs vz)))))))
TelJΦ9 : Ctx
TelJΦ9 = TelJΦ8 ▹ El GJΦ8
GJΦ9 : RTm ⌊ TelJΦ9 ⌋
GJΦ9 = ⌜Id⌝ (⌜IMu⌝ KnotD IPair (pair sTy (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))))) (fst (snd (snd (snd (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))))) (jsub (⌜IMu⌝ KnotD IPair (pair sTy (var vz))) (symN (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))) (var (vs (vs vz)))) Ty-UK)
TelJΦ10 : Ctx
TelJΦ10 = TelJΦ9 ▹ El GJΦ9
GJΦ10 : RTm ⌊ TelJΦ10 ⌋
GJΦ10 = ⌜Id⌝ ⌜Nat⌝ (fst (snd (snd (snd (snd (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))))))) (jsub ⌜Nat⌝ (symN (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))) (var (vs (vs (vs vz))))) (num 1))
TelJΦ11 : Ctx
TelJΦ11 = TelJΦ10 ▹ El GJΦ10
GJΦ11 : RTm ⌊ TelJΦ11 ⌋
GJΦ11 = ⌜Id⌝ (⌜IMu⌝ IxD INat (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))))) (snd (snd (snd (snd (snd (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))))))))) (jsub (⌜IMu⌝ IxD INat (var vz)) (symN (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))))) (var (vs (vs (vs (vs vz)))))) (IxNoneK (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))))
TelJΦ12 : Ctx
TelJΦ12 = TelJΦ11 ▹ El GJΦ11

aJΦ11 : TelJΦ11 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))) ∷ Nat
aJΦ11 = ⊢fst (⊢var (there (there (there (there (there (there (there (there (there (there (there here))))))))))))
CJΦ11 : ICon XJΦ11
CJΦ11 = iκ kJΦ11 iι
W_JΦ11 : IConWf IJudge TelJΦ11 (keep (keep (keep (keep (keep (keep (keep (keep (keep (keep (keep ρ₀))))))))))) (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs x₀))))))))))) CJΦ11
W_JΦ11 =
  iwf-κ kJΦ11 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ IxWf (toI aJΦ11))
           (toMu (⊢snd (⊢snd (⊢snd (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there (there (there (there (there here))))))))))))))))))
           (⊢jsub (⊢⌜IMu⌝ IxWf (toI (fromI (⊢var here))))
                  (toI (fromI (⊢var (there (there (there (there (there (there (there (there (there (there here)))))))))))))
                  (toI aJΦ11)
                  (⊢symN aJΦ11 (fromI (⊢var (there (there (there (there (there (there (there (there (there (there here))))))))))))
                         (fordAs (⊢var (there (there (there (there here)))))))
                  (toMu (⊢IxNoneK (fromI (⊢var (there (there (there (there (there (there (there (there (there (there here))))))))))))))))
    iwf-ι

aJΦ10 : TelJΦ10 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))) ∷ Nat
aJΦ10 = ⊢fst (⊢var (there (there (there (there (there (there (there (there (there (there here)))))))))))
CJΦ10 : ICon XJΦ10
CJΦ10 = iκ kJΦ10 CJΦ11
W_JΦ10 : IConWf IJudge TelJΦ10 (keep (keep (keep (keep (keep (keep (keep (keep (keep (keep ρ₀)))))))))) (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs x₀)))))))))) CJΦ10
W_JΦ10 =
  iwf-κ kJΦ10 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝
           (toI (⊢fst (⊢snd (⊢snd (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there (there (there (there here)))))))))))))))))
           (⊢jsub ⊢⌜Nat⌝
                  (toI (fromI (⊢var (there (there (there (there (there (there (there (there (there here))))))))))))
                  (toI aJΦ10)
                  (⊢symN aJΦ10 (fromI (⊢var (there (there (there (there (there (there (there (there (there here)))))))))))
                         (fordAs (⊢var (there (there (there here))))))
                  (toI (⊢num 1))))
    W_JΦ11

aJΦ9 : TelJΦ9 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))) ∷ Nat
aJΦ9 = ⊢fst (⊢var (there (there (there (there (there (there (there (there (there here))))))))))
CJΦ9 : ICon XJΦ9
CJΦ9 = iκ kJΦ9 CJΦ10
W_JΦ9 : IConWf IJudge TelJΦ9 (keep (keep (keep (keep (keep (keep (keep (keep (keep ρ₀))))))))) (vs (vs (vs (vs (vs (vs (vs (vs (vs x₀))))))))) CJΦ9
W_JΦ9 =
  iwf-κ kJΦ9 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTy aJΦ9))
           (toMu (⊢fst (⊢snd (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there (there (there here)))))))))))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTy (fromI (⊢var here))))
                  (toI (fromI (⊢var (there (there (there (there (there (there (there (there here)))))))))))
                  (toI aJΦ9)
                  (⊢symN aJΦ9 (fromI (⊢var (there (there (there (there (there (there (there (there here))))))))))
                         (fordAs (⊢var (there (there here)))))
                  (toMu (⊢Ty-UKv (var (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))) (fromI (⊢var (there (there (there (there (there (there (there (there here))))))))))))))
    W_JΦ10

aJΦ8 : TelJΦ8 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))) ∷ Nat
aJΦ8 = ⊢fst (⊢var (there (there (there (there (there (there (there (there here)))))))))
CJΦ8 : ICon XJΦ8
CJΦ8 = iκ kJΦ8 CJΦ9
W_JΦ8 : IConWf IJudge TelJΦ8 (keep (keep (keep (keep (keep (keep (keep (keep ρ₀)))))))) (vs (vs (vs (vs (vs (vs (vs (vs x₀)))))))) CJΦ8
W_JΦ8 =
  iwf-κ kJΦ8 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aJΦ8))
           (toMu (⊢fst (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there (there here)))))))))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (there (there (there (there (there (there (there here))))))))))
                  (toI aJΦ8)
                  (⊢symN aJΦ8 (fromI (⊢var (there (there (there (there (there (there (there here)))))))))
                         (fordAs (⊢var (there here))))
                  (toMu (⊢Tm-cPiKv (var (vs (vs (vs (vs (vs (vs (vs vz)))))))) (fromI (⊢var (there (there (there (there (there (there (there here))))))))) (fromMu (⊢var (there (there (there (there (there here))))))) (fromMu (⊢var (there (there (there (there here))))))))))
    W_JΦ9

aJΦ7 : TelJΦ7 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs vz)))))))) ∷ Nat
aJΦ7 = ⊢fst (⊢var (there (there (there (there (there (there (there here))))))))
CJΦ7 : ICon XJΦ7
CJΦ7 = iκ kJΦ7 CJΦ8
W_JΦ7 : IConWf IJudge TelJΦ7 (keep (keep (keep (keep (keep (keep (keep ρ₀))))))) (vs (vs (vs (vs (vs (vs (vs x₀))))))) CJΦ7
W_JΦ7 =
  iwf-κ kJΦ7 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ CtxWf (toI aJΦ7))
           (toMu (⊢fst (⊢snd (⊢var (there (there (there (there (there (there (there here)))))))))))
           (⊢jsub (⊢⌜IMu⌝ CtxWf (toI (fromI (⊢var here))))
                  (toI (fromI (⊢var (there (there (there (there (there (there here)))))))))
                  (toI aJΦ7)
                  (⊢symN aJΦ7 (fromI (⊢var (there (there (there (there (there (there here))))))))
                         (fordAs (⊢var here)))
                  (toMu (fromMu (⊢var (there (there (there (there (there here))))))))))
    W_JΦ8

CJΦ6 : ICon XJΦ6
CJΦ6 = iκ kJΦ6 CJΦ7
W_JΦ6 : IConWf IJudge TelJΦ6 (keep (keep (keep (keep (keep (keep ρ₀)))))) (vs (vs (vs (vs (vs (vs x₀)))))) CJΦ6
W_JΦ6 =
  iwf-κ kJΦ6 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝ (toI (⊢fst (⊢var (there (there (there (there (there (there here))))))))) (toI (fromI (⊢var (there (there (there (there (there here)))))))))
    W_JΦ7

CJΦ5 : ICon XJΦ5
CJΦ5 = iρ kJΦ5 CJΦ6
W_JΦ5 : IConWf IJudge TelJΦ5 (keep (keep (keep (keep (keep ρ₀))))) (vs (vs (vs (vs (vs x₀))))) CJΦ5
W_JΦ5 =
  iwf-ρ kJΦ5
    (⊢pair (ty-Σ (ty-IMu CtxWf (toI (⊢var here))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢var (there here)))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢var (there (there here))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢var (there (there (there (there here))))))))))) (⊢nsuc (fromI (⊢var (there (there (there (there here)))))))
      (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢wk (⊢nsuc (fromI (⊢var (there (there (there (there here)))))))))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (⊢wk (⊢nsuc (fromI (⊢var (there (there (there (there here))))))))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢wk (⊢wk (⊢nsuc (fromI (⊢var (there (there (there (there here)))))))))))))))) (⊢Ctx-extKt (fromI (⊢var (there (there (there (there here)))))) (fromMu (⊢var (there (there (there here))))) (⊢Ty-ElKv (var (vs (vs (vs (vs vz))))) (fromI (⊢var (there (there (there (there here)))))) (fromMu (⊢var (there (there here))))))
      (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (⊢nsuc (fromI (⊢var (there (there (there (there here)))))))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢wk (⊢nsuc (fromI (⊢var (there (there (there (there here)))))))))))))) (fromMu (⊢var (there here)))
      (⊢pair (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢nsuc (fromI (⊢var (there (there (there (there here)))))))))))) (⊢Ty-UKv (nsuc (var (vs (vs (vs (vs vz)))))) (⊢nsuc (fromI (⊢var (there (there (there (there here))))))))
      (⊢pair (ty-IMu IxWf (toI (⊢wk (⊢nsuc (fromI (⊢var (there (there (there (there here)))))))))) (⊢num 1) (⊢IxNoneK (⊢nsuc (fromI (⊢var (there (there (there (there here)))))))))))))
    W_JΦ6

CJΦ4 : ICon ⌊ JΦ4 ⌋
CJΦ4 = iρ kJΦ4 CJΦ5
W_JΦ4 : IConWf IJudge TelJΦ4 (keep (keep (keep (keep ρ₀)))) (vs (vs (vs (vs x₀)))) CJΦ4
W_JΦ4 =
  iwf-ρ kJΦ4
    (⊢pair (ty-Σ (ty-IMu CtxWf (toI (⊢var here))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢var (there here)))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢var (there (there here))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢var (there (there (there (there here))))))))))) (fromI (⊢var (there (there (there here)))))
      (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢wk (fromI (⊢var (there (there (there here)))))))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (⊢wk (fromI (⊢var (there (there (there here))))))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢wk (⊢wk (fromI (⊢var (there (there (there here)))))))))))))) (fromMu (⊢var (there (there here))))
      (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (fromI (⊢var (there (there (there here)))))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢wk (fromI (⊢var (there (there (there here)))))))))))) (fromMu (⊢var (there here)))
      (⊢pair (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (fromI (⊢var (there (there (there here)))))))))) (⊢Ty-UKv (var (vs (vs (vs vz)))) (fromI (⊢var (there (there (there here))))))
      (⊢pair (ty-IMu IxWf (toI (⊢wk (fromI (⊢var (there (there (there here)))))))) (⊢num 1) (⊢IxNoneK (fromI (⊢var (there (there (there here)))))))))))
    W_JΦ5

CJΦ3 : ICon ⌊ JΦ3 ⌋
CJΦ3 = iκ kJΦ3 CJΦ4
W_JΦ3 : IConWf IJudge TelJΦ3 (keep (keep (keep ρ₀))) (vs (vs (vs x₀))) CJΦ3
W_JΦ3 =
  iwf-κ kJΦ3 (icw-imu (pair sTm (nsuc (var (vs (vs vz))))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (⊢nsuc (fromI (⊢var (there (there here)))))))
    W_JΦ4

CJΦ2 : ICon ⌊ JΦ2 ⌋
CJΦ2 = iκ kJΦ2 CJΦ3
W_JΦ2 : IConWf IJudge TelJΦ2 (keep (keep ρ₀)) (vs (vs x₀)) CJΦ2
W_JΦ2 =
  iwf-κ kJΦ2 (icw-imu (pair sTm (var (vs vz))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (there here)))))
    W_JΦ3

CJΦ1 : ICon ⌊ JΦ1 ⌋
CJΦ1 = iκ kJΦ1 CJΦ2
W_JΦ1 : IConWf IJudge TelJΦ1 (keep ρ₀) (vs x₀) CJΦ1
W_JΦ1 =
  iwf-κ kJΦ1 (icw-imu (var vz) CtxWf)
    (⊢⌜IMu⌝ CtxWf (toI (fromI (⊢var here))))
    W_JΦ2

CJΦ0 : ICon ⌊ JΦ0 ⌋
CJΦ0 = iκ kJΦ0 CJΦ1
W_JΦ0 : IConWf IJudge TelJΦ0 (ρ₀) (x₀) CJΦ0
W_JΦ0 =
  iwf-κ kJΦ0 (icw-clo ⌜Nat⌝ ⊢⌜Nat⌝) ⊢⌜Nat⌝
    W_JΦ1

jd⊢⌜Π⌝Wf : IConWf IJudge (Θ₀ IJudge) ρ₀ x₀ jd⊢⌜Π⌝
jd⊢⌜Π⌝Wf = W_JΦ0

