--- GENERATED by tools/gen-knot.py — do not edit.
------------------------------------------------------------------------
-- OCP-0009 · EXAMPLES — ★★★ `_⊢ty_ / _⊢_∷_` IS A WELL-FORMED DESCRIPTION.
--
-- ⚠⚠ THIS MODULE NEEDS THE **COMPACTING COLLECTOR**.
--
--   MEASURED 2026-08-31, the commit that added `⊢app`/`⊢pair`/`⊢snd`/
--   `⊢jsub`: `JudgeWfA` OOM-KILLED (143) on the default `-A64m` and
--   passed on `-A64m -c` at 179s.  `JudgeWfB` passed either way at 74s.
--   ⚠ Four rows moved it across the cap — and the two halves hold the
--     SAME number of rows, so the count is not what separates them.
--     `_⊢ty_`/`_⊢_∷_`'s index has FIVE components and the A half's rows
--     carry the deeper telescopes.
--
--   ⚠ BEFORE THIS MARKER THE MODULE WAS GREEN ONLY BY THE SWEEP'S
--     RETRY: `tools/sweep.sh` takes the OOM kill, then re-runs with
--     `-c`.  That is a pass, but it costs an OOM every sweep and it
--     hides the cost from anyone checking the module directly.
--
--   `tools/sweep.sh` greps this header for the phrase above and
--   switches collectors on its own (`needs_c`), which is why the words
--   are spelled out rather than described.
--
-- ⚠⚠ THE RULES ARE **PARSED OUT OF `Spec/Typing.agda`**, not transcribed.
--   A hand-written table is one chance per row to name the wrong
--   variable — the error class `Knot/LookupGen` exists to catch, and one
--   an `ICon` never reveals, because it type-checks with ANY in-scope
--   variable of the right type.  The Agda-former → knot-constructor map
--   comes from `KNOT`'s own `decl` strings, so nothing is typed twice.
--
-- ★ ANY RULE THAT DID NOT TRANSLATE IS NAMED BELOW.  Emitting a subset
--   silently is `verification-that-covers-less-than-it-claims`.
------------------------------------------------------------------------

{-# OPTIONS --safe #-}
module DirectedHoTT.Examples.Knot.Judge.DwfCons where
open import normalizer.Syntax.Types using ( _≡_; refl )
open import DirectedHoTT.Spec.Typing using ( Θ₀; ρ₀; x₀; _,,_ )
open import DirectedHoTT.Spec.Syntax using ( thinR; keep; app; renTm )
open import Agda.Builtin.Nat using ( zero; suc ) renaming ( Nat to ℕ )
open import DirectedHoTT.Spec.Syntax
  using ( Cx; ε; _∙; RTy; RTm; var; vz; vs; pair; fst; snd; nsuc; nzero
        ; El; IMu; Σ'; Nat
        ; ⌜Nat⌝; ⌜Id⌝; ⌜IMu⌝; jsub; ICon; IDesc; iι; iρ; iκ; inil; _◂_; εwkTy )
open import DirectedHoTT.Spec.Typing
  using ( Ctx; ◇; _▹_; ⌊_⌋; _⊢_∷_; _⊢ty_
        ; IConWf; iwf-ι; iwf-κ; iwf-ρ; ICodeWf; icw-clo; icw-ford; icw-imu
        ; IDescWf; idwf-nil; idwf-cons
        ; ⊢var; here; there; ⊢fst; ⊢snd; ⊢nsuc; ⊢nzero
        ; ⊢⌜Nat⌝; ⊢⌜Id⌝; ⊢⌜IMu⌝; ⊢jsub
        ; ⊢pair; ty-Σ; ty-Nat; ty-IMu
        ; ξ-pairˡ; ξ-pairʳ; ξ-nsuc; βfst; βsnd )
open import DirectedHoTT.Examples.Knot.Sorts
  using ( IPair; sTy; sTm; sDesc; sDCon; sIDesc; sICon; sVar
        ; toI; fromI; ⊢ixP; ⊢sTy; ⊢sTm; ⊢sDesc; ⊢sDCon; ⊢sIDesc; ⊢sICon; ⊢sVar
        ; num; ⊢num )
open import DirectedHoTT.Examples.Knot.Desc using ( KnotD )
open import DirectedHoTT.Examples.Knot.Wf using ( KnotWf )
open import DirectedHoTT.Examples.Knot.Ctors
open import DirectedHoTT.Examples.Knot.CtorsV
open import DirectedHoTT.Examples.Knot.Build using ( Var-vzK; Var-vsK; ⊢Var-vzKt; ⊢Var-vsKt )
open import DirectedHoTT.Examples.Knot.WkSub using ( wkTmK; ⊢wkTmK; wkTyK; ⊢wkTyK )
open import DirectedHoTT.Lib.ICast using ( toMu; fromMu; fordAs; muFwd )
open import DirectedHoTT.Lib.ArithComm using ( symN; ⊢symN )
open import DirectedHoTT.Metatheory.SubjectReduction using ( ⊢wk )
open import DirectedHoTT.Examples.Knot.Single using ( singleK; ⊢singleK )
open import DirectedHoTT.Examples.Knot.SubApp
  using ( subTmAtK; subTyAtK; ⊢subTmAtK; ⊢subTyAtK )
open import DirectedHoTT.Examples.Knot.SubMot using ( extNK; ⊢extNK )
open import DirectedHoTT.Examples.Knot.Pw using ( pwK; ⊢pwK )
open import DirectedHoTT.Examples.Knot.Stk
  using ( stkAK; ⊢stkAK; stkCK; ⊢stkCK; flatK; ⊢flatK )
open import DirectedHoTT.Examples.Knot.Nrs using ( nrsSubK; ⊢nrsSubK )
open import DirectedHoTT.Examples.Knot.PwBody using ( pwBodyK; ⊢pwBodyK )
open import DirectedHoTT.Examples.Knot.ThinD
  using ( ThinD; ThinWf; Thin-doneK; ⊢Thin-doneK; Thin-keepK; ⊢Thin-keepK
        ; Thin-dropK; ⊢Thin-dropK )
open import DirectedHoTT.Examples.Knot.ThinRen using ( thinTmK; ⊢thinTmK )
open import DirectedHoTT.Examples.Knot.CtxD
  using ( CtxD; INat; CtxWf; Ctx-extK; ⊢Ctx-extKt; Ctx-empK; ⊢Ctx-empK )
open import DirectedHoTT.Examples.Knot.EWk using ( εwkK; ⊢εwkK; isingleK; ⊢isingleK )
open import DirectedHoTT.Examples.Knot.SubMot
  using ( sortMap-ty; sortMap-tm; sortMap-desc; sortMap-dcon
        ; sortMap-idesc; sortMap-icon; sortMap-var )
open import DirectedHoTT.Examples.Knot.Lookup using ( LkD; ILk; LkWf )
open import DirectedHoTT.Examples.Knot.ConvRows using ( ConvD; IConv )
open import DirectedHoTT.Examples.Knot.ConvWf using ( ConvWf )
open import DirectedHoTT.Examples.Knot.NoNatCRows using ( NoNatCD; INoNatC )
open import DirectedHoTT.Examples.Knot.NoNatCWf using ( NoNatCWf )
open import DirectedHoTT.Examples.Knot.InDRows using ( InDD; IInD )
open import DirectedHoTT.Examples.Knot.InDWf using ( InDWf )
open import DirectedHoTT.Examples.Knot.InIDRows using ( InIDD; IInID )
open import DirectedHoTT.Examples.Knot.InIDWf using ( InIDWf )
open import DirectedHoTT.Examples.Knot.IxD
  using ( IxD; IxWf; IxNoneK; ⊢IxNoneK; IxDConK; ⊢IxDConK; IxDescK; ⊢IxDescK
        ; IxIConK; ⊢IxIConK; IxIDescK; ⊢IxIDescK )
open import DirectedHoTT.Examples.Knot.JudgeRows

-- dwf-cons
-- ★ the telescope: the family, the index, then each field
--   read through the thinning that skips the family.
TelJΩΒ0 : Ctx
TelJΩΒ0 = Θ₀ IJudge
GJΩΒ0 : RTm ⌊ TelJΩΒ0 ⌋
GJΩΒ0 = ⌜Nat⌝
TelJΩΒ1 : Ctx
TelJΩΒ1 = TelJΩΒ0 ▹ El GJΩΒ0
GJΩΒ1 : RTm ⌊ TelJΩΒ1 ⌋
GJΩΒ1 = ⌜IMu⌝ KnotD IPair (pair sDCon nzero)
TelJΩΒ2 : Ctx
TelJΩΒ2 = TelJΩΒ1 ▹ El GJΩΒ1
GJΩΒ2 : RTm ⌊ TelJΩΒ2 ⌋
GJΩΒ2 = ⌜IMu⌝ KnotD IPair (pair sDesc nzero)
TelJΩΒ3 : Ctx
TelJΩΒ3 = TelJΩΒ2 ▹ El GJΩΒ2
GJΩΒ3 : RTm ⌊ TelJΩΒ3 ⌋
GJΩΒ3 = pair (num 0) (pair Ctx-empK (pair Tm-unitK (pair Ty-NatK (pair (num 2) (IxDConK (num 0) (var (vs vz)))))))
TelJΩΒ4 : Ctx
TelJΩΒ4 = TelJΩΒ3 ▹ El (app (var (vs (vs (vs x₀)))) GJΩΒ3)
GJΩΒ4 : RTm ⌊ TelJΩΒ4 ⌋
GJΩΒ4 = pair (num 0) (pair Ctx-empK (pair Tm-unitK (pair Ty-NatK (pair (num 3) (IxDescK (num 0) (var (vs vz)))))))
TelJΩΒ5 : Ctx
TelJΩΒ5 = TelJΩΒ4 ▹ El (app (var (vs (vs (vs (vs x₀))))) GJΩΒ4)
GJΩΒ5 : RTm ⌊ TelJΩΒ5 ⌋
GJΩΒ5 = ⌜Id⌝ ⌜Nat⌝ (fst (var (vs (vs (vs (vs (vs vz))))))) (num 0)
TelJΩΒ6 : Ctx
TelJΩΒ6 = TelJΩΒ5 ▹ El GJΩΒ5
GJΩΒ6 : RTm ⌊ TelJΩΒ6 ⌋
GJΩΒ6 = ⌜Id⌝ (⌜IMu⌝ CtxD INat (fst (var (vs (vs (vs (vs (vs (vs vz))))))))) (fst (snd (var (vs (vs (vs (vs (vs (vs vz))))))))) (jsub (⌜IMu⌝ CtxD INat (var vz)) (symN (fst (var (vs (vs (vs (vs (vs (vs vz)))))))) (var vz)) Ctx-empK)
TelJΩΒ7 : Ctx
TelJΩΒ7 = TelJΩΒ6 ▹ El GJΩΒ6
GJΩΒ7 : RTm ⌊ TelJΩΒ7 ⌋
GJΩΒ7 = ⌜Id⌝ (⌜IMu⌝ KnotD IPair (pair sTm (fst (var (vs (vs (vs (vs (vs (vs (vs vz))))))))))) (fst (snd (snd (var (vs (vs (vs (vs (vs (vs (vs vz))))))))))) (jsub (⌜IMu⌝ KnotD IPair (pair sTm (var vz))) (symN (fst (var (vs (vs (vs (vs (vs (vs (vs vz))))))))) (var (vs vz))) Tm-unitK)
TelJΩΒ8 : Ctx
TelJΩΒ8 = TelJΩΒ7 ▹ El GJΩΒ7
GJΩΒ8 : RTm ⌊ TelJΩΒ8 ⌋
GJΩΒ8 = ⌜Id⌝ (⌜IMu⌝ KnotD IPair (pair sTy (fst (var (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))) (fst (snd (snd (snd (var (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))))) (jsub (⌜IMu⌝ KnotD IPair (pair sTy (var vz))) (symN (fst (var (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))) (var (vs (vs vz)))) Ty-NatK)
TelJΩΒ9 : Ctx
TelJΩΒ9 = TelJΩΒ8 ▹ El GJΩΒ8
GJΩΒ9 : RTm ⌊ TelJΩΒ9 ⌋
GJΩΒ9 = ⌜Id⌝ ⌜Nat⌝ (fst (snd (snd (snd (snd (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))))))) (jsub ⌜Nat⌝ (symN (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))) (var (vs (vs (vs vz))))) (num 3))
TelJΩΒ10 : Ctx
TelJΩΒ10 = TelJΩΒ9 ▹ El GJΩΒ9
GJΩΒ10 : RTm ⌊ TelJΩΒ10 ⌋
GJΩΒ10 = ⌜Id⌝ (⌜IMu⌝ IxD INat (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))))) (snd (snd (snd (snd (snd (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))))))) (jsub (⌜IMu⌝ IxD INat (var vz)) (symN (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))) (var (vs (vs (vs (vs vz)))))) (IxDescK (num 0) (Desc-consK (var (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))) (var (vs (vs (vs (vs (vs (vs (vs vz)))))))))))
TelJΩΒ11 : Ctx
TelJΩΒ11 = TelJΩΒ10 ▹ El GJΩΒ10

aJΩΒ10 : TelJΩΒ10 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))) ∷ Nat
aJΩΒ10 = ⊢fst (⊢var (there (there (there (there (there (there (there (there (there (there here)))))))))))
CJΩΒ10 : ICon XJΩΒ10
CJΩΒ10 = iκ kJΩΒ10 iι
W_JΩΒ10 : IConWf IJudge TelJΩΒ10 (keep (keep (keep (keep (keep (keep (keep (keep (keep (keep ρ₀)))))))))) (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs x₀)))))))))) CJΩΒ10
W_JΩΒ10 =
  iwf-κ kJΩΒ10 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ IxWf (toI aJΩΒ10))
           (toMu (⊢snd (⊢snd (⊢snd (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there (there (there (there here)))))))))))))))))
           (⊢jsub (⊢⌜IMu⌝ IxWf (toI (fromI (⊢var here))))
                  (toI (⊢num 0))
                  (toI aJΩΒ10)
                  (⊢symN aJΩΒ10 (⊢num 0)
                         (fordAs (⊢var (there (there (there (there here)))))))
                  (toMu (⊢IxDescK (⊢num 0) (⊢Desc-consKv (num 0) (⊢num 0) (fromMu (⊢var (there (there (there (there (there (there (there (there here)))))))))) (fromMu (⊢var (there (there (there (there (there (there (there here))))))))))))))
    iwf-ι

aJΩΒ9 : TelJΩΒ9 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))) ∷ Nat
aJΩΒ9 = ⊢fst (⊢var (there (there (there (there (there (there (there (there (there here))))))))))
CJΩΒ9 : ICon XJΩΒ9
CJΩΒ9 = iκ kJΩΒ9 CJΩΒ10
W_JΩΒ9 : IConWf IJudge TelJΩΒ9 (keep (keep (keep (keep (keep (keep (keep (keep (keep ρ₀))))))))) (vs (vs (vs (vs (vs (vs (vs (vs (vs x₀))))))))) CJΩΒ9
W_JΩΒ9 =
  iwf-κ kJΩΒ9 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝
           (toI (⊢fst (⊢snd (⊢snd (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there (there (there here))))))))))))))))
           (⊢jsub ⊢⌜Nat⌝
                  (toI (⊢num 0))
                  (toI aJΩΒ9)
                  (⊢symN aJΩΒ9 (⊢num 0)
                         (fordAs (⊢var (there (there (there here))))))
                  (toI (⊢num 3))))
    W_JΩΒ10

aJΩΒ8 : TelJΩΒ8 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))) ∷ Nat
aJΩΒ8 = ⊢fst (⊢var (there (there (there (there (there (there (there (there here)))))))))
CJΩΒ8 : ICon XJΩΒ8
CJΩΒ8 = iκ kJΩΒ8 CJΩΒ9
W_JΩΒ8 : IConWf IJudge TelJΩΒ8 (keep (keep (keep (keep (keep (keep (keep (keep ρ₀)))))))) (vs (vs (vs (vs (vs (vs (vs (vs x₀)))))))) CJΩΒ8
W_JΩΒ8 =
  iwf-κ kJΩΒ8 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTy aJΩΒ8))
           (toMu (⊢fst (⊢snd (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there (there here))))))))))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTy (fromI (⊢var here))))
                  (toI (⊢num 0))
                  (toI aJΩΒ8)
                  (⊢symN aJΩΒ8 (⊢num 0)
                         (fordAs (⊢var (there (there here)))))
                  (toMu (⊢Ty-NatKv (num 0) (⊢num 0)))))
    W_JΩΒ9

aJΩΒ7 : TelJΩΒ7 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs vz)))))))) ∷ Nat
aJΩΒ7 = ⊢fst (⊢var (there (there (there (there (there (there (there here))))))))
CJΩΒ7 : ICon XJΩΒ7
CJΩΒ7 = iκ kJΩΒ7 CJΩΒ8
W_JΩΒ7 : IConWf IJudge TelJΩΒ7 (keep (keep (keep (keep (keep (keep (keep ρ₀))))))) (vs (vs (vs (vs (vs (vs (vs x₀))))))) CJΩΒ7
W_JΩΒ7 =
  iwf-κ kJΩΒ7 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aJΩΒ7))
           (toMu (⊢fst (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there here))))))))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (⊢num 0))
                  (toI aJΩΒ7)
                  (⊢symN aJΩΒ7 (⊢num 0)
                         (fordAs (⊢var (there here))))
                  (toMu (⊢Tm-unitKv (num 0) (⊢num 0)))))
    W_JΩΒ8

aJΩΒ6 : TelJΩΒ6 ⊢ fst (var (vs (vs (vs (vs (vs (vs vz))))))) ∷ Nat
aJΩΒ6 = ⊢fst (⊢var (there (there (there (there (there (there here)))))))
CJΩΒ6 : ICon XJΩΒ6
CJΩΒ6 = iκ kJΩΒ6 CJΩΒ7
W_JΩΒ6 : IConWf IJudge TelJΩΒ6 (keep (keep (keep (keep (keep (keep ρ₀)))))) (vs (vs (vs (vs (vs (vs x₀)))))) CJΩΒ6
W_JΩΒ6 =
  iwf-κ kJΩΒ6 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ CtxWf (toI aJΩΒ6))
           (toMu (⊢fst (⊢snd (⊢var (there (there (there (there (there (there here))))))))))
           (⊢jsub (⊢⌜IMu⌝ CtxWf (toI (fromI (⊢var here))))
                  (toI (⊢num 0))
                  (toI aJΩΒ6)
                  (⊢symN aJΩΒ6 (⊢num 0)
                         (fordAs (⊢var here)))
                  (toMu ⊢Ctx-empK)))
    W_JΩΒ7

CJΩΒ5 : ICon XJΩΒ5
CJΩΒ5 = iκ kJΩΒ5 CJΩΒ6
W_JΩΒ5 : IConWf IJudge TelJΩΒ5 (keep (keep (keep (keep (keep ρ₀))))) (vs (vs (vs (vs (vs x₀))))) CJΩΒ5
W_JΩΒ5 =
  iwf-κ kJΩΒ5 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝ (toI (⊢fst (⊢var (there (there (there (there (there here)))))))) (toI (⊢num 0)))
    W_JΩΒ6

CJΩΒ4 : ICon XJΩΒ4
CJΩΒ4 = iρ kJΩΒ4 CJΩΒ5
W_JΩΒ4 : IConWf IJudge TelJΩΒ4 (keep (keep (keep (keep ρ₀)))) (vs (vs (vs (vs x₀)))) CJΩΒ4
W_JΩΒ4 =
  iwf-ρ kJΩΒ4
    (⊢pair (ty-Σ (ty-IMu CtxWf (toI (⊢var here))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢var (there here)))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢var (there (there here))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢var (there (there (there (there here))))))))))) (⊢num 0)
      (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢wk (⊢num 0)))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (⊢wk (⊢num 0))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢wk (⊢wk (⊢num 0)))))))))) ⊢Ctx-empK
      (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (⊢num 0)))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢wk (⊢num 0)))))))) (⊢Tm-unitKv (num 0) (⊢num 0))
      (⊢pair (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢num 0)))))) (⊢Ty-NatKv (num 0) (⊢num 0))
      (⊢pair (ty-IMu IxWf (toI (⊢wk (⊢num 0)))) (⊢num 3) (⊢IxDescK (⊢num 0) (fromMu (⊢var (there here)))))))))
    W_JΩΒ5

CJΩΒ3 : ICon ⌊ JΩΒ3 ⌋
CJΩΒ3 = iρ kJΩΒ3 CJΩΒ4
W_JΩΒ3 : IConWf IJudge TelJΩΒ3 (keep (keep (keep ρ₀))) (vs (vs (vs x₀))) CJΩΒ3
W_JΩΒ3 =
  iwf-ρ kJΩΒ3
    (⊢pair (ty-Σ (ty-IMu CtxWf (toI (⊢var here))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢var (there here)))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢var (there (there here))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢var (there (there (there (there here))))))))))) (⊢num 0)
      (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢wk (⊢num 0)))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (⊢wk (⊢num 0))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢wk (⊢wk (⊢num 0)))))))))) ⊢Ctx-empK
      (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (⊢num 0)))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢wk (⊢num 0)))))))) (⊢Tm-unitKv (num 0) (⊢num 0))
      (⊢pair (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢num 0)))))) (⊢Ty-NatKv (num 0) (⊢num 0))
      (⊢pair (ty-IMu IxWf (toI (⊢wk (⊢num 0)))) (⊢num 2) (⊢IxDConK (⊢num 0) (fromMu (⊢var (there here)))))))))
    W_JΩΒ4

CJΩΒ2 : ICon ⌊ JΩΒ2 ⌋
CJΩΒ2 = iκ kJΩΒ2 CJΩΒ3
W_JΩΒ2 : IConWf IJudge TelJΩΒ2 (keep (keep ρ₀)) (vs (vs x₀)) CJΩΒ2
W_JΩΒ2 =
  iwf-κ kJΩΒ2 (icw-imu (pair sDesc nzero) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sDesc ⊢nzero))
    W_JΩΒ3

CJΩΒ1 : ICon ⌊ JΩΒ1 ⌋
CJΩΒ1 = iκ kJΩΒ1 CJΩΒ2
W_JΩΒ1 : IConWf IJudge TelJΩΒ1 (keep ρ₀) (vs x₀) CJΩΒ1
W_JΩΒ1 =
  iwf-κ kJΩΒ1 (icw-imu (pair sDCon nzero) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sDCon ⊢nzero))
    W_JΩΒ2

CJΩΒ0 : ICon ⌊ JΩΒ0 ⌋
CJΩΒ0 = iκ kJΩΒ0 CJΩΒ1
W_JΩΒ0 : IConWf IJudge TelJΩΒ0 (ρ₀) (x₀) CJΩΒ0
W_JΩΒ0 =
  iwf-κ kJΩΒ0 (icw-clo ⌜Nat⌝ ⊢⌜Nat⌝) ⊢⌜Nat⌝
    W_JΩΒ1

jddwf-consWf : IConWf IJudge (Θ₀ IJudge) ρ₀ x₀ jddwf-cons
jddwf-consWf = W_JΩΒ0

