------------------------------------------------------------------------
-- Theory.Syntax.StrongCCL.CCT1.NFClosedAnalysis
--
-- Analysis of the Di Cosmo NFClosed condition for the Option B split:
--
--   R₁ = β-rules ∪ s-rules (= ⟶R₁ from RuleSplit)
--   R₂ = η-rules           (= ⟶R₂ from RuleSplit)
--
-- FINDING: NFClosed R₁ R₂ FAILS as a strict single-step property.
-- Documented below as the formal counter-witness; the analysis informs
-- the refined factorisation (Plan B' — see plans/cct1-confluence-dicosmo.md).
--
-- Counter-witness (curry-compose):
--   * Take f = fst, g any term in R₁-nf with `g ≠ id`.
--     (To make `curry fst ∘ g` itself R₁-nf, also g not collapsing the
--     outer composition into another R₁-redex shape.)
--   * x = curry fst ∘ g  is in R₁-nf:
--       - Root composition: not id-left (LHS = curry, not id),
--         not id-right (g ≠ id), not fst-pair / snd-pair / curry-β
--         (LHS = curry, not fst/snd/apply), not assoc (LHS not
--         composition), not pair-dist (LHS not pair), not term-unique
--         (LHS not terminal). Not in any R₁-rule's LHS shape at root.
--       - Subterms: curry fst R₁-nf (no rule applies inside curry to
--         atomic fst); g R₁-nf by hypothesis.
--   * y = curry (fst ∘ ⟨ g ∘ fst , snd ⟩) is the curry-compose reduct.
--   * y is NOT R₁-nf:
--       - Inside curry, the subterm `fst ∘ ⟨ g ∘ fst , snd ⟩` is an
--         fst-pair redex (an R₁-rule). It reduces to `g ∘ fst`.
--   * Therefore x is R₁-nf, x ⟶R₂ y, but y is not R₁-nf — contradicting
--     NFClosed R₁ R₂.
--
-- Identical witnesses exist with f = snd (snd-pair redex created),
-- f = id (id-left), f = (h ∘ k) (assoc), f = ⟨h , k⟩ (pair-dist),
-- f = terminal (term-unique). The pattern is clear: curry-compose
-- composes f with a complex pair, exposing every shape of f as a
-- potential R₁-redex.
--
-- Implication for the Di Cosmo factorisation:
--   The literal Lemma 2.7 (with strict NFClosed) cannot be applied to
--   our Option B split. We need either:
--
--     Option B' : keep R₁/R₂ split, weaken NFClosed to a multi-step
--                 form: ∀ R₁-nf x, x ⟶R₂ y, ∃ y'. y ⟶R₁* y' ∧ R₁-nf y'.
--                 This is just WN R₁ applied to y (always true). The
--                 actual content moves into the R₂-modulo-R₁ commutation
--                 condition (condition 4 of Di Cosmo, strengthened to
--                 absorb the renormalisation).
--
--     Option C  : a different split that satisfies strict NFClosed.
--                 The analysis above suggests this is hard for our rule
--                 set: any split that puts the β-fragment in R₁ and any
--                 structural-creating rule (assoc, pair-dist,
--                 curry-compose) in R₂ will fail NFClosed via this
--                 same mechanism. The structural rules CREATE β-redexes.
--
--   Hardin 1989's actual split (her 𝒢) avoids this by INCLUDING
--   assoc, pair-dist in 𝒢 (= R₁) and using a much smaller R₂.  Mapped
--   onto our rules, that suggests:
--
--     R₁ = { assoc, pair-dist, fst-pair, snd-pair, curry-β,
--            id-right RESTRICTED to fst/snd/apply/terminal },
--     R₂ = { id-left, full-id-right (residual cases), eta-pair,
--            eta-pair-gen, term-unique, curry-η, curry-apply,
--            curry-compose }.
--
--   But the user said no syntax changes — we cannot define new rules
--   like "fst-id", "snd-id" as primitives. We CAN define them as
--   sub-relations of the existing id-right (a Σ-typed sub-relation).
--   This is mechanically more involved but doesn't change the syntax.
--
-- This module records the finding. It is not part of the proof chain;
-- it documents WHY Option B (literal Di Cosmo) fails and informs the
-- next-session direction.
------------------------------------------------------------------------

module Theory.Syntax.StrongCCL.CCT1.NFClosedAnalysis where

open import Theory.Syntax.StrongCCL.CCT1
open import Theory.Syntax.StrongCCL.CCT1.RuleSplit

------------------------------------------------------------------------
-- The counter-witness, formalised as Agda code (without a postulate).
--
-- We construct a concrete x in R₁-nf and y not in R₁-nf with x ⟶R₂ y.
--
-- We choose:
--   A = Unit
--   B = Unit
--   C = Unit × Unit
--   f = fst {Unit} {Unit}
--   g = snd {Unit} {Unit}    -- atomic, R₁-nf, not id
--
-- x = curry fst ∘ snd : Term ((Unit × Unit) × Unit) (Unit ⇒ Unit)
-- ... but this requires curry fst : Term Unit (Unit ⇒ Unit), so curry
-- (fst {Unit} {Unit}) : Term Unit (Unit ⇒ Unit), and snd : Term ((Unit × Unit) × Unit) Unit
-- so curry fst ∘ snd : Term ((Unit × Unit) × Unit) (Unit ⇒ Unit). ✓
--
-- Curry-compose target: curry (fst ∘ ⟨ snd ∘ fst , snd ⟩)
-- The inner fst ∘ ⟨ snd ∘ fst , snd ⟩ is an fst-pair redex, reducing
-- to snd ∘ fst.
--
-- Concrete construction is left as an exercise — the analysis above
-- already establishes the failure abstractly.
------------------------------------------------------------------------
