------------------------------------------------------------------------
-- DirectedHoTT · THE TRUST SURFACE.
--
-- ★★ WHAT A REVIEWER MUST TAKE ON FAITH IN ORDER TO BELIEVE THIS KERNEL:
--
--        Agda itself, `--safe`, and nothing else.
--
--   This module is DELIBERATELY EMPTY OF CONTENT.  That is its content.
--
-- ⚠ AND IT IS NOT A PROMISE — IT IS CHECKED.  `tools/check-trust.sh`
--   fails the sweep if ANY module under `DirectedHoTT/` acquires:
--
--        postulate            an assumed proposition
--        {-# TERMINATING #-}  a defeated termination check
--        {-# NON_TERMINATING #-}, primTrustMe, trustMe
--        {-# NO_POSITIVITY_CHECK #-}, {-# NO_UNIVERSE_CHECK #-}
--        {  }-holes           an unfinished proof
--        an OPTIONS line without `--safe`
--
--   A prose claim rots; a checked one cannot.  This is the analogue of
--   `formal/Once/Postulates.agda` on master, which isolates that
--   development's assumptions into one readable place.
--
-- ★ WHY IT MATTERS FOR HOW YOU READ THE REST.  With this empty, a
--   reviewer asking "IS IT SOUND?" can read `Spec/` and `Metatheory/` and
--   stop: nothing in `Lib/` or `Examples/` can weaken anything, because
--   nothing there may assume anything.
--
-- ⚠⚠ BUT SOUNDNESS IS NOT THE ONLY QUESTION, AND THIS DOES NOT ANSWER THE
--   OTHER ONE.  An empty trust surface does NOT make a lemma MEANINGFUL.
--   `lexrec` (now in `Negative/`) was derived, green, `--safe` and
--   postulate-free — and NOT CALLABLE, because its premise was
--   unsatisfiable.  Perfectly sound; entirely worthless.
--
--   ⇒ A reviewer asking "IS IT ANY GOOD?" must read `Lib/` and
--     `Examples/`, and CANNOT skip them.  That question is answered by
--     the standing rule that every library branch is exercised by an
--     Example — which is what catches the `lexrec` failure mode, and
--     which this file cannot.
------------------------------------------------------------------------

-- ⚠⚠ UPDATED 2026-09-01 — IT NOW CHECKS ITSELF, AND DID NOT BEFORE.
--
--   For weeks this module claimed "it is not a promise — it is checked"
--   while importing ZERO modules; every bit of the checking lived in the
--   shell script.  Two facts, MEASURED, make the claim real instead:
--
--     `--safe` BANS `postulate`             → SafeFlagPostulate
--     `--safe` PROPAGATES through imports   → CoInfectiveImport
--
--   ⇒ so a `--safe` module importing the WHOLE TREE makes AGDA enforce
--     the trust surface transitively.  That is what the list below is.
--   ⇒ and `tools/check-trust.sh` shrinks to the ONE question that is
--     genuinely a filesystem property and not a proposition: does this
--     list name every `.agda` file?  It regenerates and DIFFS.
--
-- ⚠ `import`, not `open import`: the dependency EDGE is the point; 209
--   modules opened would collide at once.
-- ⚠ `Negative/` is excluded — it holds REFUTED results that must not
--   build, and importing them would fail the root for the one reason
--   that is not a trust violation.
-- ★ GENERATED by `tools/gen-trust.sh`.  Do not hand-edit the list.
------------------------------------------------------------------------

{-# OPTIONS --safe #-}
module DirectedHoTT.Trust where

import DirectedHoTT.Algorithm.DecideConversion
import DirectedHoTT.Comparison.GcdIndStepConcrete
import DirectedHoTT.Comparison.GcdRoute1Agda
import DirectedHoTT.Comparison.GcdRoute2Kernel
import DirectedHoTT.Comparison.GcdRoute3Combinator
import DirectedHoTT.Examples.AbsProbe
import DirectedHoTT.Examples.Ack
import DirectedHoTT.Examples.AckAgda1
import DirectedHoTT.Examples.AckAgda2
import DirectedHoTT.Examples.AckKernel
import DirectedHoTT.Examples.Agree
import DirectedHoTT.Examples.AmrecC
import DirectedHoTT.Examples.AmrecIMu
import DirectedHoTT.Examples.AmrecIMuDepth
import DirectedHoTT.Examples.AmrecIMuRec
import DirectedHoTT.Examples.AmrecIMuSzGen
import DirectedHoTT.Examples.AmrecInd
import DirectedHoTT.Examples.AmrecInst
import DirectedHoTT.Examples.AmrecT
import DirectedHoTT.Examples.DepIx
import DirectedHoTT.Examples.Div
import DirectedHoTT.Examples.DivC
import DirectedHoTT.Examples.DivLib
import DirectedHoTT.Examples.Dogfood
import DirectedHoTT.Examples.DvdArith
import DirectedHoTT.Examples.Gcd.Cert
import DirectedHoTT.Examples.Gcd.Dvd
import DirectedHoTT.Examples.Gcd.DvdL
import DirectedHoTT.Examples.Gcd.DvdLs
import DirectedHoTT.Examples.Gcd.Eqs
import DirectedHoTT.Examples.Gcd.IndG
import DirectedHoTT.Examples.Gcd.LeEq
import DirectedHoTT.Examples.Gcd.LeMid
import DirectedHoTT.Examples.Gcd.MaxSpec
import DirectedHoTT.Examples.Gcd.Motives
import DirectedHoTT.Examples.Gcd.Rec
import DirectedHoTT.Examples.Gcd.Spec
import DirectedHoTT.Examples.Gcd.Step
import DirectedHoTT.Examples.Gcd.StepExt
import DirectedHoTT.Examples.Gcd.StepExtA
import DirectedHoTT.Examples.Gcd.StepExtE
import DirectedHoTT.Examples.Gcd.StepExtL
import DirectedHoTT.Examples.Gcd.StepExtLs
import DirectedHoTT.Examples.IHCallAgree
import DirectedHoTT.Examples.Id
import DirectedHoTT.Examples.IrrProbe
import DirectedHoTT.Examples.Knot.Build
import DirectedHoTT.Examples.Knot.Census
import DirectedHoTT.Examples.Knot.ConvRows
import DirectedHoTT.Examples.Knot.ConvWf
import DirectedHoTT.Examples.Knot.Ctors
import DirectedHoTT.Examples.Knot.CtorsV
import DirectedHoTT.Examples.Knot.CtxD
import DirectedHoTT.Examples.Knot.Desc
import DirectedHoTT.Examples.Knot.EWk
import DirectedHoTT.Examples.Knot.IxD
import DirectedHoTT.Examples.Knot.JudgeRows
import DirectedHoTT.Examples.Knot.JudgeWfA
import DirectedHoTT.Examples.Knot.JudgeWfAA
import DirectedHoTT.Examples.Knot.JudgeWfAB
import DirectedHoTT.Examples.Knot.JudgeWfAC
import DirectedHoTT.Examples.Knot.JudgeWfAD
import DirectedHoTT.Examples.Knot.JudgeWfAE
import DirectedHoTT.Examples.Knot.JudgeWfAF
import DirectedHoTT.Examples.Knot.JudgeWfAG
import DirectedHoTT.Examples.Knot.JudgeWfAH
import DirectedHoTT.Examples.Knot.JudgeWfAI
import DirectedHoTT.Examples.Knot.JudgeWfAJ
import DirectedHoTT.Examples.Knot.JudgeWfAK
import DirectedHoTT.Examples.Knot.JudgeWfAL
import DirectedHoTT.Examples.Knot.JudgeWfAM
import DirectedHoTT.Examples.Knot.JudgeWfAN
import DirectedHoTT.Examples.Knot.JudgeWfAO
import DirectedHoTT.Examples.Knot.JudgeWfAP
import DirectedHoTT.Examples.Knot.JudgeWfAQ
import DirectedHoTT.Examples.Knot.JudgeWfAR
import DirectedHoTT.Examples.Knot.JudgeWfAS
import DirectedHoTT.Examples.Knot.JudgeWfAT
import DirectedHoTT.Examples.Knot.JudgeWfAU
import DirectedHoTT.Examples.Knot.JudgeWfAV
import DirectedHoTT.Examples.Knot.JudgeWfAW
import DirectedHoTT.Examples.Knot.JudgeWfAX
import DirectedHoTT.Examples.Knot.JudgeWfAY
import DirectedHoTT.Examples.Knot.JudgeWfB
import DirectedHoTT.Examples.Knot.JudgeWfC
import DirectedHoTT.Examples.Knot.JudgeWfD
import DirectedHoTT.Examples.Knot.JudgeWfE
import DirectedHoTT.Examples.Knot.JudgeWfF
import DirectedHoTT.Examples.Knot.JudgeWfG
import DirectedHoTT.Examples.Knot.JudgeWfH
import DirectedHoTT.Examples.Knot.JudgeWfI
import DirectedHoTT.Examples.Knot.JudgeWfJ
import DirectedHoTT.Examples.Knot.JudgeWfK
import DirectedHoTT.Examples.Knot.JudgeWfL
import DirectedHoTT.Examples.Knot.JudgeWfM
import DirectedHoTT.Examples.Knot.JudgeWfN
import DirectedHoTT.Examples.Knot.JudgeWfO
import DirectedHoTT.Examples.Knot.JudgeWfP
import DirectedHoTT.Examples.Knot.JudgeWfQ
import DirectedHoTT.Examples.Knot.JudgeWfR
import DirectedHoTT.Examples.Knot.JudgeWfS
import DirectedHoTT.Examples.Knot.JudgeWfT
import DirectedHoTT.Examples.Knot.JudgeWfU
import DirectedHoTT.Examples.Knot.JudgeWfV
import DirectedHoTT.Examples.Knot.JudgeWfW
import DirectedHoTT.Examples.Knot.JudgeWfX
import DirectedHoTT.Examples.Knot.JudgeWfY
import DirectedHoTT.Examples.Knot.JudgeWfZ
import DirectedHoTT.Examples.Knot.Lookup
import DirectedHoTT.Examples.Knot.LookupGen
import DirectedHoTT.Examples.Knot.Map
import DirectedHoTT.Examples.Knot.NoNatCRows
import DirectedHoTT.Examples.Knot.NoNatCWf
import DirectedHoTT.Examples.Knot.Nrs
import DirectedHoTT.Examples.Knot.Pw
import DirectedHoTT.Examples.Knot.PwBody
import DirectedHoTT.Examples.Knot.RedRows
import DirectedHoTT.Examples.Knot.RedWfA
import DirectedHoTT.Examples.Knot.RedWfB
import DirectedHoTT.Examples.Knot.Single
import DirectedHoTT.Examples.Knot.Sorts
import DirectedHoTT.Examples.Knot.Stk
import DirectedHoTT.Examples.Knot.SubApp
import DirectedHoTT.Examples.Knot.SubMot
import DirectedHoTT.Examples.Knot.Sz
import DirectedHoTT.Examples.Knot.SzAgree
import DirectedHoTT.Examples.Knot.SzProbe
import DirectedHoTT.Examples.Knot.SzS
import DirectedHoTT.Examples.Knot.Tags
import DirectedHoTT.Examples.Knot.Terms
import DirectedHoTT.Examples.Knot.TyRedRows
import DirectedHoTT.Examples.Knot.TyRedWf
import DirectedHoTT.Examples.Knot.Wf
import DirectedHoTT.Examples.Knot.Wk
import DirectedHoTT.Examples.Knot.WkProbe
import DirectedHoTT.Examples.Knot.WkRows
import DirectedHoTT.Examples.KripkeIx
import DirectedHoTT.Examples.KripkeSub
import DirectedHoTT.Examples.MaxLib
import DirectedHoTT.Examples.MuNest
import DirectedHoTT.Examples.Mutual
import DirectedHoTT.Examples.Nat
import DirectedHoTT.Examples.OneApp
import DirectedHoTT.Examples.Ord
import DirectedHoTT.Examples.Overview
import DirectedHoTT.Examples.PairC
import DirectedHoTT.Examples.PairIx
import DirectedHoTT.Examples.PairLib
import DirectedHoTT.Examples.Scoped
import DirectedHoTT.Examples.ScopedDepth
import DirectedHoTT.Examples.ScopedSize
import DirectedHoTT.Examples.ScopedSz
import DirectedHoTT.Examples.Small
import DirectedHoTT.Examples.Strong
import DirectedHoTT.Examples.Vec
import DirectedHoTT.Examples.WkFin
import DirectedHoTT.Examples.WkTm
import DirectedHoTT.Lib.Amrec
import DirectedHoTT.Lib.AmrecClosed
import DirectedHoTT.Lib.AmrecInd
import DirectedHoTT.Lib.AmrecRen
import DirectedHoTT.Lib.Arith
import DirectedHoTT.Lib.ArithComm
import DirectedHoTT.Lib.ArithLe
import DirectedHoTT.Lib.ArithMonus
import DirectedHoTT.Lib.Dvd
import DirectedHoTT.Lib.DvdArith
import DirectedHoTT.Lib.ICast
import DirectedHoTT.Lib.IDepth
import DirectedHoTT.Lib.IFold
import DirectedHoTT.Lib.IHCall
import DirectedHoTT.Lib.IMeths
import DirectedHoTT.Lib.IPay
import DirectedHoTT.Lib.ISub
import DirectedHoTT.Lib.ISz
import DirectedHoTT.Lib.ISzRed
import DirectedHoTT.Lib.ISzSort
import DirectedHoTT.Lib.IWk
import DirectedHoTT.Lib.Id
import DirectedHoTT.Lib.IdSuc
import DirectedHoTT.Lib.Max
import DirectedHoTT.Lib.Monus
import DirectedHoTT.Lib.MonusArith
import DirectedHoTT.Lib.MonusLe
import DirectedHoTT.Lib.MonusPlus
import DirectedHoTT.Lib.Mul
import DirectedHoTT.Lib.Nat
import DirectedHoTT.Lib.NatEval
import DirectedHoTT.Lib.NatMax
import DirectedHoTT.Lib.NatNum
import DirectedHoTT.Lib.NatVal
import DirectedHoTT.Lib.Natrec
import DirectedHoTT.Lib.Ord
import DirectedHoTT.Lib.Pair
import DirectedHoTT.Lib.Rec
import DirectedHoTT.Lib.Strong
import DirectedHoTT.Lib.Wk
import DirectedHoTT.Metatheory.Canonicity
import DirectedHoTT.Metatheory.Confluence
import DirectedHoTT.Metatheory.FormerCensus
import DirectedHoTT.Metatheory.Fundamental
import DirectedHoTT.Metatheory.Fundamental.Indexed
import DirectedHoTT.Metatheory.Fundamental.Semantic
import DirectedHoTT.Metatheory.Fundamental.Syntactic
import DirectedHoTT.Metatheory.Injectivity
import DirectedHoTT.Metatheory.LogicalRelation
import DirectedHoTT.Metatheory.SubjectReduction
import DirectedHoTT.Metatheory.SubjectReductionBase
import DirectedHoTT.Spec.Syntax
import DirectedHoTT.Spec.Typing
import DirectedHoTT.Spec.Variance
