--- GENERATED by tools/gen-trust.sh — do not edit.
------------------------------------------------------------------------
-- DirectedHoTT · TRUST SURFACE — the **Knot8** root.
--
-- ★★★ WHAT A REVIEWER MUST TAKE ON FAITH TO BELIEVE THIS KERNEL:
--        Agda itself, `--safe`, and nothing else.
--   These roots are DELIBERATELY EMPTY OF CONTENT.  That is their content.
--
-- ⚠⚠ WHY SEVERAL ROOTS COST NO GUARANTEE.  `--safe` BANS `postulate` and
--   PROPAGATES through imports, and that propagation is EDGE-LOCAL, not
--   root-local — it happens on every import edge regardless of where the
--   walk starts.  So N roots enforce exactly what one root did, provided
--   every module is reachable from SOME root; `tools/check-trust.sh`
--   diffs the union of these files against the module list to check
--   precisely that.  ⇒ a partition, not a weakening.
--
-- ⚠ A module in NO root is invisible to `--safe` however sound the
--   language is.  COVERAGE, not correctness — the same class as a stale
--   generated file the sweep still globs.
--
-- ⚠⚠ THERE MUST BE NO ROOT IMPORTING THE OTHERS.
------------------------------------------------------------------------

{-# OPTIONS --safe #-}
module DirectedHoTT.Trust.Knot8 where

import DirectedHoTT.Examples.Knot.SubRed
import DirectedHoTT.Examples.Knot.SubSpec
import DirectedHoTT.Examples.Knot.Sz
import DirectedHoTT.Examples.Knot.SzAgree
import DirectedHoTT.Examples.Knot.SzProbe
import DirectedHoTT.Examples.Knot.SzS
import DirectedHoTT.Examples.Knot.Tags
import DirectedHoTT.Examples.Knot.Terms
import DirectedHoTT.Examples.Knot.TyRedRows
import DirectedHoTT.Examples.Knot.TyRedWf
import DirectedHoTT.Examples.Knot.Wf
import DirectedHoTT.Examples.Knot.Wk
import DirectedHoTT.Examples.Knot.WkProbe
import DirectedHoTT.Examples.Knot.WkRows
import DirectedHoTT.Examples.Knot.WkSub
