--- GENERATED by tools/gen-trust.sh — do not edit.
------------------------------------------------------------------------
-- DirectedHoTT · TRUST SURFACE — the **Lib** root.
--
-- ★★★ WHAT A REVIEWER MUST TAKE ON FAITH TO BELIEVE THIS KERNEL:
--        Agda itself, `--safe`, and nothing else.
--   These roots are DELIBERATELY EMPTY OF CONTENT.  That is their content.
--
-- ⚠⚠ WHY SEVERAL ROOTS COST NO GUARANTEE.  `--safe` BANS `postulate` and
--   PROPAGATES through imports, and that propagation is EDGE-LOCAL, not
--   root-local — it happens on every import edge regardless of where the
--   walk starts.  So N roots enforce exactly what one root did, provided
--   every module is reachable from SOME root; `tools/check-trust.sh`
--   diffs the union of these files against the module list to check
--   precisely that.  ⇒ a partition, not a weakening.
--
-- ⚠ A module in NO root is invisible to `--safe` however sound the
--   language is.  COVERAGE, not correctness — the same class as a stale
--   generated file the sweep still globs.
--
-- ⚠⚠ THERE MUST BE NO ROOT IMPORTING THE OTHERS.
------------------------------------------------------------------------

{-# OPTIONS --safe #-}
module DirectedHoTT.Trust.Lib where

import DirectedHoTT.Lib.Amrec
import DirectedHoTT.Lib.AmrecClosed
import DirectedHoTT.Lib.AmrecInd
import DirectedHoTT.Lib.AmrecRen
import DirectedHoTT.Lib.Arith
import DirectedHoTT.Lib.ArithComm
import DirectedHoTT.Lib.ArithLe
import DirectedHoTT.Lib.ArithMonus
import DirectedHoTT.Lib.Dvd
import DirectedHoTT.Lib.DvdArith
import DirectedHoTT.Lib.ICast
import DirectedHoTT.Lib.IDepth
import DirectedHoTT.Lib.IFold
import DirectedHoTT.Lib.IHCall
import DirectedHoTT.Lib.IMeths
import DirectedHoTT.Lib.IPay
import DirectedHoTT.Lib.ISub
import DirectedHoTT.Lib.ISz
import DirectedHoTT.Lib.ISzRed
import DirectedHoTT.Lib.ISzSort
import DirectedHoTT.Lib.IWk
import DirectedHoTT.Lib.Id
import DirectedHoTT.Lib.IdSuc
import DirectedHoTT.Lib.Max
import DirectedHoTT.Lib.Monus
import DirectedHoTT.Lib.MonusArith
import DirectedHoTT.Lib.MonusLe
import DirectedHoTT.Lib.MonusPlus
import DirectedHoTT.Lib.Mul
import DirectedHoTT.Lib.Nat
import DirectedHoTT.Lib.NatEval
import DirectedHoTT.Lib.NatMax
import DirectedHoTT.Lib.NatNum
import DirectedHoTT.Lib.NatVal
import DirectedHoTT.Lib.Natrec
import DirectedHoTT.Lib.Ord
import DirectedHoTT.Lib.Pair
import DirectedHoTT.Lib.Rec
import DirectedHoTT.Lib.Strong
import DirectedHoTT.Lib.Wk
