--- GENERATED by tools/gen-knot.py — do not edit.
------------------------------------------------------------------------
-- OCP-0009 · EXAMPLES — ★★★ `_⊢ty_ / _⊢_∷_` IS A WELL-FORMED DESCRIPTION.
--
-- ⚠⚠ THIS MODULE NEEDS THE **COMPACTING COLLECTOR**.
--
--   MEASURED 2026-08-31, the commit that added `⊢app`/`⊢pair`/`⊢snd`/
--   `⊢jsub`: `JudgeWfA` OOM-KILLED (143) on the default `-A64m` and
--   passed on `-A64m -c` at 179s.  `JudgeWfB` passed either way at 74s.
--   ⚠ Four rows moved it across the cap — and the two halves hold the
--     SAME number of rows, so the count is not what separates them.
--     `_⊢ty_`/`_⊢_∷_`'s index has FIVE components and the A half's rows
--     carry the deeper telescopes.
--
--   ⚠ BEFORE THIS MARKER THE MODULE WAS GREEN ONLY BY THE SWEEP'S
--     RETRY: `tools/sweep.sh` takes the OOM kill, then re-runs with
--     `-c`.  That is a pass, but it costs an OOM every sweep and it
--     hides the cost from anyone checking the module directly.
--
--   `tools/sweep.sh` greps this header for the phrase above and
--   switches collectors on its own (`needs_c`), which is why the words
--   are spelled out rather than described.
--
-- ⚠⚠ THE RULES ARE **PARSED OUT OF `Spec/Typing.agda`**, not transcribed.
--   A hand-written table is one chance per row to name the wrong
--   variable — the error class `Knot/LookupGen` exists to catch, and one
--   an `ICon` never reveals, because it type-checks with ANY in-scope
--   variable of the right type.  The Agda-former → knot-constructor map
--   comes from `KNOT`'s own `decl` strings, so nothing is typed twice.
--
-- ★ ANY RULE THAT DID NOT TRANSLATE IS NAMED BELOW.  Emitting a subset
--   silently is `verification-that-covers-less-than-it-claims`.
------------------------------------------------------------------------

{-# OPTIONS --safe #-}
module DirectedHoTT.Examples.Knot.JudgeWfAU where
open import normalizer.Syntax.Types using ( _≡_; refl )
open import Agda.Builtin.Nat using ( zero; suc ) renaming ( Nat to ℕ )
open import DirectedHoTT.Spec.Syntax
  using ( Cx; ε; _∙; RTy; RTm; var; vz; vs; pair; fst; snd; nsuc; nzero
        ; El; IMu; Σ'; Nat
        ; ⌜Nat⌝; ⌜Id⌝; ⌜IMu⌝; jsub; ICon; IDesc; iι; iρ; iκ; inil; _◂_; εwkTy )
open import DirectedHoTT.Spec.Typing
  using ( Ctx; ◇; _▹_; ⌊_⌋; _⊢_∷_; _⊢ty_
        ; IConWf; iwf-ι; iwf-κ; iwf-ρ; ICodeWf; icw-clo; icw-ford; icw-imu
        ; IDescWf; idwf-nil; idwf-cons
        ; ⊢var; here; there; ⊢fst; ⊢snd; ⊢nsuc; ⊢nzero
        ; ⊢⌜Nat⌝; ⊢⌜Id⌝; ⊢⌜IMu⌝; ⊢jsub
        ; ⊢pair; ty-Σ; ty-Nat; ty-IMu
        ; ξ-pairˡ; ξ-pairʳ; ξ-nsuc; βfst; βsnd )
open import DirectedHoTT.Examples.Knot.Sorts
  using ( IPair; sTy; sTm; sDesc; sDCon; sIDesc; sICon; sVar
        ; toI; fromI; ⊢ixP; ⊢sTy; ⊢sTm; ⊢sDesc; ⊢sDCon; ⊢sIDesc; ⊢sICon; ⊢sVar
        ; num; ⊢num )
open import DirectedHoTT.Examples.Knot.Desc using ( KnotD )
open import DirectedHoTT.Examples.Knot.Wf using ( KnotWf )
open import DirectedHoTT.Examples.Knot.Ctors
open import DirectedHoTT.Examples.Knot.CtorsV
open import DirectedHoTT.Examples.Knot.Build using ( Var-vzK; Var-vsK; ⊢Var-vzKt; ⊢Var-vsKt )
open import DirectedHoTT.Examples.Knot.WkSub using ( wkTmK; ⊢wkTmK; wkTyK; ⊢wkTyK )
-- ★ STEP 5 — `⊢con` needs these.  `lookupDK`/`ilookupDK` are already in
--   the kernel's argument order; `payTyKᵏ` is `Knot/KAdapt`'s adapter,
--   because `payTy D C` maps to `payTyK n C D` with the arguments SWAPPED
--   and `_SUBST_CT` only renames a head.
open import DirectedHoTT.Examples.Knot.LookupD using ( lookupDK; ⊢lookupDK )
open import DirectedHoTT.Examples.Knot.ILookupD using ( ilookupDK; ⊢ilookupDK )
open import DirectedHoTT.Examples.Knot.KAdapt using ( payTyKᵏ; ⊢payTyKᵏ; ipayTyKᵏ; ⊢ipayTyKᵏ )
open import DirectedHoTT.Lib.ICast using ( toMu; fromMu; fordAs; muFwd )
open import DirectedHoTT.Lib.ArithComm using ( symN; ⊢symN )
open import DirectedHoTT.Metatheory.SubjectReduction using ( ⊢wk )
open import DirectedHoTT.Examples.Knot.Single using ( singleK; ⊢singleK )
open import DirectedHoTT.Examples.Knot.SubApp
  using ( subTmAtK; subTyAtK; ⊢subTmAtK; ⊢subTyAtK )
open import DirectedHoTT.Examples.Knot.SubMot using ( extNK; ⊢extNK )
open import DirectedHoTT.Examples.Knot.Pw using ( pwK; ⊢pwK )
open import DirectedHoTT.Examples.Knot.Stk
  using ( stkAK; ⊢stkAK; stkCK; ⊢stkCK; flatK; ⊢flatK )
open import DirectedHoTT.Examples.Knot.Nrs using ( nrsSubK; ⊢nrsSubK )
open import DirectedHoTT.Examples.Knot.PwBody using ( pwBodyK; ⊢pwBodyK )
open import DirectedHoTT.Examples.Knot.CtxD
  using ( CtxD; INat; CtxWf; Ctx-extK; ⊢Ctx-extKt; Ctx-empK; ⊢Ctx-empK )
open import DirectedHoTT.Examples.Knot.EWk using ( εwkK; ⊢εwkK; isingleK; ⊢isingleK )
open import DirectedHoTT.Examples.Knot.SubMot
  using ( sortMap-ty; sortMap-tm; sortMap-desc; sortMap-dcon
        ; sortMap-idesc; sortMap-icon; sortMap-var )
open import DirectedHoTT.Examples.Knot.Lookup using ( LkD; ILk; LkWf )
open import DirectedHoTT.Examples.Knot.ConvRows using ( ConvD; IConv )
open import DirectedHoTT.Examples.Knot.ConvWf using ( ConvWf )
open import DirectedHoTT.Examples.Knot.NoNatCRows using ( NoNatCD; INoNatC )
open import DirectedHoTT.Examples.Knot.NoNatCWf using ( NoNatCWf )
open import DirectedHoTT.Examples.Knot.InDRows using ( InDD; IInD )
open import DirectedHoTT.Examples.Knot.InDWf using ( InDWf )
open import DirectedHoTT.Examples.Knot.InIDRows using ( InIDD; IInID )
open import DirectedHoTT.Examples.Knot.InIDWf using ( InIDWf )
open import DirectedHoTT.Examples.Knot.IxD
  using ( IxD; IxWf; IxNoneK; ⊢IxNoneK; IxDConK; ⊢IxDConK; IxDescK; ⊢IxDescK
        ; IxIConK; ⊢IxIConK; IxIDescK; ⊢IxIDescK )
open import DirectedHoTT.Examples.Knot.JudgeRows
open import DirectedHoTT.Examples.Knot.JudgeWfA
open import DirectedHoTT.Examples.Knot.JudgeWfB
open import DirectedHoTT.Examples.Knot.JudgeWfC
open import DirectedHoTT.Examples.Knot.JudgeWfD
open import DirectedHoTT.Examples.Knot.JudgeWfE
open import DirectedHoTT.Examples.Knot.JudgeWfF
open import DirectedHoTT.Examples.Knot.JudgeWfG
open import DirectedHoTT.Examples.Knot.JudgeWfH
open import DirectedHoTT.Examples.Knot.JudgeWfI
open import DirectedHoTT.Examples.Knot.JudgeWfJ
open import DirectedHoTT.Examples.Knot.JudgeWfK
open import DirectedHoTT.Examples.Knot.JudgeWfL
open import DirectedHoTT.Examples.Knot.JudgeWfM
open import DirectedHoTT.Examples.Knot.JudgeWfN
open import DirectedHoTT.Examples.Knot.JudgeWfO
open import DirectedHoTT.Examples.Knot.JudgeWfP
open import DirectedHoTT.Examples.Knot.JudgeWfQ
open import DirectedHoTT.Examples.Knot.JudgeWfR
open import DirectedHoTT.Examples.Knot.JudgeWfS
open import DirectedHoTT.Examples.Knot.JudgeWfT
open import DirectedHoTT.Examples.Knot.JudgeWfU
open import DirectedHoTT.Examples.Knot.JudgeWfV
open import DirectedHoTT.Examples.Knot.JudgeWfW
open import DirectedHoTT.Examples.Knot.JudgeWfX
open import DirectedHoTT.Examples.Knot.JudgeWfY
open import DirectedHoTT.Examples.Knot.JudgeWfZ
open import DirectedHoTT.Examples.Knot.JudgeWfAA
open import DirectedHoTT.Examples.Knot.JudgeWfAB
open import DirectedHoTT.Examples.Knot.JudgeWfAC
open import DirectedHoTT.Examples.Knot.JudgeWfAD
open import DirectedHoTT.Examples.Knot.JudgeWfAE
open import DirectedHoTT.Examples.Knot.JudgeWfAF
open import DirectedHoTT.Examples.Knot.JudgeWfAG
open import DirectedHoTT.Examples.Knot.JudgeWfAH
open import DirectedHoTT.Examples.Knot.JudgeWfAI
open import DirectedHoTT.Examples.Knot.JudgeWfAJ
open import DirectedHoTT.Examples.Knot.JudgeWfAK
open import DirectedHoTT.Examples.Knot.JudgeWfAL
open import DirectedHoTT.Examples.Knot.JudgeWfAM
open import DirectedHoTT.Examples.Knot.JudgeWfAN
open import DirectedHoTT.Examples.Knot.JudgeWfAO
open import DirectedHoTT.Examples.Knot.JudgeWfAP
open import DirectedHoTT.Examples.Knot.JudgeWfAQ
open import DirectedHoTT.Examples.Knot.JudgeWfAR
open import DirectedHoTT.Examples.Knot.JudgeWfAS
open import DirectedHoTT.Examples.Knot.JudgeWfAT

-- iwf-κ
-- ★ the telescope, back at `Ctx` level: `emit_jrow` had to
--   drop to a bare `Cx` at the premise to stay writable
--   before `JudgeD` existed.
JΨΒ7 JΨΒ8 JΨΒ9 JΨΒ10 JΨΒ11 JΨΒ12 JΨΒ13 JΨΒ14 JΨΒ15 : Ctx
JΨΒ7 = JΨΒ6 ▹ IMu JudgeD IJudge kJΨΒ6
JΨΒ8 = JΨΒ7 ▹ IMu JudgeD IJudge kJΨΒ7
JΨΒ9 = JΨΒ8 ▹ IMu JudgeD IJudge kJΨΒ8
JΨΒ10 = JΨΒ9 ▹ El kJΨΒ9
JΨΒ11 = JΨΒ10 ▹ El kJΨΒ10
JΨΒ12 = JΨΒ11 ▹ El kJΨΒ11
JΨΒ13 = JΨΒ12 ▹ El kJΨΒ12
JΨΒ14 = JΨΒ13 ▹ El kJΨΒ13
JΨΒ15 = JΨΒ14 ▹ El kJΨΒ14

aJΨΒ14 : JΨΒ14 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))))))) ∷ Nat
aJΨΒ14 = ⊢fst (⊢var (there (there (there (there (there (there (there (there (there (there (there (there (there (there here)))))))))))))))
CJΨΒ14 : ICon ⌊ JΨΒ14 ⌋
CJΨΒ14 = iκ kJΨΒ14 iι
W_JΨΒ14 : IConWf JudgeD IJudge JΨΒ14 CJΨΒ14
W_JΨΒ14 =
  iwf-κ kJΨΒ14 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ IxWf (toI aJΨΒ14))
           (toMu (⊢snd (⊢snd (⊢snd (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there (there (there (there (there (there (there (there here)))))))))))))))))))))
           (⊢jsub (⊢⌜IMu⌝ IxWf (toI (fromI (⊢var here))))
                  (toI (fromI (⊢var (there (there (there (there (there (there (there (there (there (there (there (there (there here))))))))))))))))
                  (toI aJΨΒ14)
                  (⊢symN aJΨΒ14 (fromI (⊢var (there (there (there (there (there (there (there (there (there (there (there (there (there here)))))))))))))))
                         (fordAs (⊢var (there (there (there (there here)))))))
                  (toMu (⊢IxIConK (fromI (⊢var (there (there (there (there (there (there (there (there (there (there (there (there (there here))))))))))))))) (fromMu (⊢var (there (there (there (there (there (there (there (there (there (there (there (there here)))))))))))))) (fromMu (⊢var (there (there (there (there (there (there (there (there (there (there (there here))))))))))))) (⊢ICon-kapKv (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))))) (fromI (⊢var (there (there (there (there (there (there (there (there (there (there (there (there (there here))))))))))))))) (fromMu (⊢var (there (there (there (there (there (there (there (there here)))))))))) (fromMu (⊢var (there (there (there (there (there (there (there (there (there here))))))))))))))))
    iwf-ι

aJΨΒ13 : JΨΒ13 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))))) ∷ Nat
aJΨΒ13 = ⊢fst (⊢var (there (there (there (there (there (there (there (there (there (there (there (there (there here))))))))))))))
CJΨΒ13 : ICon ⌊ JΨΒ13 ⌋
CJΨΒ13 = iκ kJΨΒ13 CJΨΒ14
W_JΨΒ13 : IConWf JudgeD IJudge JΨΒ13 CJΨΒ13
W_JΨΒ13 =
  iwf-κ kJΨΒ13 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝
           (toI (⊢fst (⊢snd (⊢snd (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there (there (there (there (there (there (there here))))))))))))))))))))
           (⊢jsub ⊢⌜Nat⌝
                  (toI (fromI (⊢var (there (there (there (there (there (there (there (there (there (there (there (there here)))))))))))))))
                  (toI aJΨΒ13)
                  (⊢symN aJΨΒ13 (fromI (⊢var (there (there (there (there (there (there (there (there (there (there (there (there here))))))))))))))
                         (fordAs (⊢var (there (there (there here))))))
                  (toI (⊢num 4))))
    W_JΨΒ14

aJΨΒ12 : JΨΒ12 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))))) ∷ Nat
aJΨΒ12 = ⊢fst (⊢var (there (there (there (there (there (there (there (there (there (there (there (there here)))))))))))))
CJΨΒ12 : ICon ⌊ JΨΒ12 ⌋
CJΨΒ12 = iκ kJΨΒ12 CJΨΒ13
W_JΨΒ12 : IConWf JudgeD IJudge JΨΒ12 CJΨΒ12
W_JΨΒ12 =
  iwf-κ kJΨΒ12 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTy aJΨΒ12))
           (toMu (⊢fst (⊢snd (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there (there (there (there (there (there here))))))))))))))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTy (fromI (⊢var here))))
                  (toI (fromI (⊢var (there (there (there (there (there (there (there (there (there (there (there here))))))))))))))
                  (toI aJΨΒ12)
                  (⊢symN aJΨΒ12 (fromI (⊢var (there (there (there (there (there (there (there (there (there (there (there here)))))))))))))
                         (fordAs (⊢var (there (there here)))))
                  (toMu (⊢Ty-NatKv (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))) (fromI (⊢var (there (there (there (there (there (there (there (there (there (there (there here)))))))))))))))))
    W_JΨΒ13

aJΨΒ11 : JΨΒ11 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))) ∷ Nat
aJΨΒ11 = ⊢fst (⊢var (there (there (there (there (there (there (there (there (there (there (there here))))))))))))
CJΨΒ11 : ICon ⌊ JΨΒ11 ⌋
CJΨΒ11 = iκ kJΨΒ11 CJΨΒ12
W_JΨΒ11 : IConWf JudgeD IJudge JΨΒ11 CJΨΒ11
W_JΨΒ11 =
  iwf-κ kJΨΒ11 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aJΨΒ11))
           (toMu (⊢fst (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there (there (there (there (there here))))))))))))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (there (there (there (there (there (there (there (there (there (there here)))))))))))))
                  (toI aJΨΒ11)
                  (⊢symN aJΨΒ11 (fromI (⊢var (there (there (there (there (there (there (there (there (there (there here))))))))))))
                         (fordAs (⊢var (there here))))
                  (toMu (⊢Tm-unitKv (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))) (fromI (⊢var (there (there (there (there (there (there (there (there (there (there here))))))))))))))))
    W_JΨΒ12

aJΨΒ10 : JΨΒ10 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))) ∷ Nat
aJΨΒ10 = ⊢fst (⊢var (there (there (there (there (there (there (there (there (there (there here)))))))))))
CJΨΒ10 : ICon ⌊ JΨΒ10 ⌋
CJΨΒ10 = iκ kJΨΒ10 CJΨΒ11
W_JΨΒ10 : IConWf JudgeD IJudge JΨΒ10 CJΨΒ10
W_JΨΒ10 =
  iwf-κ kJΨΒ10 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ CtxWf (toI aJΨΒ10))
           (toMu (⊢fst (⊢snd (⊢var (there (there (there (there (there (there (there (there (there (there here))))))))))))))
           (⊢jsub (⊢⌜IMu⌝ CtxWf (toI (fromI (⊢var here))))
                  (toI (fromI (⊢var (there (there (there (there (there (there (there (there (there here))))))))))))
                  (toI aJΨΒ10)
                  (⊢symN aJΨΒ10 (fromI (⊢var (there (there (there (there (there (there (there (there (there here)))))))))))
                         (fordAs (⊢var here)))
                  (toMu (fromMu (⊢var (there (there (there (there (there (there here)))))))))))
    W_JΨΒ11

CJΨΒ9 : ICon ⌊ JΨΒ9 ⌋
CJΨΒ9 = iκ kJΨΒ9 CJΨΒ10
W_JΨΒ9 : IConWf JudgeD IJudge JΨΒ9 CJΨΒ9
W_JΨΒ9 =
  iwf-κ kJΨΒ9 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝ (toI (⊢fst (⊢var (there (there (there (there (there (there (there (there (there here)))))))))))) (toI (fromI (⊢var (there (there (there (there (there (there (there (there here))))))))))))
    W_JΨΒ10

CJΨΒ8 : ICon ⌊ JΨΒ8 ⌋
CJΨΒ8 = iρ kJΨΒ8 CJΨΒ9
W_JΨΒ8 : IConWf JudgeD IJudge JΨΒ8 CJΨΒ8
W_JΨΒ8 =
  iwf-ρ kJΨΒ8
    (⊢pair (ty-Σ (ty-IMu CtxWf (toI (⊢var here))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢var (there here)))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢var (there (there here))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢var (there (there (there (there here))))))))))) (⊢nsuc (fromI (⊢var (there (there (there (there (there (there (there here))))))))))
      (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢wk (⊢nsuc (fromI (⊢var (there (there (there (there (there (there (there here))))))))))))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (⊢wk (⊢nsuc (fromI (⊢var (there (there (there (there (there (there (there here)))))))))))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢wk (⊢wk (⊢nsuc (fromI (⊢var (there (there (there (there (there (there (there here))))))))))))))))))) (⊢Ctx-extKt (fromI (⊢var (there (there (there (there (there (there (there here))))))))) (fromMu (⊢var (there (there (there (there here)))))) (⊢Ty-ElKv (var (vs (vs (vs (vs (vs (vs (vs vz)))))))) (fromI (⊢var (there (there (there (there (there (there (there here))))))))) (fromMu (⊢var (there (there here))))))
      (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (⊢nsuc (fromI (⊢var (there (there (there (there (there (there (there here))))))))))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢wk (⊢nsuc (fromI (⊢var (there (there (there (there (there (there (there here))))))))))))))))) (⊢Tm-unitKv (nsuc (var (vs (vs (vs (vs (vs (vs (vs vz))))))))) (⊢nsuc (fromI (⊢var (there (there (there (there (there (there (there here)))))))))))
      (⊢pair (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢nsuc (fromI (⊢var (there (there (there (there (there (there (there here))))))))))))))) (⊢Ty-NatKv (nsuc (var (vs (vs (vs (vs (vs (vs (vs vz))))))))) (⊢nsuc (fromI (⊢var (there (there (there (there (there (there (there here)))))))))))
      (⊢pair (ty-IMu IxWf (toI (⊢wk (⊢nsuc (fromI (⊢var (there (there (there (there (there (there (there here))))))))))))) (⊢num 4) (⊢IxIConK (⊢nsuc (fromI (⊢var (there (there (there (there (there (there (there here)))))))))) (fromMu (⊢var (there (there (there (there (there (there here)))))))) (fromMu (⊢var (there (there (there (there (there here))))))) (fromMu (⊢var (there (there (there here)))))))))))
    W_JΨΒ9

CJΨΒ7 : ICon ⌊ JΨΒ7 ⌋
CJΨΒ7 = iρ kJΨΒ7 CJΨΒ8
W_JΨΒ7 : IConWf JudgeD IJudge JΨΒ7 CJΨΒ7
W_JΨΒ7 =
  iwf-ρ kJΨΒ7
    (⊢pair (ty-Σ (ty-IMu CtxWf (toI (⊢var here))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢var (there here)))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢var (there (there here))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢var (there (there (there (there here))))))))))) (fromI (⊢var (there (there (there (there (there (there here))))))))
      (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢wk (fromI (⊢var (there (there (there (there (there (there here))))))))))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (⊢wk (fromI (⊢var (there (there (there (there (there (there here)))))))))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢wk (⊢wk (fromI (⊢var (there (there (there (there (there (there here))))))))))))))))) (fromMu (⊢var (there (there (there here)))))
      (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (fromI (⊢var (there (there (there (there (there (there here))))))))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢wk (fromI (⊢var (there (there (there (there (there (there here))))))))))))))) (fromMu (⊢var (there here)))
      (⊢pair (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (fromI (⊢var (there (there (there (there (there (there here))))))))))))) (⊢Ty-UKv (var (vs (vs (vs (vs (vs (vs vz))))))) (fromI (⊢var (there (there (there (there (there (there here)))))))))
      (⊢pair (ty-IMu IxWf (toI (⊢wk (fromI (⊢var (there (there (there (there (there (there here))))))))))) (⊢num 1) (⊢IxNoneK (fromI (⊢var (there (there (there (there (there (there here))))))))))))))
    W_JΨΒ8

CJΨΒ6 : ICon ⌊ JΨΒ6 ⌋
CJΨΒ6 = iρ kJΨΒ6 CJΨΒ7
W_JΨΒ6 : IConWf JudgeD IJudge JΨΒ6 CJΨΒ6
W_JΨΒ6 =
  iwf-ρ kJΨΒ6
    (⊢pair (ty-Σ (ty-IMu CtxWf (toI (⊢var here))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢var (there here)))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢var (there (there here))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢var (there (there (there (there here))))))))))) (fromI (⊢var (there (there (there (there (there here)))))))
      (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢wk (fromI (⊢var (there (there (there (there (there here)))))))))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (⊢wk (fromI (⊢var (there (there (there (there (there here))))))))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢wk (⊢wk (fromI (⊢var (there (there (there (there (there here)))))))))))))))) (fromMu (⊢var (there (there here))))
      (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (fromI (⊢var (there (there (there (there (there here)))))))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢wk (fromI (⊢var (there (there (there (there (there here)))))))))))))) (fromMu (⊢var here))
      (⊢pair (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (fromI (⊢var (there (there (there (there (there here)))))))))))) (⊢Ty-NatKv (var (vs (vs (vs (vs (vs vz)))))) (fromI (⊢var (there (there (there (there (there here))))))))
      (⊢pair (ty-IMu IxWf (toI (⊢wk (fromI (⊢var (there (there (there (there (there here)))))))))) (⊢num 5) (⊢IxNoneK (fromI (⊢var (there (there (there (there (there here)))))))))))))
    W_JΨΒ7

CJΨΒ5 : ICon ⌊ JΨΒ5 ⌋
CJΨΒ5 = iκ kJΨΒ5 CJΨΒ6
W_JΨΒ5 : IConWf JudgeD IJudge JΨΒ5 CJΨΒ5
W_JΨΒ5 =
  iwf-κ kJΨΒ5 (icw-imu (pair sTm (var (vs (vs (vs (vs vz)))))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (there (there (there (there here))))))))
    W_JΨΒ6

CJΨΒ4 : ICon ⌊ JΨΒ4 ⌋
CJΨΒ4 = iκ kJΨΒ4 CJΨΒ5
W_JΨΒ4 : IConWf JudgeD IJudge JΨΒ4 CJΨΒ4
W_JΨΒ4 =
  iwf-κ kJΨΒ4 (icw-imu (pair sICon (nsuc (var (vs (vs (vs vz)))))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sICon (⊢nsuc (fromI (⊢var (there (there (there here))))))))
    W_JΨΒ5

CJΨΒ3 : ICon ⌊ JΨΒ3 ⌋
CJΨΒ3 = iκ kJΨΒ3 CJΨΒ4
W_JΨΒ3 : IConWf JudgeD IJudge JΨΒ3 CJΨΒ3
W_JΨΒ3 =
  iwf-κ kJΨΒ3 (icw-imu (var (vs (vs vz))) CtxWf)
    (⊢⌜IMu⌝ CtxWf (toI (fromI (⊢var (there (there here))))))
    W_JΨΒ4

CJΨΒ2 : ICon ⌊ JΨΒ2 ⌋
CJΨΒ2 = iκ kJΨΒ2 CJΨΒ3
W_JΨΒ2 : IConWf JudgeD IJudge JΨΒ2 CJΨΒ2
W_JΨΒ2 =
  iwf-κ kJΨΒ2 (icw-imu (pair sTy nzero) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTy ⊢nzero))
    W_JΨΒ3

CJΨΒ1 : ICon ⌊ JΨΒ1 ⌋
CJΨΒ1 = iκ kJΨΒ1 CJΨΒ2
W_JΨΒ1 : IConWf JudgeD IJudge JΨΒ1 CJΨΒ1
W_JΨΒ1 =
  iwf-κ kJΨΒ1 (icw-imu (pair sIDesc nzero) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sIDesc ⊢nzero))
    W_JΨΒ2

CJΨΒ0 : ICon ⌊ JΨΒ0 ⌋
CJΨΒ0 = iκ kJΨΒ0 CJΨΒ1
W_JΨΒ0 : IConWf JudgeD IJudge JΨΒ0 CJΨΒ0
W_JΨΒ0 =
  iwf-κ kJΨΒ0 (icw-clo ⌜Nat⌝ ⊢⌜Nat⌝) ⊢⌜Nat⌝
    W_JΨΒ1

jdiwf-κWf : IConWf JudgeD IJudge JΨΒ0 jdiwf-κ
jdiwf-κWf = W_JΨΒ0

