--- GENERATED by tools/gen-knot.py — do not edit.
------------------------------------------------------------------------
-- OCP-0009 · EXAMPLES — ★★★ `_⊢ty_ / _⊢_∷_` IS A WELL-FORMED DESCRIPTION.
--
-- ⚠⚠ THIS MODULE NEEDS THE **COMPACTING COLLECTOR**.
--
--   MEASURED 2026-08-31, the commit that added `⊢app`/`⊢pair`/`⊢snd`/
--   `⊢jsub`: `JudgeWfA` OOM-KILLED (143) on the default `-A64m` and
--   passed on `-A64m -c` at 179s.  `JudgeWfB` passed either way at 74s.
--   ⚠ Four rows moved it across the cap — and the two halves hold the
--     SAME number of rows, so the count is not what separates them.
--     `_⊢ty_`/`_⊢_∷_`'s index has FIVE components and the A half's rows
--     carry the deeper telescopes.
--
--   ⚠ BEFORE THIS MARKER THE MODULE WAS GREEN ONLY BY THE SWEEP'S
--     RETRY: `tools/sweep.sh` takes the OOM kill, then re-runs with
--     `-c`.  That is a pass, but it costs an OOM every sweep and it
--     hides the cost from anyone checking the module directly.
--
--   `tools/sweep.sh` greps this header for the phrase above and
--   switches collectors on its own (`needs_c`), which is why the words
--   are spelled out rather than described.
--
-- ⚠⚠ THE RULES ARE **PARSED OUT OF `Spec/Typing.agda`**, not transcribed.
--   A hand-written table is one chance per row to name the wrong
--   variable — the error class `Knot/LookupGen` exists to catch, and one
--   an `ICon` never reveals, because it type-checks with ANY in-scope
--   variable of the right type.  The Agda-former → knot-constructor map
--   comes from `KNOT`'s own `decl` strings, so nothing is typed twice.
--
-- ★ ANY RULE THAT DID NOT TRANSLATE IS NAMED BELOW.  Emitting a subset
--   silently is `verification-that-covers-less-than-it-claims`.
------------------------------------------------------------------------

{-# OPTIONS --safe #-}
module DirectedHoTT.Examples.Knot.JudgeWfAW where
open import normalizer.Syntax.Types using ( _≡_; refl )
open import Agda.Builtin.Nat using ( zero; suc ) renaming ( Nat to ℕ )
open import DirectedHoTT.Spec.Syntax
  using ( Cx; ε; _∙; RTy; RTm; var; vz; vs; pair; fst; snd; nsuc; nzero
        ; El; IMu; Σ'; Nat
        ; ⌜Nat⌝; ⌜Id⌝; ⌜IMu⌝; jsub; ICon; IDesc; iι; iρ; iκ; inil; _◂_; εwkTy )
open import DirectedHoTT.Spec.Typing
  using ( Ctx; ◇; _▹_; ⌊_⌋; _⊢_∷_; _⊢ty_
        ; IConWf; iwf-ι; iwf-κ; iwf-ρ; ICodeWf; icw-clo; icw-ford; icw-imu
        ; IDescWf; idwf-nil; idwf-cons
        ; ⊢var; here; there; ⊢fst; ⊢snd; ⊢nsuc; ⊢nzero
        ; ⊢⌜Nat⌝; ⊢⌜Id⌝; ⊢⌜IMu⌝; ⊢jsub
        ; ⊢pair; ty-Σ; ty-Nat; ty-IMu
        ; ξ-pairˡ; ξ-pairʳ; ξ-nsuc; βfst; βsnd )
open import DirectedHoTT.Examples.Knot.Sorts
  using ( IPair; sTy; sTm; sDesc; sDCon; sIDesc; sICon; sVar
        ; toI; fromI; ⊢ixP; ⊢sTy; ⊢sTm; ⊢sDesc; ⊢sDCon; ⊢sIDesc; ⊢sICon; ⊢sVar
        ; num; ⊢num )
open import DirectedHoTT.Examples.Knot.Desc using ( KnotD )
open import DirectedHoTT.Examples.Knot.Wf using ( KnotWf )
open import DirectedHoTT.Examples.Knot.Ctors
open import DirectedHoTT.Examples.Knot.CtorsV
open import DirectedHoTT.Examples.Knot.Build using ( Var-vzK; Var-vsK; ⊢Var-vzKt; ⊢Var-vsKt )
open import DirectedHoTT.Examples.Knot.WkSub using ( wkTmK; ⊢wkTmK; wkTyK; ⊢wkTyK )
-- ★ STEP 5 — `⊢con` needs these.  `lookupDK`/`ilookupDK` are already in
--   the kernel's argument order; `payTyKᵏ` is `Knot/KAdapt`'s adapter,
--   because `payTy D C` maps to `payTyK n C D` with the arguments SWAPPED
--   and `_SUBST_CT` only renames a head.
open import DirectedHoTT.Examples.Knot.LookupD using ( lookupDK; ⊢lookupDK )
open import DirectedHoTT.Examples.Knot.ILookupD using ( ilookupDK; ⊢ilookupDK )
open import DirectedHoTT.Examples.Knot.KAdapt using ( payTyKᵏ; ⊢payTyKᵏ; ipayTyKᵏ; ⊢ipayTyKᵏ )
open import DirectedHoTT.Lib.ICast using ( toMu; fromMu; fordAs; muFwd )
open import DirectedHoTT.Lib.ArithComm using ( symN; ⊢symN )
open import DirectedHoTT.Metatheory.SubjectReduction using ( ⊢wk )
open import DirectedHoTT.Examples.Knot.Single using ( singleK; ⊢singleK )
open import DirectedHoTT.Examples.Knot.SubApp
  using ( subTmAtK; subTyAtK; ⊢subTmAtK; ⊢subTyAtK )
open import DirectedHoTT.Examples.Knot.SubMot using ( extNK; ⊢extNK )
open import DirectedHoTT.Examples.Knot.Pw using ( pwK; ⊢pwK )
open import DirectedHoTT.Examples.Knot.Stk
  using ( stkAK; ⊢stkAK; stkCK; ⊢stkCK; flatK; ⊢flatK )
open import DirectedHoTT.Examples.Knot.Nrs using ( nrsSubK; ⊢nrsSubK )
open import DirectedHoTT.Examples.Knot.PwBody using ( pwBodyK; ⊢pwBodyK )
open import DirectedHoTT.Examples.Knot.CtxD
  using ( CtxD; INat; CtxWf; Ctx-extK; ⊢Ctx-extKt; Ctx-empK; ⊢Ctx-empK )
open import DirectedHoTT.Examples.Knot.EWk using ( εwkK; ⊢εwkK; isingleK; ⊢isingleK )
open import DirectedHoTT.Examples.Knot.SubMot
  using ( sortMap-ty; sortMap-tm; sortMap-desc; sortMap-dcon
        ; sortMap-idesc; sortMap-icon; sortMap-var )
open import DirectedHoTT.Examples.Knot.Lookup using ( LkD; ILk; LkWf )
open import DirectedHoTT.Examples.Knot.ConvRows using ( ConvD; IConv )
open import DirectedHoTT.Examples.Knot.ConvWf using ( ConvWf )
open import DirectedHoTT.Examples.Knot.NoNatCRows using ( NoNatCD; INoNatC )
open import DirectedHoTT.Examples.Knot.NoNatCWf using ( NoNatCWf )
open import DirectedHoTT.Examples.Knot.InDRows using ( InDD; IInD )
open import DirectedHoTT.Examples.Knot.InDWf using ( InDWf )
open import DirectedHoTT.Examples.Knot.InIDRows using ( InIDD; IInID )
open import DirectedHoTT.Examples.Knot.InIDWf using ( InIDWf )
open import DirectedHoTT.Examples.Knot.IxD
  using ( IxD; IxWf; IxNoneK; ⊢IxNoneK; IxDConK; ⊢IxDConK; IxDescK; ⊢IxDescK
        ; IxIConK; ⊢IxIConK; IxIDescK; ⊢IxIDescK )
open import DirectedHoTT.Examples.Knot.JudgeRows
open import DirectedHoTT.Examples.Knot.JudgeWfA
open import DirectedHoTT.Examples.Knot.JudgeWfB
open import DirectedHoTT.Examples.Knot.JudgeWfC
open import DirectedHoTT.Examples.Knot.JudgeWfD
open import DirectedHoTT.Examples.Knot.JudgeWfE
open import DirectedHoTT.Examples.Knot.JudgeWfF
open import DirectedHoTT.Examples.Knot.JudgeWfG
open import DirectedHoTT.Examples.Knot.JudgeWfH
open import DirectedHoTT.Examples.Knot.JudgeWfI
open import DirectedHoTT.Examples.Knot.JudgeWfJ
open import DirectedHoTT.Examples.Knot.JudgeWfK
open import DirectedHoTT.Examples.Knot.JudgeWfL
open import DirectedHoTT.Examples.Knot.JudgeWfM
open import DirectedHoTT.Examples.Knot.JudgeWfN
open import DirectedHoTT.Examples.Knot.JudgeWfO
open import DirectedHoTT.Examples.Knot.JudgeWfP
open import DirectedHoTT.Examples.Knot.JudgeWfQ
open import DirectedHoTT.Examples.Knot.JudgeWfR
open import DirectedHoTT.Examples.Knot.JudgeWfS
open import DirectedHoTT.Examples.Knot.JudgeWfT
open import DirectedHoTT.Examples.Knot.JudgeWfU
open import DirectedHoTT.Examples.Knot.JudgeWfV
open import DirectedHoTT.Examples.Knot.JudgeWfW
open import DirectedHoTT.Examples.Knot.JudgeWfX
open import DirectedHoTT.Examples.Knot.JudgeWfY
open import DirectedHoTT.Examples.Knot.JudgeWfZ
open import DirectedHoTT.Examples.Knot.JudgeWfAA
open import DirectedHoTT.Examples.Knot.JudgeWfAB
open import DirectedHoTT.Examples.Knot.JudgeWfAC
open import DirectedHoTT.Examples.Knot.JudgeWfAD
open import DirectedHoTT.Examples.Knot.JudgeWfAE
open import DirectedHoTT.Examples.Knot.JudgeWfAF
open import DirectedHoTT.Examples.Knot.JudgeWfAG
open import DirectedHoTT.Examples.Knot.JudgeWfAH
open import DirectedHoTT.Examples.Knot.JudgeWfAI
open import DirectedHoTT.Examples.Knot.JudgeWfAJ
open import DirectedHoTT.Examples.Knot.JudgeWfAK
open import DirectedHoTT.Examples.Knot.JudgeWfAL
open import DirectedHoTT.Examples.Knot.JudgeWfAM
open import DirectedHoTT.Examples.Knot.JudgeWfAN
open import DirectedHoTT.Examples.Knot.JudgeWfAO
open import DirectedHoTT.Examples.Knot.JudgeWfAP
open import DirectedHoTT.Examples.Knot.JudgeWfAQ
open import DirectedHoTT.Examples.Knot.JudgeWfAR
open import DirectedHoTT.Examples.Knot.JudgeWfAS
open import DirectedHoTT.Examples.Knot.JudgeWfAT
open import DirectedHoTT.Examples.Knot.JudgeWfAU
open import DirectedHoTT.Examples.Knot.JudgeWfAV

-- icw-clo
-- ★ the telescope, back at `Ctx` level: `emit_jrow` had to
--   drop to a bare `Cx` at the premise to stay writable
--   before `JudgeD` existed.
JΑΓ4 JΑΓ5 JΑΓ6 JΑΓ7 JΑΓ8 JΑΓ9 JΑΓ10 : Ctx
JΑΓ4 = JΑΓ3 ▹ IMu JudgeD IJudge kJΑΓ3
JΑΓ5 = JΑΓ4 ▹ El kJΑΓ4
JΑΓ6 = JΑΓ5 ▹ El kJΑΓ5
JΑΓ7 = JΑΓ6 ▹ El kJΑΓ6
JΑΓ8 = JΑΓ7 ▹ El kJΑΓ7
JΑΓ9 = JΑΓ8 ▹ El kJΑΓ8
JΑΓ10 = JΑΓ9 ▹ El kJΑΓ9

aJΑΓ9 : JΑΓ9 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))) ∷ Nat
aJΑΓ9 = ⊢fst (⊢var (there (there (there (there (there (there (there (there (there here))))))))))
CJΑΓ9 : ICon ⌊ JΑΓ9 ⌋
CJΑΓ9 = iκ kJΑΓ9 iι
W_JΑΓ9 : IConWf JudgeD IJudge JΑΓ9 CJΑΓ9
W_JΑΓ9 =
  iwf-κ kJΑΓ9 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ IxWf (toI aJΑΓ9))
           (toMu (⊢snd (⊢snd (⊢snd (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there (there (there here))))))))))))))))
           (⊢jsub (⊢⌜IMu⌝ IxWf (toI (fromI (⊢var here))))
                  (toI (fromI (⊢var (there (there (there (there (there (there (there (there here)))))))))))
                  (toI aJΑΓ9)
                  (⊢symN aJΑΓ9 (fromI (⊢var (there (there (there (there (there (there (there (there here))))))))))
                         (fordAs (⊢var (there (there (there (there here)))))))
                  (toMu (⊢IxNoneK (fromI (⊢var (there (there (there (there (there (there (there (there here))))))))))))))
    iwf-ι

aJΑΓ8 : JΑΓ8 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))) ∷ Nat
aJΑΓ8 = ⊢fst (⊢var (there (there (there (there (there (there (there (there here)))))))))
CJΑΓ8 : ICon ⌊ JΑΓ8 ⌋
CJΑΓ8 = iκ kJΑΓ8 CJΑΓ9
W_JΑΓ8 : IConWf JudgeD IJudge JΑΓ8 CJΑΓ8
W_JΑΓ8 =
  iwf-κ kJΑΓ8 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝
           (toI (⊢fst (⊢snd (⊢snd (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there (there here)))))))))))))))
           (⊢jsub ⊢⌜Nat⌝
                  (toI (fromI (⊢var (there (there (there (there (there (there (there here))))))))))
                  (toI aJΑΓ8)
                  (⊢symN aJΑΓ8 (fromI (⊢var (there (there (there (there (there (there (there here)))))))))
                         (fordAs (⊢var (there (there (there here))))))
                  (toI (⊢num 5))))
    W_JΑΓ9

aJΑΓ7 : JΑΓ7 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs vz)))))))) ∷ Nat
aJΑΓ7 = ⊢fst (⊢var (there (there (there (there (there (there (there here))))))))
CJΑΓ7 : ICon ⌊ JΑΓ7 ⌋
CJΑΓ7 = iκ kJΑΓ7 CJΑΓ8
W_JΑΓ7 : IConWf JudgeD IJudge JΑΓ7 CJΑΓ7
W_JΑΓ7 =
  iwf-κ kJΑΓ7 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTy aJΑΓ7))
           (toMu (⊢fst (⊢snd (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there here)))))))))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTy (fromI (⊢var here))))
                  (toI (fromI (⊢var (there (there (there (there (there (there here)))))))))
                  (toI aJΑΓ7)
                  (⊢symN aJΑΓ7 (fromI (⊢var (there (there (there (there (there (there here))))))))
                         (fordAs (⊢var (there (there here)))))
                  (toMu (⊢Ty-NatKv (var (vs (vs (vs (vs (vs (vs vz))))))) (fromI (⊢var (there (there (there (there (there (there here))))))))))))
    W_JΑΓ8

aJΑΓ6 : JΑΓ6 ⊢ fst (var (vs (vs (vs (vs (vs (vs vz))))))) ∷ Nat
aJΑΓ6 = ⊢fst (⊢var (there (there (there (there (there (there here)))))))
CJΑΓ6 : ICon ⌊ JΑΓ6 ⌋
CJΑΓ6 = iκ kJΑΓ6 CJΑΓ7
W_JΑΓ6 : IConWf JudgeD IJudge JΑΓ6 CJΑΓ6
W_JΑΓ6 =
  iwf-κ kJΑΓ6 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aJΑΓ6))
           (toMu (⊢fst (⊢snd (⊢snd (⊢var (there (there (there (there (there (there here)))))))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (there (there (there (there (there here))))))))
                  (toI aJΑΓ6)
                  (⊢symN aJΑΓ6 (fromI (⊢var (there (there (there (there (there here)))))))
                         (fordAs (⊢var (there here))))
                  (toMu (⊢εwkK ⊢sTm sortMap-tm (fromI (⊢var (there (there (there (there (there here))))))) (fromMu (⊢var (there (there (there here)))))))))
    W_JΑΓ7

aJΑΓ5 : JΑΓ5 ⊢ fst (var (vs (vs (vs (vs (vs vz)))))) ∷ Nat
aJΑΓ5 = ⊢fst (⊢var (there (there (there (there (there here))))))
CJΑΓ5 : ICon ⌊ JΑΓ5 ⌋
CJΑΓ5 = iκ kJΑΓ5 CJΑΓ6
W_JΑΓ5 : IConWf JudgeD IJudge JΑΓ5 CJΑΓ5
W_JΑΓ5 =
  iwf-κ kJΑΓ5 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ CtxWf (toI aJΑΓ5))
           (toMu (⊢fst (⊢snd (⊢var (there (there (there (there (there here)))))))))
           (⊢jsub (⊢⌜IMu⌝ CtxWf (toI (fromI (⊢var here))))
                  (toI (fromI (⊢var (there (there (there (there here)))))))
                  (toI aJΑΓ5)
                  (⊢symN aJΑΓ5 (fromI (⊢var (there (there (there (there here))))))
                         (fordAs (⊢var here)))
                  (toMu (fromMu (⊢var (there (there (there here))))))))
    W_JΑΓ6

CJΑΓ4 : ICon ⌊ JΑΓ4 ⌋
CJΑΓ4 = iκ kJΑΓ4 CJΑΓ5
W_JΑΓ4 : IConWf JudgeD IJudge JΑΓ4 CJΑΓ4
W_JΑΓ4 =
  iwf-κ kJΑΓ4 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝ (toI (⊢fst (⊢var (there (there (there (there here))))))) (toI (fromI (⊢var (there (there (there here)))))))
    W_JΑΓ5

CJΑΓ3 : ICon ⌊ JΑΓ3 ⌋
CJΑΓ3 = iρ kJΑΓ3 CJΑΓ4
W_JΑΓ3 : IConWf JudgeD IJudge JΑΓ3 CJΑΓ3
W_JΑΓ3 =
  iwf-ρ kJΑΓ3
    (⊢pair (ty-Σ (ty-IMu CtxWf (toI (⊢var here))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢var (there here)))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢var (there (there here))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢var (there (there (there (there here))))))))))) (⊢num 0)
      (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢wk (⊢num 0)))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (⊢wk (⊢num 0))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢wk (⊢wk (⊢num 0)))))))))) ⊢Ctx-empK
      (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (⊢num 0)))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢wk (⊢num 0)))))))) (fromMu (⊢var here))
      (⊢pair (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢num 0)))))) (⊢Ty-UKv (num 0) (⊢num 0))
      (⊢pair (ty-IMu IxWf (toI (⊢wk (⊢num 0)))) (⊢num 1) (⊢IxNoneK (⊢num 0)))))))
    W_JΑΓ4

CJΑΓ2 : ICon ⌊ JΑΓ2 ⌋
CJΑΓ2 = iκ kJΑΓ2 CJΑΓ3
W_JΑΓ2 : IConWf JudgeD IJudge JΑΓ2 CJΑΓ2
W_JΑΓ2 =
  iwf-κ kJΑΓ2 (icw-imu (pair sTm nzero) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm ⊢nzero))
    W_JΑΓ3

CJΑΓ1 : ICon ⌊ JΑΓ1 ⌋
CJΑΓ1 = iκ kJΑΓ1 CJΑΓ2
W_JΑΓ1 : IConWf JudgeD IJudge JΑΓ1 CJΑΓ1
W_JΑΓ1 =
  iwf-κ kJΑΓ1 (icw-imu (var vz) CtxWf)
    (⊢⌜IMu⌝ CtxWf (toI (fromI (⊢var here))))
    W_JΑΓ2

CJΑΓ0 : ICon ⌊ JΑΓ0 ⌋
CJΑΓ0 = iκ kJΑΓ0 CJΑΓ1
W_JΑΓ0 : IConWf JudgeD IJudge JΑΓ0 CJΑΓ0
W_JΑΓ0 =
  iwf-κ kJΑΓ0 (icw-clo ⌜Nat⌝ ⊢⌜Nat⌝) ⊢⌜Nat⌝
    W_JΑΓ1

jdicw-cloWf : IConWf JudgeD IJudge JΑΓ0 jdicw-clo
jdicw-cloWf = W_JΑΓ0

