--- GENERATED by tools/gen-knot.py — do not edit.
------------------------------------------------------------------------
-- OCP-0009 · EXAMPLES — ★★★ `_⊢ty_ / _⊢_∷_` IS A WELL-FORMED DESCRIPTION.
--
-- ⚠⚠ THIS MODULE NEEDS THE **COMPACTING COLLECTOR**.
--
--   MEASURED 2026-08-31, the commit that added `⊢app`/`⊢pair`/`⊢snd`/
--   `⊢jsub`: `JudgeWfA` OOM-KILLED (143) on the default `-A64m` and
--   passed on `-A64m -c` at 179s.  `JudgeWfB` passed either way at 74s.
--   ⚠ Four rows moved it across the cap — and the two halves hold the
--     SAME number of rows, so the count is not what separates them.
--     `_⊢ty_`/`_⊢_∷_`'s index has FIVE components and the A half's rows
--     carry the deeper telescopes.
--
--   ⚠ BEFORE THIS MARKER THE MODULE WAS GREEN ONLY BY THE SWEEP'S
--     RETRY: `tools/sweep.sh` takes the OOM kill, then re-runs with
--     `-c`.  That is a pass, but it costs an OOM every sweep and it
--     hides the cost from anyone checking the module directly.
--
--   `tools/sweep.sh` greps this header for the phrase above and
--   switches collectors on its own (`needs_c`), which is why the words
--   are spelled out rather than described.
--
-- ⚠⚠ THE RULES ARE **PARSED OUT OF `Spec/Typing.agda`**, not transcribed.
--   A hand-written table is one chance per row to name the wrong
--   variable — the error class `Knot/LookupGen` exists to catch, and one
--   an `ICon` never reveals, because it type-checks with ANY in-scope
--   variable of the right type.  The Agda-former → knot-constructor map
--   comes from `KNOT`'s own `decl` strings, so nothing is typed twice.
--
-- ★ ANY RULE THAT DID NOT TRANSLATE IS NAMED BELOW.  Emitting a subset
--   silently is `verification-that-covers-less-than-it-claims`.
------------------------------------------------------------------------

{-# OPTIONS --safe #-}
module DirectedHoTT.Examples.Knot.JudgeWfAN where
open import normalizer.Syntax.Types using ( _≡_; refl )
open import Agda.Builtin.Nat using ( zero; suc ) renaming ( Nat to ℕ )
open import DirectedHoTT.Spec.Syntax
  using ( Cx; ε; _∙; RTy; RTm; var; vz; vs; pair; fst; snd; nsuc; nzero
        ; El; IMu; Σ'; Nat
        ; ⌜Nat⌝; ⌜Id⌝; ⌜IMu⌝; jsub; ICon; IDesc; iι; iρ; iκ; inil; _◂_; εwkTy )
open import DirectedHoTT.Spec.Typing
  using ( Ctx; ◇; _▹_; ⌊_⌋; _⊢_∷_; _⊢ty_
        ; IConWf; iwf-ι; iwf-κ; iwf-ρ; ICodeWf; icw-clo; icw-ford; icw-imu
        ; IDescWf; idwf-nil; idwf-cons
        ; ⊢var; here; there; ⊢fst; ⊢snd; ⊢nsuc; ⊢nzero
        ; ⊢⌜Nat⌝; ⊢⌜Id⌝; ⊢⌜IMu⌝; ⊢jsub
        ; ⊢pair; ty-Σ; ty-Nat; ty-IMu
        ; ξ-pairˡ; ξ-pairʳ; ξ-nsuc; βfst; βsnd )
open import DirectedHoTT.Examples.Knot.Sorts
  using ( IPair; sTy; sTm; sDesc; sDCon; sIDesc; sICon; sVar
        ; toI; fromI; ⊢ixP; ⊢sTy; ⊢sTm; ⊢sDesc; ⊢sDCon; ⊢sIDesc; ⊢sICon; ⊢sVar
        ; num; ⊢num )
open import DirectedHoTT.Examples.Knot.Desc using ( KnotD )
open import DirectedHoTT.Examples.Knot.Wf using ( KnotWf )
open import DirectedHoTT.Examples.Knot.Ctors
open import DirectedHoTT.Examples.Knot.CtorsV
open import DirectedHoTT.Examples.Knot.Build using ( Var-vzK; Var-vsK; ⊢Var-vzKt; ⊢Var-vsKt )
open import DirectedHoTT.Examples.Knot.WkSub using ( wkTmK; ⊢wkTmK; wkTyK; ⊢wkTyK )
-- ★ STEP 5 — `⊢con` needs these.  `lookupDK`/`ilookupDK` are already in
--   the kernel's argument order; `payTyKᵏ` is `Knot/KAdapt`'s adapter,
--   because `payTy D C` maps to `payTyK n C D` with the arguments SWAPPED
--   and `_SUBST_CT` only renames a head.
open import DirectedHoTT.Examples.Knot.LookupD using ( lookupDK; ⊢lookupDK )
open import DirectedHoTT.Examples.Knot.ILookupD using ( ilookupDK; ⊢ilookupDK )
open import DirectedHoTT.Examples.Knot.KAdapt using ( payTyKᵏ; ⊢payTyKᵏ; ipayTyKᵏ; ⊢ipayTyKᵏ )
open import DirectedHoTT.Lib.ICast using ( toMu; fromMu; fordAs; muFwd )
open import DirectedHoTT.Lib.ArithComm using ( symN; ⊢symN )
open import DirectedHoTT.Metatheory.SubjectReduction using ( ⊢wk )
open import DirectedHoTT.Examples.Knot.Single using ( singleK; ⊢singleK )
open import DirectedHoTT.Examples.Knot.SubApp
  using ( subTmAtK; subTyAtK; ⊢subTmAtK; ⊢subTyAtK )
open import DirectedHoTT.Examples.Knot.SubMot using ( extNK; ⊢extNK )
open import DirectedHoTT.Examples.Knot.Pw using ( pwK; ⊢pwK )
open import DirectedHoTT.Examples.Knot.Stk
  using ( stkAK; ⊢stkAK; stkCK; ⊢stkCK; flatK; ⊢flatK )
open import DirectedHoTT.Examples.Knot.Nrs using ( nrsSubK; ⊢nrsSubK )
open import DirectedHoTT.Examples.Knot.PwBody using ( pwBodyK; ⊢pwBodyK )
open import DirectedHoTT.Examples.Knot.CtxD
  using ( CtxD; INat; CtxWf; Ctx-extK; ⊢Ctx-extKt; Ctx-empK; ⊢Ctx-empK )
open import DirectedHoTT.Examples.Knot.EWk using ( εwkK; ⊢εwkK; isingleK; ⊢isingleK )
open import DirectedHoTT.Examples.Knot.SubMot
  using ( sortMap-ty; sortMap-tm; sortMap-desc; sortMap-dcon
        ; sortMap-idesc; sortMap-icon; sortMap-var )
open import DirectedHoTT.Examples.Knot.Lookup using ( LkD; ILk; LkWf )
open import DirectedHoTT.Examples.Knot.ConvRows using ( ConvD; IConv )
open import DirectedHoTT.Examples.Knot.ConvWf using ( ConvWf )
open import DirectedHoTT.Examples.Knot.NoNatCRows using ( NoNatCD; INoNatC )
open import DirectedHoTT.Examples.Knot.NoNatCWf using ( NoNatCWf )
open import DirectedHoTT.Examples.Knot.InDRows using ( InDD; IInD )
open import DirectedHoTT.Examples.Knot.InDWf using ( InDWf )
open import DirectedHoTT.Examples.Knot.InIDRows using ( InIDD; IInID )
open import DirectedHoTT.Examples.Knot.InIDWf using ( InIDWf )
open import DirectedHoTT.Examples.Knot.IxD
  using ( IxD; IxWf; IxNoneK; ⊢IxNoneK; IxDConK; ⊢IxDConK; IxDescK; ⊢IxDescK
        ; IxIConK; ⊢IxIConK; IxIDescK; ⊢IxIDescK )
open import DirectedHoTT.Examples.Knot.JudgeRows
open import DirectedHoTT.Examples.Knot.JudgeWfA
open import DirectedHoTT.Examples.Knot.JudgeWfB
open import DirectedHoTT.Examples.Knot.JudgeWfC
open import DirectedHoTT.Examples.Knot.JudgeWfD
open import DirectedHoTT.Examples.Knot.JudgeWfE
open import DirectedHoTT.Examples.Knot.JudgeWfF
open import DirectedHoTT.Examples.Knot.JudgeWfG
open import DirectedHoTT.Examples.Knot.JudgeWfH
open import DirectedHoTT.Examples.Knot.JudgeWfI
open import DirectedHoTT.Examples.Knot.JudgeWfJ
open import DirectedHoTT.Examples.Knot.JudgeWfK
open import DirectedHoTT.Examples.Knot.JudgeWfL
open import DirectedHoTT.Examples.Knot.JudgeWfM
open import DirectedHoTT.Examples.Knot.JudgeWfN
open import DirectedHoTT.Examples.Knot.JudgeWfO
open import DirectedHoTT.Examples.Knot.JudgeWfP
open import DirectedHoTT.Examples.Knot.JudgeWfQ
open import DirectedHoTT.Examples.Knot.JudgeWfR
open import DirectedHoTT.Examples.Knot.JudgeWfS
open import DirectedHoTT.Examples.Knot.JudgeWfT
open import DirectedHoTT.Examples.Knot.JudgeWfU
open import DirectedHoTT.Examples.Knot.JudgeWfV
open import DirectedHoTT.Examples.Knot.JudgeWfW
open import DirectedHoTT.Examples.Knot.JudgeWfX
open import DirectedHoTT.Examples.Knot.JudgeWfY
open import DirectedHoTT.Examples.Knot.JudgeWfZ
open import DirectedHoTT.Examples.Knot.JudgeWfAA
open import DirectedHoTT.Examples.Knot.JudgeWfAB
open import DirectedHoTT.Examples.Knot.JudgeWfAC
open import DirectedHoTT.Examples.Knot.JudgeWfAD
open import DirectedHoTT.Examples.Knot.JudgeWfAE
open import DirectedHoTT.Examples.Knot.JudgeWfAF
open import DirectedHoTT.Examples.Knot.JudgeWfAG
open import DirectedHoTT.Examples.Knot.JudgeWfAH
open import DirectedHoTT.Examples.Knot.JudgeWfAI
open import DirectedHoTT.Examples.Knot.JudgeWfAJ
open import DirectedHoTT.Examples.Knot.JudgeWfAK
open import DirectedHoTT.Examples.Knot.JudgeWfAL
open import DirectedHoTT.Examples.Knot.JudgeWfAM

-- dwf-ι
aJΠΒ6 : JΠΒ6 ⊢ fst (var (vs (vs (vs (vs (vs (vs vz))))))) ∷ Nat
aJΠΒ6 = ⊢fst (⊢var (there (there (there (there (there (there here)))))))
CJΠΒ6 : ICon ⌊ JΠΒ6 ⌋
CJΠΒ6 = iκ kJΠΒ6 iι
W_JΠΒ6 : (D : IDesc) → IConWf D IJudge JΠΒ6 CJΠΒ6
W_JΠΒ6 D =
  iwf-κ kJΠΒ6 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ IxWf (toI aJΠΒ6))
           (toMu (⊢snd (⊢snd (⊢snd (⊢snd (⊢snd (⊢var (there (there (there (there (there (there here)))))))))))))
           (⊢jsub (⊢⌜IMu⌝ IxWf (toI (fromI (⊢var here))))
                  (toI (⊢num 0))
                  (toI aJΠΒ6)
                  (⊢symN aJΠΒ6 (⊢num 0)
                         (fordAs (⊢var (there (there (there (there here)))))))
                  (toMu (⊢IxDConK (⊢num 0) (⊢DCon-iKv (num 0) (⊢num 0))))))
    (iwf-ι)

aJΠΒ5 : JΠΒ5 ⊢ fst (var (vs (vs (vs (vs (vs vz)))))) ∷ Nat
aJΠΒ5 = ⊢fst (⊢var (there (there (there (there (there here))))))
CJΠΒ5 : ICon ⌊ JΠΒ5 ⌋
CJΠΒ5 = iκ kJΠΒ5 CJΠΒ6
W_JΠΒ5 : (D : IDesc) → IConWf D IJudge JΠΒ5 CJΠΒ5
W_JΠΒ5 D =
  iwf-κ kJΠΒ5 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝
           (toI (⊢fst (⊢snd (⊢snd (⊢snd (⊢snd (⊢var (there (there (there (there (there here))))))))))))
           (⊢jsub ⊢⌜Nat⌝
                  (toI (⊢num 0))
                  (toI aJΠΒ5)
                  (⊢symN aJΠΒ5 (⊢num 0)
                         (fordAs (⊢var (there (there (there here))))))
                  (toI (⊢num 2))))
    (W_JΠΒ6 D)

aJΠΒ4 : JΠΒ4 ⊢ fst (var (vs (vs (vs (vs vz))))) ∷ Nat
aJΠΒ4 = ⊢fst (⊢var (there (there (there (there here)))))
CJΠΒ4 : ICon ⌊ JΠΒ4 ⌋
CJΠΒ4 = iκ kJΠΒ4 CJΠΒ5
W_JΠΒ4 : (D : IDesc) → IConWf D IJudge JΠΒ4 CJΠΒ4
W_JΠΒ4 D =
  iwf-κ kJΠΒ4 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTy aJΠΒ4))
           (toMu (⊢fst (⊢snd (⊢snd (⊢snd (⊢var (there (there (there (there here))))))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTy (fromI (⊢var here))))
                  (toI (⊢num 0))
                  (toI aJΠΒ4)
                  (⊢symN aJΠΒ4 (⊢num 0)
                         (fordAs (⊢var (there (there here)))))
                  (toMu (⊢Ty-NatKv (num 0) (⊢num 0)))))
    (W_JΠΒ5 D)

aJΠΒ3 : JΠΒ3 ⊢ fst (var (vs (vs (vs vz)))) ∷ Nat
aJΠΒ3 = ⊢fst (⊢var (there (there (there here))))
CJΠΒ3 : ICon ⌊ JΠΒ3 ⌋
CJΠΒ3 = iκ kJΠΒ3 CJΠΒ4
W_JΠΒ3 : (D : IDesc) → IConWf D IJudge JΠΒ3 CJΠΒ3
W_JΠΒ3 D =
  iwf-κ kJΠΒ3 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aJΠΒ3))
           (toMu (⊢fst (⊢snd (⊢snd (⊢var (there (there (there here))))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (⊢num 0))
                  (toI aJΠΒ3)
                  (⊢symN aJΠΒ3 (⊢num 0)
                         (fordAs (⊢var (there here))))
                  (toMu (⊢Tm-unitKv (num 0) (⊢num 0)))))
    (W_JΠΒ4 D)

aJΠΒ2 : JΠΒ2 ⊢ fst (var (vs (vs vz))) ∷ Nat
aJΠΒ2 = ⊢fst (⊢var (there (there here)))
CJΠΒ2 : ICon ⌊ JΠΒ2 ⌋
CJΠΒ2 = iκ kJΠΒ2 CJΠΒ3
W_JΠΒ2 : (D : IDesc) → IConWf D IJudge JΠΒ2 CJΠΒ2
W_JΠΒ2 D =
  iwf-κ kJΠΒ2 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ CtxWf (toI aJΠΒ2))
           (toMu (⊢fst (⊢snd (⊢var (there (there here))))))
           (⊢jsub (⊢⌜IMu⌝ CtxWf (toI (fromI (⊢var here))))
                  (toI (⊢num 0))
                  (toI aJΠΒ2)
                  (⊢symN aJΠΒ2 (⊢num 0)
                         (fordAs (⊢var here)))
                  (toMu ⊢Ctx-empK)))
    (W_JΠΒ3 D)

CJΠΒ1 : ICon ⌊ JΠΒ1 ⌋
CJΠΒ1 = iκ kJΠΒ1 CJΠΒ2
W_JΠΒ1 : (D : IDesc) → IConWf D IJudge JΠΒ1 CJΠΒ1
W_JΠΒ1 D =
  iwf-κ kJΠΒ1 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝ (toI (⊢fst (⊢var (there here)))) (toI (⊢num 0)))
    (W_JΠΒ2 D)

CJΠΒ0 : ICon ⌊ JΠΒ0 ⌋
CJΠΒ0 = iκ kJΠΒ0 CJΠΒ1
W_JΠΒ0 : (D : IDesc) → IConWf D IJudge JΠΒ0 CJΠΒ0
W_JΠΒ0 D =
  iwf-κ kJΠΒ0 (icw-clo ⌜Nat⌝ ⊢⌜Nat⌝) ⊢⌜Nat⌝
    (W_JΠΒ1 D)

jddwf-ιWf : (D : IDesc) → IConWf D IJudge JΠΒ0 jddwf-ι
jddwf-ιWf = W_JΠΒ0

