--- GENERATED by tools/gen-knot.py — do not edit.
------------------------------------------------------------------------
-- OCP-0009 · EXAMPLES — ★★★ `_⊢ty_ / _⊢_∷_` IS A WELL-FORMED DESCRIPTION.
--
-- ⚠⚠ THIS MODULE NEEDS THE **COMPACTING COLLECTOR**.
--
--   MEASURED 2026-08-31, the commit that added `⊢app`/`⊢pair`/`⊢snd`/
--   `⊢jsub`: `JudgeWfA` OOM-KILLED (143) on the default `-A64m` and
--   passed on `-A64m -c` at 179s.  `JudgeWfB` passed either way at 74s.
--   ⚠ Four rows moved it across the cap — and the two halves hold the
--     SAME number of rows, so the count is not what separates them.
--     `_⊢ty_`/`_⊢_∷_`'s index has FIVE components and the A half's rows
--     carry the deeper telescopes.
--
--   ⚠ BEFORE THIS MARKER THE MODULE WAS GREEN ONLY BY THE SWEEP'S
--     RETRY: `tools/sweep.sh` takes the OOM kill, then re-runs with
--     `-c`.  That is a pass, but it costs an OOM every sweep and it
--     hides the cost from anyone checking the module directly.
--
--   `tools/sweep.sh` greps this header for the phrase above and
--   switches collectors on its own (`needs_c`), which is why the words
--   are spelled out rather than described.
--
-- ⚠⚠ THE RULES ARE **PARSED OUT OF `Spec/Typing.agda`**, not transcribed.
--   A hand-written table is one chance per row to name the wrong
--   variable — the error class `Knot/LookupGen` exists to catch, and one
--   an `ICon` never reveals, because it type-checks with ANY in-scope
--   variable of the right type.  The Agda-former → knot-constructor map
--   comes from `KNOT`'s own `decl` strings, so nothing is typed twice.
--
-- ★ ANY RULE THAT DID NOT TRANSLATE IS NAMED BELOW.  Emitting a subset
--   silently is `verification-that-covers-less-than-it-claims`.
------------------------------------------------------------------------

{-# OPTIONS --safe #-}
module DirectedHoTT.Examples.Knot.JudgeWfF where
open import normalizer.Syntax.Types using ( _≡_; refl )
open import Agda.Builtin.Nat using ( zero; suc ) renaming ( Nat to ℕ )
open import DirectedHoTT.Spec.Syntax
  using ( Cx; ε; _∙; RTy; RTm; var; vz; vs; pair; fst; snd; nsuc; nzero
        ; El; IMu; Σ'; Nat
        ; ⌜Nat⌝; ⌜Id⌝; ⌜IMu⌝; jsub; ICon; IDesc; iι; iρ; iκ; inil; _◂_; εwkTy )
open import DirectedHoTT.Spec.Typing
  using ( Ctx; ◇; _▹_; ⌊_⌋; _⊢_∷_; _⊢ty_
        ; IConWf; iwf-ι; iwf-κ; iwf-ρ; ICodeWf; icw-clo; icw-ford; icw-imu
        ; IDescWf; idwf-nil; idwf-cons
        ; ⊢var; here; there; ⊢fst; ⊢snd; ⊢nsuc; ⊢nzero
        ; ⊢⌜Nat⌝; ⊢⌜Id⌝; ⊢⌜IMu⌝; ⊢jsub
        ; ⊢pair; ty-Σ; ty-Nat; ty-IMu
        ; ξ-pairˡ; ξ-pairʳ; ξ-nsuc; βfst; βsnd )
open import DirectedHoTT.Examples.Knot.Sorts
  using ( IPair; sTy; sTm; sDesc; sDCon; sIDesc; sICon; sVar
        ; toI; fromI; ⊢ixP; ⊢sTy; ⊢sTm; ⊢sDesc; ⊢sDCon; ⊢sIDesc; ⊢sICon; ⊢sVar
        ; num; ⊢num )
open import DirectedHoTT.Examples.Knot.Desc using ( KnotD )
open import DirectedHoTT.Examples.Knot.Wf using ( KnotWf )
open import DirectedHoTT.Examples.Knot.Ctors
open import DirectedHoTT.Examples.Knot.CtorsV
open import DirectedHoTT.Examples.Knot.Build using ( Var-vzK; Var-vsK; ⊢Var-vzKt; ⊢Var-vsKt )
open import DirectedHoTT.Examples.Knot.Wk using ( wkK; ⊢wkK )
open import DirectedHoTT.Examples.Knot.WkSub using ( wkTmK; ⊢wkTmK; wkTyK; ⊢wkTyK )
open import DirectedHoTT.Lib.ICast using ( toMu; fromMu; fordAs; muFwd )
open import DirectedHoTT.Lib.ArithComm using ( symN; ⊢symN )
open import DirectedHoTT.Metatheory.SubjectReduction using ( ⊢wk )
open import DirectedHoTT.Examples.Knot.Single using ( singleK; ⊢singleK )
open import DirectedHoTT.Examples.Knot.SubApp
  using ( subTmAtK; subTyAtK; ⊢subTmAtK; ⊢subTyAtK )
open import DirectedHoTT.Examples.Knot.SubMot using ( extNK; ⊢extNK )
open import DirectedHoTT.Examples.Knot.Pw using ( pwK; ⊢pwK )
open import DirectedHoTT.Examples.Knot.Stk
  using ( stkAK; ⊢stkAK; stkCK; ⊢stkCK; flatK; ⊢flatK )
open import DirectedHoTT.Examples.Knot.Nrs using ( nrsSubK; ⊢nrsSubK )
open import DirectedHoTT.Examples.Knot.PwBody using ( pwBodyK; ⊢pwBodyK )
open import DirectedHoTT.Examples.Knot.CtxD
  using ( CtxD; INat; CtxWf; Ctx-extK; ⊢Ctx-extKt; Ctx-empK; ⊢Ctx-empK )
open import DirectedHoTT.Examples.Knot.EWk using ( εwkK; ⊢εwkK; isingleK; ⊢isingleK )
open import DirectedHoTT.Examples.Knot.SubMot
  using ( sortMap-ty; sortMap-tm; sortMap-desc; sortMap-dcon
        ; sortMap-idesc; sortMap-icon; sortMap-var )
open import DirectedHoTT.Examples.Knot.Lookup using ( LkD; ILk; LkWf )
open import DirectedHoTT.Examples.Knot.ConvRows using ( ConvD; IConv )
open import DirectedHoTT.Examples.Knot.ConvWf using ( ConvWf )
open import DirectedHoTT.Examples.Knot.NoNatCRows using ( NoNatCD; INoNatC )
open import DirectedHoTT.Examples.Knot.NoNatCWf using ( NoNatCWf )
open import DirectedHoTT.Examples.Knot.InDRows using ( InDD; IInD )
open import DirectedHoTT.Examples.Knot.InDWf using ( InDWf )
open import DirectedHoTT.Examples.Knot.InIDRows using ( InIDD; IInID )
open import DirectedHoTT.Examples.Knot.InIDWf using ( InIDWf )
open import DirectedHoTT.Examples.Knot.IxD
  using ( IxD; IxWf; IxNoneK; ⊢IxNoneK; IxDConK; ⊢IxDConK; IxDescK; ⊢IxDescK
        ; IxIConK; ⊢IxIConK; IxIDescK; ⊢IxIDescK )
open import DirectedHoTT.Examples.Knot.JudgeRows
open import DirectedHoTT.Examples.Knot.JudgeWfA
open import DirectedHoTT.Examples.Knot.JudgeWfB
open import DirectedHoTT.Examples.Knot.JudgeWfC
open import DirectedHoTT.Examples.Knot.JudgeWfD
open import DirectedHoTT.Examples.Knot.JudgeWfE

-- ty-Id
-- ★ the telescope, back at `Ctx` level: `emit_jrow` had to
--   drop to a bare `Cx` at the premise to stay writable
--   before `JudgeD` existed.
JΖ6 JΖ7 JΖ8 JΖ9 JΖ10 JΖ11 JΖ12 JΖ13 JΖ14 : Ctx
JΖ6 = JΖ5 ▹ IMu JudgeD IJudge kJΖ5
JΖ7 = JΖ6 ▹ IMu JudgeD IJudge kJΖ6
JΖ8 = JΖ7 ▹ IMu JudgeD IJudge kJΖ7
JΖ9 = JΖ8 ▹ El kJΖ8
JΖ10 = JΖ9 ▹ El kJΖ9
JΖ11 = JΖ10 ▹ El kJΖ10
JΖ12 = JΖ11 ▹ El kJΖ11
JΖ13 = JΖ12 ▹ El kJΖ12
JΖ14 = JΖ13 ▹ El kJΖ13

aJΖ13 : JΖ13 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))))) ∷ Nat
aJΖ13 = ⊢fst (⊢var (there (there (there (there (there (there (there (there (there (there (there (there (there here))))))))))))))
CJΖ13 : ICon ⌊ JΖ13 ⌋
CJΖ13 = iκ kJΖ13 iι
W_JΖ13 : IConWf JudgeD IJudge JΖ13 CJΖ13
W_JΖ13 =
  iwf-κ kJΖ13 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ IxWf (toI aJΖ13))
           (toMu (⊢snd (⊢snd (⊢snd (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there (there (there (there (there (there (there here))))))))))))))))))))
           (⊢jsub (⊢⌜IMu⌝ IxWf (toI (fromI (⊢var here))))
                  (toI (fromI (⊢var (there (there (there (there (there (there (there (there (there (there (there (there here)))))))))))))))
                  (toI aJΖ13)
                  (⊢symN aJΖ13 (fromI (⊢var (there (there (there (there (there (there (there (there (there (there (there (there here))))))))))))))
                         (fordAs (⊢var (there (there (there (there here)))))))
                  (toMu (⊢IxNoneK (fromI (⊢var (there (there (there (there (there (there (there (there (there (there (there (there here))))))))))))))))))
    iwf-ι

aJΖ12 : JΖ12 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))))) ∷ Nat
aJΖ12 = ⊢fst (⊢var (there (there (there (there (there (there (there (there (there (there (there (there here)))))))))))))
CJΖ12 : ICon ⌊ JΖ12 ⌋
CJΖ12 = iκ kJΖ12 CJΖ13
W_JΖ12 : IConWf JudgeD IJudge JΖ12 CJΖ12
W_JΖ12 =
  iwf-κ kJΖ12 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝
           (toI (⊢fst (⊢snd (⊢snd (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there (there (there (there (there (there here)))))))))))))))))))
           (⊢jsub ⊢⌜Nat⌝
                  (toI (fromI (⊢var (there (there (there (there (there (there (there (there (there (there (there here))))))))))))))
                  (toI aJΖ12)
                  (⊢symN aJΖ12 (fromI (⊢var (there (there (there (there (there (there (there (there (there (there (there here)))))))))))))
                         (fordAs (⊢var (there (there (there here))))))
                  (toI (⊢num 0))))
    W_JΖ13

aJΖ11 : JΖ11 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))) ∷ Nat
aJΖ11 = ⊢fst (⊢var (there (there (there (there (there (there (there (there (there (there (there here))))))))))))
CJΖ11 : ICon ⌊ JΖ11 ⌋
CJΖ11 = iκ kJΖ11 CJΖ12
W_JΖ11 : IConWf JudgeD IJudge JΖ11 CJΖ11
W_JΖ11 =
  iwf-κ kJΖ11 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTy aJΖ11))
           (toMu (⊢fst (⊢snd (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there (there (there (there (there here)))))))))))))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTy (fromI (⊢var here))))
                  (toI (fromI (⊢var (there (there (there (there (there (there (there (there (there (there here)))))))))))))
                  (toI aJΖ11)
                  (⊢symN aJΖ11 (fromI (⊢var (there (there (there (there (there (there (there (there (there (there here))))))))))))
                         (fordAs (⊢var (there (there here)))))
                  (toMu (⊢Ty-IdKv (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))) (fromI (⊢var (there (there (there (there (there (there (there (there (there (there here)))))))))))) (fromMu (⊢var (there (there (there (there (there (there (there (there here)))))))))) (fromMu (⊢var (there (there (there (there (there (there (there here))))))))) (fromMu (⊢var (there (there (there (there (there (there here))))))))))))
    W_JΖ12

aJΖ10 : JΖ10 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))) ∷ Nat
aJΖ10 = ⊢fst (⊢var (there (there (there (there (there (there (there (there (there (there here)))))))))))
CJΖ10 : ICon ⌊ JΖ10 ⌋
CJΖ10 = iκ kJΖ10 CJΖ11
W_JΖ10 : IConWf JudgeD IJudge JΖ10 CJΖ10
W_JΖ10 =
  iwf-κ kJΖ10 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aJΖ10))
           (toMu (⊢fst (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there (there (there (there here)))))))))))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (there (there (there (there (there (there (there (there (there here))))))))))))
                  (toI aJΖ10)
                  (⊢symN aJΖ10 (fromI (⊢var (there (there (there (there (there (there (there (there (there here)))))))))))
                         (fordAs (⊢var (there here))))
                  (toMu (⊢Tm-unitKv (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))) (fromI (⊢var (there (there (there (there (there (there (there (there (there here)))))))))))))))
    W_JΖ11

aJΖ9 : JΖ9 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))) ∷ Nat
aJΖ9 = ⊢fst (⊢var (there (there (there (there (there (there (there (there (there here))))))))))
CJΖ9 : ICon ⌊ JΖ9 ⌋
CJΖ9 = iκ kJΖ9 CJΖ10
W_JΖ9 : IConWf JudgeD IJudge JΖ9 CJΖ9
W_JΖ9 =
  iwf-κ kJΖ9 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ CtxWf (toI aJΖ9))
           (toMu (⊢fst (⊢snd (⊢var (there (there (there (there (there (there (there (there (there here)))))))))))))
           (⊢jsub (⊢⌜IMu⌝ CtxWf (toI (fromI (⊢var here))))
                  (toI (fromI (⊢var (there (there (there (there (there (there (there (there here)))))))))))
                  (toI aJΖ9)
                  (⊢symN aJΖ9 (fromI (⊢var (there (there (there (there (there (there (there (there here))))))))))
                         (fordAs (⊢var here)))
                  (toMu (fromMu (⊢var (there (there (there (there (there (there (there here))))))))))))
    W_JΖ10

CJΖ8 : ICon ⌊ JΖ8 ⌋
CJΖ8 = iκ kJΖ8 CJΖ9
W_JΖ8 : IConWf JudgeD IJudge JΖ8 CJΖ8
W_JΖ8 =
  iwf-κ kJΖ8 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝ (toI (⊢fst (⊢var (there (there (there (there (there (there (there (there here))))))))))) (toI (fromI (⊢var (there (there (there (there (there (there (there here)))))))))))
    W_JΖ9

CJΖ7 : ICon ⌊ JΖ7 ⌋
CJΖ7 = iρ kJΖ7 CJΖ8
W_JΖ7 : IConWf JudgeD IJudge JΖ7 CJΖ7
W_JΖ7 =
  iwf-ρ kJΖ7
    (⊢pair (ty-Σ (ty-IMu CtxWf (toI (⊢var here))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢var (there here)))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢var (there (there here))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢var (there (there (there (there here))))))))))) (fromI (⊢var (there (there (there (there (there (there here))))))))
      (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢wk (fromI (⊢var (there (there (there (there (there (there here))))))))))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (⊢wk (fromI (⊢var (there (there (there (there (there (there here)))))))))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢wk (⊢wk (fromI (⊢var (there (there (there (there (there (there here))))))))))))))))) (fromMu (⊢var (there (there (there (there (there here)))))))
      (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (fromI (⊢var (there (there (there (there (there (there here))))))))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢wk (fromI (⊢var (there (there (there (there (there (there here))))))))))))))) (fromMu (⊢var (there (there here))))
      (⊢pair (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (fromI (⊢var (there (there (there (there (there (there here))))))))))))) (fromMu (⊢var (there (there (there (there here))))))
      (⊢pair (ty-IMu IxWf (toI (⊢wk (fromI (⊢var (there (there (there (there (there (there here))))))))))) (⊢num 1) (⊢IxNoneK (fromI (⊢var (there (there (there (there (there (there here))))))))))))))
    W_JΖ8

CJΖ6 : ICon ⌊ JΖ6 ⌋
CJΖ6 = iρ kJΖ6 CJΖ7
W_JΖ6 : IConWf JudgeD IJudge JΖ6 CJΖ6
W_JΖ6 =
  iwf-ρ kJΖ6
    (⊢pair (ty-Σ (ty-IMu CtxWf (toI (⊢var here))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢var (there here)))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢var (there (there here))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢var (there (there (there (there here))))))))))) (fromI (⊢var (there (there (there (there (there here)))))))
      (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢wk (fromI (⊢var (there (there (there (there (there here)))))))))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (⊢wk (fromI (⊢var (there (there (there (there (there here))))))))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢wk (⊢wk (fromI (⊢var (there (there (there (there (there here)))))))))))))))) (fromMu (⊢var (there (there (there (there here))))))
      (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (fromI (⊢var (there (there (there (there (there here)))))))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢wk (fromI (⊢var (there (there (there (there (there here)))))))))))))) (fromMu (⊢var (there (there here))))
      (⊢pair (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (fromI (⊢var (there (there (there (there (there here)))))))))))) (fromMu (⊢var (there (there (there here)))))
      (⊢pair (ty-IMu IxWf (toI (⊢wk (fromI (⊢var (there (there (there (there (there here)))))))))) (⊢num 1) (⊢IxNoneK (fromI (⊢var (there (there (there (there (there here)))))))))))))
    W_JΖ7

CJΖ5 : ICon ⌊ JΖ5 ⌋
CJΖ5 = iρ kJΖ5 CJΖ6
W_JΖ5 : IConWf JudgeD IJudge JΖ5 CJΖ5
W_JΖ5 =
  iwf-ρ kJΖ5
    (⊢pair (ty-Σ (ty-IMu CtxWf (toI (⊢var here))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢var (there here)))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢var (there (there here))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢var (there (there (there (there here))))))))))) (fromI (⊢var (there (there (there (there here))))))
      (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢wk (fromI (⊢var (there (there (there (there here))))))))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (⊢wk (fromI (⊢var (there (there (there (there here)))))))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢wk (⊢wk (fromI (⊢var (there (there (there (there here))))))))))))))) (fromMu (⊢var (there (there (there here)))))
      (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (fromI (⊢var (there (there (there (there here))))))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢wk (fromI (⊢var (there (there (there (there here))))))))))))) (⊢Tm-unitKv (var (vs (vs (vs (vs vz))))) (fromI (⊢var (there (there (there (there here)))))))
      (⊢pair (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (fromI (⊢var (there (there (there (there here))))))))))) (fromMu (⊢var (there (there here))))
      (⊢pair (ty-IMu IxWf (toI (⊢wk (fromI (⊢var (there (there (there (there here))))))))) (⊢num 0) (⊢IxNoneK (fromI (⊢var (there (there (there (there here))))))))))))
    W_JΖ6

CJΖ4 : ICon ⌊ JΖ4 ⌋
CJΖ4 = iκ kJΖ4 CJΖ5
W_JΖ4 : IConWf JudgeD IJudge JΖ4 CJΖ4
W_JΖ4 =
  iwf-κ kJΖ4 (icw-imu (pair sTm (var (vs (vs (vs vz))))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (there (there (there here)))))))
    W_JΖ5

CJΖ3 : ICon ⌊ JΖ3 ⌋
CJΖ3 = iκ kJΖ3 CJΖ4
W_JΖ3 : IConWf JudgeD IJudge JΖ3 CJΖ3
W_JΖ3 =
  iwf-κ kJΖ3 (icw-imu (pair sTm (var (vs (vs vz)))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (there (there here))))))
    W_JΖ4

CJΖ2 : ICon ⌊ JΖ2 ⌋
CJΖ2 = iκ kJΖ2 CJΖ3
W_JΖ2 : IConWf JudgeD IJudge JΖ2 CJΖ2
W_JΖ2 =
  iwf-κ kJΖ2 (icw-imu (pair sTy (var (vs vz))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTy (fromI (⊢var (there here)))))
    W_JΖ3

CJΖ1 : ICon ⌊ JΖ1 ⌋
CJΖ1 = iκ kJΖ1 CJΖ2
W_JΖ1 : IConWf JudgeD IJudge JΖ1 CJΖ1
W_JΖ1 =
  iwf-κ kJΖ1 (icw-imu (var vz) CtxWf)
    (⊢⌜IMu⌝ CtxWf (toI (fromI (⊢var here))))
    W_JΖ2

CJΖ0 : ICon ⌊ JΖ0 ⌋
CJΖ0 = iκ kJΖ0 CJΖ1
W_JΖ0 : IConWf JudgeD IJudge JΖ0 CJΖ0
W_JΖ0 =
  iwf-κ kJΖ0 (icw-clo ⌜Nat⌝ ⊢⌜Nat⌝) ⊢⌜Nat⌝
    W_JΖ1

jdty-IdWf : IConWf JudgeD IJudge JΖ0 jdty-Id
jdty-IdWf = W_JΖ0

