--- GENERATED by tools/gen-knot.py — do not edit.
------------------------------------------------------------------------
-- OCP-0009 · EXAMPLES — ★★★ `_⊢ty_ / _⊢_∷_` IS A WELL-FORMED DESCRIPTION.
--
-- ⚠⚠ THIS MODULE NEEDS THE **COMPACTING COLLECTOR**.
--
--   MEASURED 2026-08-31, the commit that added `⊢app`/`⊢pair`/`⊢snd`/
--   `⊢jsub`: `JudgeWfA` OOM-KILLED (143) on the default `-A64m` and
--   passed on `-A64m -c` at 179s.  `JudgeWfB` passed either way at 74s.
--   ⚠ Four rows moved it across the cap — and the two halves hold the
--     SAME number of rows, so the count is not what separates them.
--     `_⊢ty_`/`_⊢_∷_`'s index has FIVE components and the A half's rows
--     carry the deeper telescopes.
--
--   ⚠ BEFORE THIS MARKER THE MODULE WAS GREEN ONLY BY THE SWEEP'S
--     RETRY: `tools/sweep.sh` takes the OOM kill, then re-runs with
--     `-c`.  That is a pass, but it costs an OOM every sweep and it
--     hides the cost from anyone checking the module directly.
--
--   `tools/sweep.sh` greps this header for the phrase above and
--   switches collectors on its own (`needs_c`), which is why the words
--   are spelled out rather than described.
--
-- ⚠⚠ THE RULES ARE **PARSED OUT OF `Spec/Typing.agda`**, not transcribed.
--   A hand-written table is one chance per row to name the wrong
--   variable — the error class `Knot/LookupGen` exists to catch, and one
--   an `ICon` never reveals, because it type-checks with ANY in-scope
--   variable of the right type.  The Agda-former → knot-constructor map
--   comes from `KNOT`'s own `decl` strings, so nothing is typed twice.
--
-- ★ ANY RULE THAT DID NOT TRANSLATE IS NAMED BELOW.  Emitting a subset
--   silently is `verification-that-covers-less-than-it-claims`.
------------------------------------------------------------------------

{-# OPTIONS --safe #-}
module DirectedHoTT.Examples.Knot.JudgeWfL where
open import normalizer.Syntax.Types using ( _≡_; refl )
open import Agda.Builtin.Nat using ( zero; suc ) renaming ( Nat to ℕ )
open import DirectedHoTT.Spec.Syntax
  using ( Cx; ε; _∙; RTy; RTm; var; vz; vs; pair; fst; snd; nsuc; nzero
        ; El; IMu; Σ'; Nat
        ; ⌜Nat⌝; ⌜Id⌝; ⌜IMu⌝; jsub; ICon; IDesc; iι; iρ; iκ; inil; _◂_; εwkTy )
open import DirectedHoTT.Spec.Typing
  using ( Ctx; ◇; _▹_; ⌊_⌋; _⊢_∷_; _⊢ty_
        ; IConWf; iwf-ι; iwf-κ; iwf-ρ; ICodeWf; icw-clo; icw-ford; icw-imu
        ; IDescWf; idwf-nil; idwf-cons
        ; ⊢var; here; there; ⊢fst; ⊢snd; ⊢nsuc; ⊢nzero
        ; ⊢⌜Nat⌝; ⊢⌜Id⌝; ⊢⌜IMu⌝; ⊢jsub
        ; ⊢pair; ty-Σ; ty-Nat; ty-IMu
        ; ξ-pairˡ; ξ-pairʳ; ξ-nsuc; βfst; βsnd )
open import DirectedHoTT.Examples.Knot.Sorts
  using ( IPair; sTy; sTm; sDesc; sDCon; sIDesc; sICon; sVar
        ; toI; fromI; ⊢ixP; ⊢sTy; ⊢sTm; ⊢sDesc; ⊢sDCon; ⊢sIDesc; ⊢sICon; ⊢sVar
        ; num; ⊢num )
open import DirectedHoTT.Examples.Knot.Desc using ( KnotD )
open import DirectedHoTT.Examples.Knot.Wf using ( KnotWf )
open import DirectedHoTT.Examples.Knot.Ctors
open import DirectedHoTT.Examples.Knot.CtorsV
open import DirectedHoTT.Examples.Knot.Build using ( Var-vzK; Var-vsK; ⊢Var-vzKt; ⊢Var-vsKt )
open import DirectedHoTT.Examples.Knot.Wk using ( wkK; ⊢wkK )
open import DirectedHoTT.Lib.ICast using ( toMu; fromMu; fordAs; muFwd )
open import DirectedHoTT.Lib.ArithComm using ( symN; ⊢symN )
open import DirectedHoTT.Metatheory.SubjectReduction using ( ⊢wk )
open import DirectedHoTT.Examples.Knot.Single using ( singleK; ⊢singleK )
open import DirectedHoTT.Examples.Knot.SubApp
  using ( subTmAtK; subTyAtK; ⊢subTmAtK; ⊢subTyAtK )
open import DirectedHoTT.Examples.Knot.SubMot using ( extNK; ⊢extNK )
open import DirectedHoTT.Examples.Knot.Pw using ( pwK; ⊢pwK )
open import DirectedHoTT.Examples.Knot.Stk
  using ( stkAK; ⊢stkAK; stkCK; ⊢stkCK; flatK; ⊢flatK )
open import DirectedHoTT.Examples.Knot.Nrs using ( nrsSubK; ⊢nrsSubK )
open import DirectedHoTT.Examples.Knot.PwBody using ( pwBodyK; ⊢pwBodyK )
open import DirectedHoTT.Examples.Knot.CtxD
  using ( CtxD; INat; CtxWf; Ctx-extK; ⊢Ctx-extKt; Ctx-empK; ⊢Ctx-empK )
open import DirectedHoTT.Examples.Knot.EWk using ( εwkK; ⊢εwkK )
open import DirectedHoTT.Examples.Knot.SubMot
  using ( sortMap-ty; sortMap-tm; sortMap-desc; sortMap-dcon
        ; sortMap-idesc; sortMap-icon; sortMap-var )
open import DirectedHoTT.Examples.Knot.Lookup using ( LkD; ILk; LkWf )
open import DirectedHoTT.Examples.Knot.ConvRows using ( ConvD; IConv )
open import DirectedHoTT.Examples.Knot.ConvWf using ( ConvWf )
open import DirectedHoTT.Examples.Knot.NoNatCRows using ( NoNatCD; INoNatC )
open import DirectedHoTT.Examples.Knot.NoNatCWf using ( NoNatCWf )
open import DirectedHoTT.Examples.Knot.InDRows using ( InDD; IInD )
open import DirectedHoTT.Examples.Knot.InDWf using ( InDWf )
open import DirectedHoTT.Examples.Knot.InIDRows using ( InIDD; IInID )
open import DirectedHoTT.Examples.Knot.InIDWf using ( InIDWf )
open import DirectedHoTT.Examples.Knot.IxD
  using ( IxD; IxWf; IxNoneK; ⊢IxNoneK; IxDConK; ⊢IxDConK; IxDescK; ⊢IxDescK
        ; IxIConK; ⊢IxIConK; IxIDescK; ⊢IxIDescK )
open import DirectedHoTT.Examples.Knot.JudgeRows
open import DirectedHoTT.Examples.Knot.JudgeWfA
open import DirectedHoTT.Examples.Knot.JudgeWfB
open import DirectedHoTT.Examples.Knot.JudgeWfC
open import DirectedHoTT.Examples.Knot.JudgeWfD
open import DirectedHoTT.Examples.Knot.JudgeWfE
open import DirectedHoTT.Examples.Knot.JudgeWfF
open import DirectedHoTT.Examples.Knot.JudgeWfG
open import DirectedHoTT.Examples.Knot.JudgeWfH
open import DirectedHoTT.Examples.Knot.JudgeWfI
open import DirectedHoTT.Examples.Knot.JudgeWfJ
open import DirectedHoTT.Examples.Knot.JudgeWfK

-- ⊢var
aJΜ10 : JΜ10 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))) ∷ Nat
aJΜ10 = ⊢fst (⊢var (there (there (there (there (there (there (there (there (there (there here)))))))))))
CJΜ10 : ICon ⌊ JΜ10 ⌋
CJΜ10 = iκ kJΜ10 iι
W_JΜ10 : (D : IDesc) → IConWf D IJudge JΜ10 CJΜ10
W_JΜ10 D =
  iwf-κ kJΜ10 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ IxWf (toI aJΜ10))
           (toMu (⊢snd (⊢snd (⊢snd (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there (there (there (there here)))))))))))))))))
           (⊢jsub (⊢⌜IMu⌝ IxWf (toI (fromI (⊢var here))))
                  (toI (fromI (⊢var (there (there (there (there (there (there (there (there (there here))))))))))))
                  (toI aJΜ10)
                  (⊢symN aJΜ10 (fromI (⊢var (there (there (there (there (there (there (there (there (there here)))))))))))
                         (fordAs (⊢var (there (there (there (there here)))))))
                  (toMu (⊢IxNoneK (fromI (⊢var (there (there (there (there (there (there (there (there (there here)))))))))))))))
    (iwf-ι)

aJΜ9 : JΜ9 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))) ∷ Nat
aJΜ9 = ⊢fst (⊢var (there (there (there (there (there (there (there (there (there here))))))))))
CJΜ9 : ICon ⌊ JΜ9 ⌋
CJΜ9 = iκ kJΜ9 CJΜ10
W_JΜ9 : (D : IDesc) → IConWf D IJudge JΜ9 CJΜ9
W_JΜ9 D =
  iwf-κ kJΜ9 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝
           (toI (⊢fst (⊢snd (⊢snd (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there (there (there here))))))))))))))))
           (⊢jsub ⊢⌜Nat⌝
                  (toI (fromI (⊢var (there (there (there (there (there (there (there (there here)))))))))))
                  (toI aJΜ9)
                  (⊢symN aJΜ9 (fromI (⊢var (there (there (there (there (there (there (there (there here))))))))))
                         (fordAs (⊢var (there (there (there here))))))
                  (toI (⊢num 1))))
    (W_JΜ10 D)

aJΜ8 : JΜ8 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))) ∷ Nat
aJΜ8 = ⊢fst (⊢var (there (there (there (there (there (there (there (there here)))))))))
CJΜ8 : ICon ⌊ JΜ8 ⌋
CJΜ8 = iκ kJΜ8 CJΜ9
W_JΜ8 : (D : IDesc) → IConWf D IJudge JΜ8 CJΜ8
W_JΜ8 D =
  iwf-κ kJΜ8 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTy aJΜ8))
           (toMu (⊢fst (⊢snd (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there (there here))))))))))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTy (fromI (⊢var here))))
                  (toI (fromI (⊢var (there (there (there (there (there (there (there here))))))))))
                  (toI aJΜ8)
                  (⊢symN aJΜ8 (fromI (⊢var (there (there (there (there (there (there (there here)))))))))
                         (fordAs (⊢var (there (there here)))))
                  (toMu (fromMu (⊢var (there (there (there (there here)))))))))
    (W_JΜ9 D)

aJΜ7 : JΜ7 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs vz)))))))) ∷ Nat
aJΜ7 = ⊢fst (⊢var (there (there (there (there (there (there (there here))))))))
CJΜ7 : ICon ⌊ JΜ7 ⌋
CJΜ7 = iκ kJΜ7 CJΜ8
W_JΜ7 : (D : IDesc) → IConWf D IJudge JΜ7 CJΜ7
W_JΜ7 D =
  iwf-κ kJΜ7 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aJΜ7))
           (toMu (⊢fst (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there here))))))))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (there (there (there (there (there (there here)))))))))
                  (toI aJΜ7)
                  (⊢symN aJΜ7 (fromI (⊢var (there (there (there (there (there (there here))))))))
                         (fordAs (⊢var (there here))))
                  (toMu (⊢Tm-varKv (var (vs (vs (vs (vs (vs (vs vz))))))) (fromI (⊢var (there (there (there (there (there (there here)))))))) (fromMu (⊢var (there (there (there (there here))))))))))
    (W_JΜ8 D)

aJΜ6 : JΜ6 ⊢ fst (var (vs (vs (vs (vs (vs (vs vz))))))) ∷ Nat
aJΜ6 = ⊢fst (⊢var (there (there (there (there (there (there here)))))))
CJΜ6 : ICon ⌊ JΜ6 ⌋
CJΜ6 = iκ kJΜ6 CJΜ7
W_JΜ6 : (D : IDesc) → IConWf D IJudge JΜ6 CJΜ6
W_JΜ6 D =
  iwf-κ kJΜ6 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ CtxWf (toI aJΜ6))
           (toMu (⊢fst (⊢snd (⊢var (there (there (there (there (there (there here))))))))))
           (⊢jsub (⊢⌜IMu⌝ CtxWf (toI (fromI (⊢var here))))
                  (toI (fromI (⊢var (there (there (there (there (there here))))))))
                  (toI aJΜ6)
                  (⊢symN aJΜ6 (fromI (⊢var (there (there (there (there (there here)))))))
                         (fordAs (⊢var here)))
                  (toMu (fromMu (⊢var (there (there (there (there here)))))))))
    (W_JΜ7 D)

CJΜ5 : ICon ⌊ JΜ5 ⌋
CJΜ5 = iκ kJΜ5 CJΜ6
W_JΜ5 : (D : IDesc) → IConWf D IJudge JΜ5 CJΜ5
W_JΜ5 D =
  iwf-κ kJΜ5 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝ (toI (⊢fst (⊢var (there (there (there (there (there here)))))))) (toI (fromI (⊢var (there (there (there (there here))))))))
    (W_JΜ6 D)

CJΜ4 : ICon ⌊ JΜ4 ⌋
CJΜ4 = iκ kJΜ4 CJΜ5
W_JΜ4 : (D : IDesc) → IConWf D IJudge JΜ4 CJΜ4
W_JΜ4 D =
  iwf-κ kJΜ4 (icw-imu (pair (var (vs (vs (vs vz)))) (pair (var (vs (vs vz))) (pair (var (vs vz)) (var vz)))) LkWf)
    (⊢⌜IMu⌝ LkWf (⊢pair (ty-Σ (ty-IMu CtxWf (toI (⊢var here))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sVar (⊢var (there here)))) (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢var (there (there here))))))) (fromI (⊢var (there (there (there here)))))
      (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sVar (⊢wk (fromI (⊢var (there (there (there here)))))))) (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (⊢wk (fromI (⊢var (there (there (there here)))))))))) (fromMu (⊢var (there (there here))))
      (⊢pair (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (fromI (⊢var (there (there (there here)))))))) (fromMu (⊢var (there here))) (fromMu (⊢var here))))))
    (W_JΜ5 D)

CJΜ3 : ICon ⌊ JΜ3 ⌋
CJΜ3 = iκ kJΜ3 CJΜ4
W_JΜ3 : (D : IDesc) → IConWf D IJudge JΜ3 CJΜ3
W_JΜ3 D =
  iwf-κ kJΜ3 (icw-imu (pair sTy (var (vs (vs vz)))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTy (fromI (⊢var (there (there here))))))
    (W_JΜ4 D)

CJΜ2 : ICon ⌊ JΜ2 ⌋
CJΜ2 = iκ kJΜ2 CJΜ3
W_JΜ2 : (D : IDesc) → IConWf D IJudge JΜ2 CJΜ2
W_JΜ2 D =
  iwf-κ kJΜ2 (icw-imu (pair sVar (var (vs vz))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sVar (fromI (⊢var (there here)))))
    (W_JΜ3 D)

CJΜ1 : ICon ⌊ JΜ1 ⌋
CJΜ1 = iκ kJΜ1 CJΜ2
W_JΜ1 : (D : IDesc) → IConWf D IJudge JΜ1 CJΜ1
W_JΜ1 D =
  iwf-κ kJΜ1 (icw-imu (var vz) CtxWf)
    (⊢⌜IMu⌝ CtxWf (toI (fromI (⊢var here))))
    (W_JΜ2 D)

CJΜ0 : ICon ⌊ JΜ0 ⌋
CJΜ0 = iκ kJΜ0 CJΜ1
W_JΜ0 : (D : IDesc) → IConWf D IJudge JΜ0 CJΜ0
W_JΜ0 D =
  iwf-κ kJΜ0 (icw-clo ⌜Nat⌝ ⊢⌜Nat⌝) ⊢⌜Nat⌝
    (W_JΜ1 D)

jd⊢varWf : (D : IDesc) → IConWf D IJudge JΜ0 jd⊢var
jd⊢varWf = W_JΜ0

