--- GENERATED by tools/gen-knot.py — do not edit.
------------------------------------------------------------------------
-- OCP-0009 · EXAMPLES — ★★★ `_⊢ty_ / _⊢_∷_` IS A WELL-FORMED DESCRIPTION.
--
-- ⚠⚠ THIS MODULE NEEDS THE **COMPACTING COLLECTOR**.
--
--   MEASURED 2026-08-31, the commit that added `⊢app`/`⊢pair`/`⊢snd`/
--   `⊢jsub`: `JudgeWfA` OOM-KILLED (143) on the default `-A64m` and
--   passed on `-A64m -c` at 179s.  `JudgeWfB` passed either way at 74s.
--   ⚠ Four rows moved it across the cap — and the two halves hold the
--     SAME number of rows, so the count is not what separates them.
--     `_⊢ty_`/`_⊢_∷_`'s index has FIVE components and the A half's rows
--     carry the deeper telescopes.
--
--   ⚠ BEFORE THIS MARKER THE MODULE WAS GREEN ONLY BY THE SWEEP'S
--     RETRY: `tools/sweep.sh` takes the OOM kill, then re-runs with
--     `-c`.  That is a pass, but it costs an OOM every sweep and it
--     hides the cost from anyone checking the module directly.
--
--   `tools/sweep.sh` greps this header for the phrase above and
--   switches collectors on its own (`needs_c`), which is why the words
--   are spelled out rather than described.
--
-- ⚠⚠ THE RULES ARE **PARSED OUT OF `Spec/Typing.agda`**, not transcribed.
--   A hand-written table is one chance per row to name the wrong
--   variable — the error class `Knot/LookupGen` exists to catch, and one
--   an `ICon` never reveals, because it type-checks with ANY in-scope
--   variable of the right type.  The Agda-former → knot-constructor map
--   comes from `KNOT`'s own `decl` strings, so nothing is typed twice.
--
-- ★ ANY RULE THAT DID NOT TRANSLATE IS NAMED BELOW.  Emitting a subset
--   silently is `verification-that-covers-less-than-it-claims`.
------------------------------------------------------------------------

{-# OPTIONS --safe #-}
module DirectedHoTT.Examples.Knot.JudgeWfI where
open import normalizer.Syntax.Types using ( _≡_; refl )
open import Agda.Builtin.Nat using ( zero; suc ) renaming ( Nat to ℕ )
open import DirectedHoTT.Spec.Syntax
  using ( Cx; ε; _∙; RTy; RTm; var; vz; vs; pair; fst; snd; nsuc; nzero
        ; El; IMu; Σ'; Nat
        ; ⌜Nat⌝; ⌜Id⌝; ⌜IMu⌝; jsub; ICon; IDesc; iι; iρ; iκ; inil; _◂_; εwkTy )
open import DirectedHoTT.Spec.Typing
  using ( Ctx; ◇; _▹_; ⌊_⌋; _⊢_∷_; _⊢ty_
        ; IConWf; iwf-ι; iwf-κ; iwf-ρ; ICodeWf; icw-clo; icw-ford; icw-imu
        ; IDescWf; idwf-nil; idwf-cons
        ; ⊢var; here; there; ⊢fst; ⊢snd; ⊢nsuc; ⊢nzero
        ; ⊢⌜Nat⌝; ⊢⌜Id⌝; ⊢⌜IMu⌝; ⊢jsub
        ; ⊢pair; ty-Σ; ty-Nat; ty-IMu
        ; ξ-pairˡ; ξ-pairʳ; ξ-nsuc; βfst; βsnd )
open import DirectedHoTT.Examples.Knot.Sorts
  using ( IPair; sTy; sTm; sDesc; sDCon; sIDesc; sICon; sVar
        ; toI; fromI; ⊢ixP; ⊢sTy; ⊢sTm; ⊢sDesc; ⊢sDCon; ⊢sIDesc; ⊢sICon; ⊢sVar
        ; num; ⊢num )
open import DirectedHoTT.Examples.Knot.Desc using ( KnotD )
open import DirectedHoTT.Examples.Knot.Wf using ( KnotWf )
open import DirectedHoTT.Examples.Knot.Ctors
open import DirectedHoTT.Examples.Knot.CtorsV
open import DirectedHoTT.Examples.Knot.Build using ( Var-vzK; Var-vsK; ⊢Var-vzKt; ⊢Var-vsKt )
open import DirectedHoTT.Examples.Knot.Wk using ( wkK; ⊢wkK )
open import DirectedHoTT.Lib.ICast using ( toMu; fromMu; fordAs; muFwd )
open import DirectedHoTT.Lib.ArithComm using ( symN; ⊢symN )
open import DirectedHoTT.Metatheory.SubjectReduction using ( ⊢wk )
open import DirectedHoTT.Examples.Knot.Single using ( singleK; ⊢singleK )
open import DirectedHoTT.Examples.Knot.SubApp
  using ( subTmAtK; subTyAtK; ⊢subTmAtK; ⊢subTyAtK )
open import DirectedHoTT.Examples.Knot.SubMot using ( extNK; ⊢extNK )
open import DirectedHoTT.Examples.Knot.Pw using ( pwK; ⊢pwK )
open import DirectedHoTT.Examples.Knot.Stk
  using ( stkAK; ⊢stkAK; stkCK; ⊢stkCK; flatK; ⊢flatK )
open import DirectedHoTT.Examples.Knot.Nrs using ( nrsSubK; ⊢nrsSubK )
open import DirectedHoTT.Examples.Knot.PwBody using ( pwBodyK; ⊢pwBodyK )
open import DirectedHoTT.Examples.Knot.CtxD
  using ( CtxD; INat; CtxWf; Ctx-extK; ⊢Ctx-extKt; Ctx-empK; ⊢Ctx-empK )
open import DirectedHoTT.Examples.Knot.EWk using ( εwkK; ⊢εwkK; isingleK; ⊢isingleK )
open import DirectedHoTT.Examples.Knot.SubMot
  using ( sortMap-ty; sortMap-tm; sortMap-desc; sortMap-dcon
        ; sortMap-idesc; sortMap-icon; sortMap-var )
open import DirectedHoTT.Examples.Knot.Lookup using ( LkD; ILk; LkWf )
open import DirectedHoTT.Examples.Knot.ConvRows using ( ConvD; IConv )
open import DirectedHoTT.Examples.Knot.ConvWf using ( ConvWf )
open import DirectedHoTT.Examples.Knot.NoNatCRows using ( NoNatCD; INoNatC )
open import DirectedHoTT.Examples.Knot.NoNatCWf using ( NoNatCWf )
open import DirectedHoTT.Examples.Knot.InDRows using ( InDD; IInD )
open import DirectedHoTT.Examples.Knot.InDWf using ( InDWf )
open import DirectedHoTT.Examples.Knot.InIDRows using ( InIDD; IInID )
open import DirectedHoTT.Examples.Knot.InIDWf using ( InIDWf )
open import DirectedHoTT.Examples.Knot.IxD
  using ( IxD; IxWf; IxNoneK; ⊢IxNoneK; IxDConK; ⊢IxDConK; IxDescK; ⊢IxDescK
        ; IxIConK; ⊢IxIConK; IxIDescK; ⊢IxIDescK )
open import DirectedHoTT.Examples.Knot.JudgeRows
open import DirectedHoTT.Examples.Knot.JudgeWfA
open import DirectedHoTT.Examples.Knot.JudgeWfB
open import DirectedHoTT.Examples.Knot.JudgeWfC
open import DirectedHoTT.Examples.Knot.JudgeWfD
open import DirectedHoTT.Examples.Knot.JudgeWfE
open import DirectedHoTT.Examples.Knot.JudgeWfF
open import DirectedHoTT.Examples.Knot.JudgeWfG
open import DirectedHoTT.Examples.Knot.JudgeWfH

-- ty-Mu
-- ★ the telescope, back at `Ctx` level: `emit_jrow` had to
--   drop to a bare `Cx` at the premise to stay writable
--   before `JudgeD` existed.
JΙ4 JΙ5 JΙ6 JΙ7 JΙ8 JΙ9 JΙ10 : Ctx
JΙ4 = JΙ3 ▹ IMu JudgeD IJudge kJΙ3
JΙ5 = JΙ4 ▹ El kJΙ4
JΙ6 = JΙ5 ▹ El kJΙ5
JΙ7 = JΙ6 ▹ El kJΙ6
JΙ8 = JΙ7 ▹ El kJΙ7
JΙ9 = JΙ8 ▹ El kJΙ8
JΙ10 = JΙ9 ▹ El kJΙ9

aJΙ9 : JΙ9 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))) ∷ Nat
aJΙ9 = ⊢fst (⊢var (there (there (there (there (there (there (there (there (there here))))))))))
CJΙ9 : ICon ⌊ JΙ9 ⌋
CJΙ9 = iκ kJΙ9 iι
W_JΙ9 : IConWf JudgeD IJudge JΙ9 CJΙ9
W_JΙ9 =
  iwf-κ kJΙ9 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ IxWf (toI aJΙ9))
           (toMu (⊢snd (⊢snd (⊢snd (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there (there (there here))))))))))))))))
           (⊢jsub (⊢⌜IMu⌝ IxWf (toI (fromI (⊢var here))))
                  (toI (fromI (⊢var (there (there (there (there (there (there (there (there here)))))))))))
                  (toI aJΙ9)
                  (⊢symN aJΙ9 (fromI (⊢var (there (there (there (there (there (there (there (there here))))))))))
                         (fordAs (⊢var (there (there (there (there here)))))))
                  (toMu (⊢IxNoneK (fromI (⊢var (there (there (there (there (there (there (there (there here))))))))))))))
    iwf-ι

aJΙ8 : JΙ8 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))) ∷ Nat
aJΙ8 = ⊢fst (⊢var (there (there (there (there (there (there (there (there here)))))))))
CJΙ8 : ICon ⌊ JΙ8 ⌋
CJΙ8 = iκ kJΙ8 CJΙ9
W_JΙ8 : IConWf JudgeD IJudge JΙ8 CJΙ8
W_JΙ8 =
  iwf-κ kJΙ8 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝
           (toI (⊢fst (⊢snd (⊢snd (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there (there here)))))))))))))))
           (⊢jsub ⊢⌜Nat⌝
                  (toI (fromI (⊢var (there (there (there (there (there (there (there here))))))))))
                  (toI aJΙ8)
                  (⊢symN aJΙ8 (fromI (⊢var (there (there (there (there (there (there (there here)))))))))
                         (fordAs (⊢var (there (there (there here))))))
                  (toI (⊢num 0))))
    W_JΙ9

aJΙ7 : JΙ7 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs vz)))))))) ∷ Nat
aJΙ7 = ⊢fst (⊢var (there (there (there (there (there (there (there here))))))))
CJΙ7 : ICon ⌊ JΙ7 ⌋
CJΙ7 = iκ kJΙ7 CJΙ8
W_JΙ7 : IConWf JudgeD IJudge JΙ7 CJΙ7
W_JΙ7 =
  iwf-κ kJΙ7 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTy aJΙ7))
           (toMu (⊢fst (⊢snd (⊢snd (⊢snd (⊢var (there (there (there (there (there (there (there here)))))))))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTy (fromI (⊢var here))))
                  (toI (fromI (⊢var (there (there (there (there (there (there here)))))))))
                  (toI aJΙ7)
                  (⊢symN aJΙ7 (fromI (⊢var (there (there (there (there (there (there here))))))))
                         (fordAs (⊢var (there (there here)))))
                  (toMu (⊢Ty-MuKv (var (vs (vs (vs (vs (vs (vs vz))))))) (fromI (⊢var (there (there (there (there (there (there here)))))))) (⊢εwkK ⊢sDesc sortMap-desc (fromI (⊢var (there (there (there (there (there (there here)))))))) (fromMu (⊢var (there (there (there (there here)))))))))))
    W_JΙ8

aJΙ6 : JΙ6 ⊢ fst (var (vs (vs (vs (vs (vs (vs vz))))))) ∷ Nat
aJΙ6 = ⊢fst (⊢var (there (there (there (there (there (there here)))))))
CJΙ6 : ICon ⌊ JΙ6 ⌋
CJΙ6 = iκ kJΙ6 CJΙ7
W_JΙ6 : IConWf JudgeD IJudge JΙ6 CJΙ6
W_JΙ6 =
  iwf-κ kJΙ6 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aJΙ6))
           (toMu (⊢fst (⊢snd (⊢snd (⊢var (there (there (there (there (there (there here)))))))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (there (there (there (there (there here))))))))
                  (toI aJΙ6)
                  (⊢symN aJΙ6 (fromI (⊢var (there (there (there (there (there here)))))))
                         (fordAs (⊢var (there here))))
                  (toMu (⊢Tm-unitKv (var (vs (vs (vs (vs (vs vz)))))) (fromI (⊢var (there (there (there (there (there here)))))))))))
    W_JΙ7

aJΙ5 : JΙ5 ⊢ fst (var (vs (vs (vs (vs (vs vz)))))) ∷ Nat
aJΙ5 = ⊢fst (⊢var (there (there (there (there (there here))))))
CJΙ5 : ICon ⌊ JΙ5 ⌋
CJΙ5 = iκ kJΙ5 CJΙ6
W_JΙ5 : IConWf JudgeD IJudge JΙ5 CJΙ5
W_JΙ5 =
  iwf-κ kJΙ5 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ CtxWf (toI aJΙ5))
           (toMu (⊢fst (⊢snd (⊢var (there (there (there (there (there here)))))))))
           (⊢jsub (⊢⌜IMu⌝ CtxWf (toI (fromI (⊢var here))))
                  (toI (fromI (⊢var (there (there (there (there here)))))))
                  (toI aJΙ5)
                  (⊢symN aJΙ5 (fromI (⊢var (there (there (there (there here))))))
                         (fordAs (⊢var here)))
                  (toMu (fromMu (⊢var (there (there (there here))))))))
    W_JΙ6

CJΙ4 : ICon ⌊ JΙ4 ⌋
CJΙ4 = iκ kJΙ4 CJΙ5
W_JΙ4 : IConWf JudgeD IJudge JΙ4 CJΙ4
W_JΙ4 =
  iwf-κ kJΙ4 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝ (toI (⊢fst (⊢var (there (there (there (there here))))))) (toI (fromI (⊢var (there (there (there here)))))))
    W_JΙ5

CJΙ3 : ICon ⌊ JΙ3 ⌋
CJΙ3 = iρ kJΙ3 CJΙ4
W_JΙ3 : IConWf JudgeD IJudge JΙ3 CJΙ3
W_JΙ3 =
  iwf-ρ kJΙ3
    (⊢pair (ty-Σ (ty-IMu CtxWf (toI (⊢var here))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢var (there here)))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢var (there (there here))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢var (there (there (there (there here))))))))))) (⊢num 0)
      (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢wk (⊢num 0)))) (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (⊢wk (⊢num 0))))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢wk (⊢wk (⊢num 0)))))))))) ⊢Ctx-empK
      (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTy (⊢wk (⊢num 0)))) (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢wk (⊢num 0)))))))) (⊢Tm-unitKv (num 0) (⊢num 0))
      (⊢pair (ty-Σ ty-Nat (ty-IMu IxWf (toI (⊢wk (⊢wk (⊢num 0)))))) (⊢Ty-NatKv (num 0) (⊢num 0))
      (⊢pair (ty-IMu IxWf (toI (⊢wk (⊢num 0)))) (⊢num 3) (⊢IxDescK (⊢num 0) (fromMu (⊢var here))))))))
    W_JΙ4

CJΙ2 : ICon ⌊ JΙ2 ⌋
CJΙ2 = iκ kJΙ2 CJΙ3
W_JΙ2 : IConWf JudgeD IJudge JΙ2 CJΙ2
W_JΙ2 =
  iwf-κ kJΙ2 (icw-imu (pair sDesc nzero) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sDesc ⊢nzero))
    W_JΙ3

CJΙ1 : ICon ⌊ JΙ1 ⌋
CJΙ1 = iκ kJΙ1 CJΙ2
W_JΙ1 : IConWf JudgeD IJudge JΙ1 CJΙ1
W_JΙ1 =
  iwf-κ kJΙ1 (icw-imu (var vz) CtxWf)
    (⊢⌜IMu⌝ CtxWf (toI (fromI (⊢var here))))
    W_JΙ2

CJΙ0 : ICon ⌊ JΙ0 ⌋
CJΙ0 = iκ kJΙ0 CJΙ1
W_JΙ0 : IConWf JudgeD IJudge JΙ0 CJΙ0
W_JΙ0 =
  iwf-κ kJΙ0 (icw-clo ⌜Nat⌝ ⊢⌜Nat⌝) ⊢⌜Nat⌝
    W_JΙ1

jdty-MuWf : IConWf JudgeD IJudge JΙ0 jdty-Mu
jdty-MuWf = W_JΙ0

