--- GENERATED by tools/gen-knot.py — do not edit.
------------------------------------------------------------------------
-- OCP-0009 · EXAMPLES — ★★★ `_⟶_` IS A WELL-FORMED DESCRIPTION.
--
-- ⚠ SPLIT FROM `Knot/RedRows` DELIBERATELY.  `Knot/Wf`'s 53 `IConWf`s
--   already cost 104s and need the compacting collector; these are 65
--   rows over a THREE-component index with a transport per component.
--   The rows and their well-formedness are independent artifacts, so
--   there is no reason to make one module carry both.
------------------------------------------------------------------------

{-# OPTIONS --safe #-}
module DirectedHoTT.Examples.Knot.RedWfOrd where
open import DirectedHoTT.Lib.Lkp using ( ∋lkp; vsⁿ )
open import DirectedHoTT.Spec.Typing using ( Θ₀; ρ₀; x₀; _,,_ )
open import DirectedHoTT.Spec.Syntax using ( thinR; keep; app; renTm )
open import normalizer.Syntax.Types using ( _≡_; refl )
open import Agda.Builtin.Nat using ( zero; suc ) renaming ( Nat to ℕ )
open import DirectedHoTT.Spec.Syntax
  using ( Cx; ε; _∙; RTy; RTm; var; vz; vs; pair; fst; snd; nsuc; nzero
        ; El; IMu; Σ'; Nat
        ; ⌜Nat⌝; ⌜Id⌝; ⌜IMu⌝; jsub; ICon; IDesc; iι; iρ; iκ; inil; _◂_; εwkTy )
open import DirectedHoTT.Spec.Typing
  using ( Ctx; ◇; _▹_; ⌊_⌋; _⊢_∷_; _⊢ty_
        ; IConWf; iwf-ι; iwf-κ; iwf-ρ; ICodeWf; icw-clo; icw-ford; icw-imu
        ; IDescWf; idwf-nil; idwf-cons
        ; ⊢var; here; there; ⊢fst; ⊢snd; ⊢nsuc; ⊢num; ⊢nzero
        ; ⊢⌜Nat⌝; ⊢⌜Id⌝; ⊢⌜IMu⌝; ⊢jsub
        ; ⊢pair; ty-Σ; ty-Nat; ty-IMu
        ; ξ-pairˡ; ξ-pairʳ; ξ-nsuc; βfst; βsnd )
open import DirectedHoTT.Examples.Knot.Sorts
  using ( IPair; sTy; sTm; sDesc; sDCon; sIDesc; sICon; sVar
        ; toI; fromI; ⊢ixP; ⊢sTy; ⊢sTm; ⊢sDesc; ⊢sDCon; ⊢sIDesc; ⊢sICon; ⊢sVar
        ; num; ⊢num )
open import DirectedHoTT.Examples.Knot.Desc using ( KnotD )
open import DirectedHoTT.Examples.Knot.Wf using ( KnotWf )
open import DirectedHoTT.Examples.Knot.Ctors
open import DirectedHoTT.Examples.Knot.CtorsV
open import DirectedHoTT.Examples.Knot.Build using ( Var-vzK; Var-vsK; ⊢Var-vzKt; ⊢Var-vsKt )
open import DirectedHoTT.Lib.ICast using ( toMu; fromMu; fordAs; muFwd )
open import DirectedHoTT.Lib.ArithComm using ( symN; ⊢symN )
open import DirectedHoTT.Metatheory.SubjectReduction using ( ⊢wk )
open import DirectedHoTT.Examples.Knot.Single using ( singleK; ⊢singleK )
open import DirectedHoTT.Examples.Knot.SubApp
  using ( subTmAtK; subTyAtK; ⊢subTmAtK; ⊢subTyAtK )
open import DirectedHoTT.Examples.Knot.SubMot using ( extNK; ⊢extNK )
open import DirectedHoTT.Examples.Knot.Pw using ( pwK; ⊢pwK )
open import DirectedHoTT.Examples.Knot.Stk
  using ( stkAK; ⊢stkAK; stkCK; ⊢stkCK; flatK; ⊢flatK )
open import DirectedHoTT.Examples.Knot.Nrs using ( nrsSubK; ⊢nrsSubK )
open import DirectedHoTT.Examples.Knot.PwBody using ( pwBodyK; ⊢pwBodyK )
open import DirectedHoTT.Examples.Knot.WkSub using ( wkTmK; ⊢wkTmK; wkTyK; ⊢wkTyK )
open import DirectedHoTT.Examples.Knot.RedRows


-- ordtr-z
-- ★ the telescope: the family, the index, then each field
--   read through the thinning that skips the family.
TelΙ0 : Ctx
TelΙ0 = Θ₀ IRed
GΙ0 : RTm ⌊ TelΙ0 ⌋
GΙ0 = ⌜Nat⌝
TelΙ1 : Ctx
TelΙ1 = TelΙ0 ▹ El GΙ0
GΙ1 : RTm ⌊ TelΙ1 ⌋
GΙ1 = ⌜IMu⌝ KnotD IPair (pair sTm (var vz))
TelΙ2 : Ctx
TelΙ2 = TelΙ1 ▹ El GΙ1
GΙ2 : RTm ⌊ TelΙ2 ⌋
GΙ2 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs vz)))
TelΙ3 : Ctx
TelΙ3 = TelΙ2 ▹ El GΙ2
GΙ3 : RTm ⌊ TelΙ3 ⌋
GΙ3 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs vz))))
TelΙ4 : Ctx
TelΙ4 = TelΙ3 ▹ El GΙ3
GΙ4 : RTm ⌊ TelΙ4 ⌋
GΙ4 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs (vs vz)))))
TelΙ5 : Ctx
TelΙ5 = TelΙ4 ▹ El GΙ4
GΙ5 : RTm ⌊ TelΙ5 ⌋
GΙ5 = ⌜Id⌝ ⌜Nat⌝ (fst (var (vs (vs (vs (vs (vs vz))))))) (var (vs (vs (vs (vs vz)))))
TelΙ6 : Ctx
TelΙ6 = TelΙ5 ▹ El GΙ5
GΙ6 : RTm ⌊ TelΙ6 ⌋
GΙ6 = ⌜Id⌝ (⌜IMu⌝ KnotD IPair (pair sTm (fst (var (vs (vs (vs (vs (vs (vs vz)))))))))) (fst (snd (var (vs (vs (vs (vs (vs (vs vz))))))))) (jsub (⌜IMu⌝ KnotD IPair (pair sTm (var vz))) (symN (fst (var (vs (vs (vs (vs (vs (vs vz)))))))) (var vz)) (Tm-ordtrK Tm-nzeroK (var (vs (vs (vs (vs vz))))) (var (vs (vs (vs vz)))) (var (vs (vs vz))) (var (vs vz))))
TelΙ7 : Ctx
TelΙ7 = TelΙ6 ▹ El GΙ6
GΙ7 : RTm ⌊ TelΙ7 ⌋
GΙ7 = ⌜Id⌝ (⌜IMu⌝ KnotD IPair (pair sTm (fst (var (vs (vs (vs (vs (vs (vs (vs vz))))))))))) (snd (snd (var (vs (vs (vs (vs (vs (vs (vs vz)))))))))) (jsub (⌜IMu⌝ KnotD IPair (pair sTm (var vz))) (symN (fst (var (vs (vs (vs (vs (vs (vs (vs vz))))))))) (var (vs vz))) Tm-unitK)
TelΙ8 : Ctx
TelΙ8 = TelΙ7 ▹ El GΙ7

aΙ7 : TelΙ7 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs vz)))))))) ∷ Nat
aΙ7 = ⊢fst (⊢var (∋lkp _ (vsⁿ 7 vz)))
CΙ7 : ICon ⌊ Ι7 ⌋
CΙ7 = iκ kΙ7 iι
W_Ι7 : IConWf IRed TelΙ7 (keep (keep (keep (keep (keep (keep (keep ρ₀))))))) (vs (vs (vs (vs (vs (vs (vs x₀))))))) CΙ7
W_Ι7 =
  iwf-κ kΙ7 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aΙ7))
           (toMu (⊢snd (⊢snd (⊢var (∋lkp _ (vsⁿ 7 vz))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (∋lkp _ (vsⁿ 6 vz)))))
                  (toI aΙ7)
                  (⊢symN aΙ7 (fromI (⊢var (∋lkp _ (vsⁿ 6 vz))))
                         (fordAs (⊢var (there here))))
                  (toMu (⊢Tm-unitKv (var (vs (vs (vs (vs (vs (vs vz))))))) (fromI (⊢var (∋lkp _ (vsⁿ 6 vz))))))))
    iwf-ι

aΙ6 : TelΙ6 ⊢ fst (var (vs (vs (vs (vs (vs (vs vz))))))) ∷ Nat
aΙ6 = ⊢fst (⊢var (∋lkp _ (vsⁿ 6 vz)))
CΙ6 : ICon ⌊ Ι6 ⌋
CΙ6 = iκ kΙ6 CΙ7
W_Ι6 : IConWf IRed TelΙ6 (keep (keep (keep (keep (keep (keep ρ₀)))))) (vs (vs (vs (vs (vs (vs x₀)))))) CΙ6
W_Ι6 =
  iwf-κ kΙ6 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aΙ6))
           (toMu (⊢fst (⊢snd (⊢var (∋lkp _ (vsⁿ 6 vz))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (∋lkp _ (vsⁿ 5 vz)))))
                  (toI aΙ6)
                  (⊢symN aΙ6 (fromI (⊢var (∋lkp _ (vsⁿ 5 vz))))
                         (fordAs (⊢var here)))
                  (toMu (⊢Tm-ordtrKv (var (vs (vs (vs (vs (vs vz)))))) (fromI (⊢var (∋lkp _ (vsⁿ 5 vz)))) (⊢Tm-nzeroKv (var (vs (vs (vs (vs (vs vz)))))) (fromI (⊢var (∋lkp _ (vsⁿ 5 vz))))) (fromMu (⊢var (∋lkp _ (vsⁿ 4 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 3 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 2 vz)))) (fromMu (⊢var (there here)))))))
    W_Ι7

CΙ5 : ICon ⌊ Ι5 ⌋
CΙ5 = iκ kΙ5 CΙ6
W_Ι5 : IConWf IRed TelΙ5 (keep (keep (keep (keep (keep ρ₀))))) (vs (vs (vs (vs (vs x₀))))) CΙ5
W_Ι5 =
  iwf-κ kΙ5 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝ (toI (⊢fst (⊢var (∋lkp _ (vsⁿ 5 vz))))) (toI (fromI (⊢var (∋lkp _ (vsⁿ 4 vz))))))
    W_Ι6

CΙ4 : ICon ⌊ Ι4 ⌋
CΙ4 = iκ kΙ4 CΙ5
W_Ι4 : IConWf IRed TelΙ4 (keep (keep (keep (keep ρ₀)))) (vs (vs (vs (vs x₀)))) CΙ4
W_Ι4 =
  iwf-κ kΙ4 (icw-imu (pair sTm (var (vs (vs (vs vz))))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 3 vz))))))
    W_Ι5

CΙ3 : ICon ⌊ Ι3 ⌋
CΙ3 = iκ kΙ3 CΙ4
W_Ι3 : IConWf IRed TelΙ3 (keep (keep (keep ρ₀))) (vs (vs (vs x₀))) CΙ3
W_Ι3 =
  iwf-κ kΙ3 (icw-imu (pair sTm (var (vs (vs vz)))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 2 vz))))))
    W_Ι4

CΙ2 : ICon ⌊ Ι2 ⌋
CΙ2 = iκ kΙ2 CΙ3
W_Ι2 : IConWf IRed TelΙ2 (keep (keep ρ₀)) (vs (vs x₀)) CΙ2
W_Ι2 =
  iwf-κ kΙ2 (icw-imu (pair sTm (var (vs vz))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (there here)))))
    W_Ι3

CΙ1 : ICon ⌊ Ι1 ⌋
CΙ1 = iκ kΙ1 CΙ2
W_Ι1 : IConWf IRed TelΙ1 (keep ρ₀) (vs x₀) CΙ1
W_Ι1 =
  iwf-κ kΙ1 (icw-imu (pair sTm (var vz)) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
    W_Ι2

CΙ0 : ICon ⌊ Ι0 ⌋
CΙ0 = iκ kΙ0 CΙ1
W_Ι0 : IConWf IRed TelΙ0 (ρ₀) (x₀) CΙ0
W_Ι0 =
  iwf-κ kΙ0 (icw-clo ⌜Nat⌝ ⊢⌜Nat⌝) ⊢⌜Nat⌝
    W_Ι1

rdordtr-zWf : IConWf IRed (Θ₀ IRed) ρ₀ x₀ rdordtr-z
rdordtr-zWf = W_Ι0

-- ordtr-szz
-- ★ the telescope: the family, the index, then each field
--   read through the thinning that skips the family.
TelΚ0 : Ctx
TelΚ0 = Θ₀ IRed
GΚ0 : RTm ⌊ TelΚ0 ⌋
GΚ0 = ⌜Nat⌝
TelΚ1 : Ctx
TelΚ1 = TelΚ0 ▹ El GΚ0
GΚ1 : RTm ⌊ TelΚ1 ⌋
GΚ1 = ⌜IMu⌝ KnotD IPair (pair sTm (var vz))
TelΚ2 : Ctx
TelΚ2 = TelΚ1 ▹ El GΚ1
GΚ2 : RTm ⌊ TelΚ2 ⌋
GΚ2 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs vz)))
TelΚ3 : Ctx
TelΚ3 = TelΚ2 ▹ El GΚ2
GΚ3 : RTm ⌊ TelΚ3 ⌋
GΚ3 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs vz))))
TelΚ4 : Ctx
TelΚ4 = TelΚ3 ▹ El GΚ3
GΚ4 : RTm ⌊ TelΚ4 ⌋
GΚ4 = ⌜Id⌝ ⌜Nat⌝ (fst (var (vs (vs (vs (vs vz)))))) (var (vs (vs (vs vz))))
TelΚ5 : Ctx
TelΚ5 = TelΚ4 ▹ El GΚ4
GΚ5 : RTm ⌊ TelΚ5 ⌋
GΚ5 = ⌜Id⌝ (⌜IMu⌝ KnotD IPair (pair sTm (fst (var (vs (vs (vs (vs (vs vz))))))))) (fst (snd (var (vs (vs (vs (vs (vs vz)))))))) (jsub (⌜IMu⌝ KnotD IPair (pair sTm (var vz))) (symN (fst (var (vs (vs (vs (vs (vs vz))))))) (var vz)) (Tm-ordtrK (Tm-nsucK (var (vs (vs (vs vz))))) Tm-nzeroK Tm-nzeroK (var (vs (vs vz))) (var (vs vz))))
TelΚ6 : Ctx
TelΚ6 = TelΚ5 ▹ El GΚ5
GΚ6 : RTm ⌊ TelΚ6 ⌋
GΚ6 = ⌜Id⌝ (⌜IMu⌝ KnotD IPair (pair sTm (fst (var (vs (vs (vs (vs (vs (vs vz)))))))))) (snd (snd (var (vs (vs (vs (vs (vs (vs vz))))))))) (jsub (⌜IMu⌝ KnotD IPair (pair sTm (var vz))) (symN (fst (var (vs (vs (vs (vs (vs (vs vz)))))))) (var (vs vz))) (var (vs (vs (vs vz)))))
TelΚ7 : Ctx
TelΚ7 = TelΚ6 ▹ El GΚ6

aΚ6 : TelΚ6 ⊢ fst (var (vs (vs (vs (vs (vs (vs vz))))))) ∷ Nat
aΚ6 = ⊢fst (⊢var (∋lkp _ (vsⁿ 6 vz)))
CΚ6 : ICon ⌊ Κ6 ⌋
CΚ6 = iκ kΚ6 iι
W_Κ6 : IConWf IRed TelΚ6 (keep (keep (keep (keep (keep (keep ρ₀)))))) (vs (vs (vs (vs (vs (vs x₀)))))) CΚ6
W_Κ6 =
  iwf-κ kΚ6 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aΚ6))
           (toMu (⊢snd (⊢snd (⊢var (∋lkp _ (vsⁿ 6 vz))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (∋lkp _ (vsⁿ 5 vz)))))
                  (toI aΚ6)
                  (⊢symN aΚ6 (fromI (⊢var (∋lkp _ (vsⁿ 5 vz))))
                         (fordAs (⊢var (there here))))
                  (toMu (fromMu (⊢var (∋lkp _ (vsⁿ 3 vz)))))))
    iwf-ι

aΚ5 : TelΚ5 ⊢ fst (var (vs (vs (vs (vs (vs vz)))))) ∷ Nat
aΚ5 = ⊢fst (⊢var (∋lkp _ (vsⁿ 5 vz)))
CΚ5 : ICon ⌊ Κ5 ⌋
CΚ5 = iκ kΚ5 CΚ6
W_Κ5 : IConWf IRed TelΚ5 (keep (keep (keep (keep (keep ρ₀))))) (vs (vs (vs (vs (vs x₀))))) CΚ5
W_Κ5 =
  iwf-κ kΚ5 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aΚ5))
           (toMu (⊢fst (⊢snd (⊢var (∋lkp _ (vsⁿ 5 vz))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (∋lkp _ (vsⁿ 4 vz)))))
                  (toI aΚ5)
                  (⊢symN aΚ5 (fromI (⊢var (∋lkp _ (vsⁿ 4 vz))))
                         (fordAs (⊢var here)))
                  (toMu (⊢Tm-ordtrKv (var (vs (vs (vs (vs vz))))) (fromI (⊢var (∋lkp _ (vsⁿ 4 vz)))) (⊢Tm-nsucKv (var (vs (vs (vs (vs vz))))) (fromI (⊢var (∋lkp _ (vsⁿ 4 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 3 vz))))) (⊢Tm-nzeroKv (var (vs (vs (vs (vs vz))))) (fromI (⊢var (∋lkp _ (vsⁿ 4 vz))))) (⊢Tm-nzeroKv (var (vs (vs (vs (vs vz))))) (fromI (⊢var (∋lkp _ (vsⁿ 4 vz))))) (fromMu (⊢var (∋lkp _ (vsⁿ 2 vz)))) (fromMu (⊢var (there here)))))))
    W_Κ6

CΚ4 : ICon ⌊ Κ4 ⌋
CΚ4 = iκ kΚ4 CΚ5
W_Κ4 : IConWf IRed TelΚ4 (keep (keep (keep (keep ρ₀)))) (vs (vs (vs (vs x₀)))) CΚ4
W_Κ4 =
  iwf-κ kΚ4 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝ (toI (⊢fst (⊢var (∋lkp _ (vsⁿ 4 vz))))) (toI (fromI (⊢var (∋lkp _ (vsⁿ 3 vz))))))
    W_Κ5

CΚ3 : ICon ⌊ Κ3 ⌋
CΚ3 = iκ kΚ3 CΚ4
W_Κ3 : IConWf IRed TelΚ3 (keep (keep (keep ρ₀))) (vs (vs (vs x₀))) CΚ3
W_Κ3 =
  iwf-κ kΚ3 (icw-imu (pair sTm (var (vs (vs vz)))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 2 vz))))))
    W_Κ4

CΚ2 : ICon ⌊ Κ2 ⌋
CΚ2 = iκ kΚ2 CΚ3
W_Κ2 : IConWf IRed TelΚ2 (keep (keep ρ₀)) (vs (vs x₀)) CΚ2
W_Κ2 =
  iwf-κ kΚ2 (icw-imu (pair sTm (var (vs vz))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (there here)))))
    W_Κ3

CΚ1 : ICon ⌊ Κ1 ⌋
CΚ1 = iκ kΚ1 CΚ2
W_Κ1 : IConWf IRed TelΚ1 (keep ρ₀) (vs x₀) CΚ1
W_Κ1 =
  iwf-κ kΚ1 (icw-imu (pair sTm (var vz)) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
    W_Κ2

CΚ0 : ICon ⌊ Κ0 ⌋
CΚ0 = iκ kΚ0 CΚ1
W_Κ0 : IConWf IRed TelΚ0 (ρ₀) (x₀) CΚ0
W_Κ0 =
  iwf-κ kΚ0 (icw-clo ⌜Nat⌝ ⊢⌜Nat⌝) ⊢⌜Nat⌝
    W_Κ1

rdordtr-szzWf : IConWf IRed (Θ₀ IRed) ρ₀ x₀ rdordtr-szz
rdordtr-szzWf = W_Κ0

-- ordtr-ssz
-- ★ the telescope: the family, the index, then each field
--   read through the thinning that skips the family.
TelΛ0 : Ctx
TelΛ0 = Θ₀ IRed
GΛ0 : RTm ⌊ TelΛ0 ⌋
GΛ0 = ⌜Nat⌝
TelΛ1 : Ctx
TelΛ1 = TelΛ0 ▹ El GΛ0
GΛ1 : RTm ⌊ TelΛ1 ⌋
GΛ1 = ⌜IMu⌝ KnotD IPair (pair sTm (var vz))
TelΛ2 : Ctx
TelΛ2 = TelΛ1 ▹ El GΛ1
GΛ2 : RTm ⌊ TelΛ2 ⌋
GΛ2 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs vz)))
TelΛ3 : Ctx
TelΛ3 = TelΛ2 ▹ El GΛ2
GΛ3 : RTm ⌊ TelΛ3 ⌋
GΛ3 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs vz))))
TelΛ4 : Ctx
TelΛ4 = TelΛ3 ▹ El GΛ3
GΛ4 : RTm ⌊ TelΛ4 ⌋
GΛ4 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs (vs vz)))))
TelΛ5 : Ctx
TelΛ5 = TelΛ4 ▹ El GΛ4
GΛ5 : RTm ⌊ TelΛ5 ⌋
GΛ5 = ⌜Id⌝ ⌜Nat⌝ (fst (var (vs (vs (vs (vs (vs vz))))))) (var (vs (vs (vs (vs vz)))))
TelΛ6 : Ctx
TelΛ6 = TelΛ5 ▹ El GΛ5
GΛ6 : RTm ⌊ TelΛ6 ⌋
GΛ6 = ⌜Id⌝ (⌜IMu⌝ KnotD IPair (pair sTm (fst (var (vs (vs (vs (vs (vs (vs vz)))))))))) (fst (snd (var (vs (vs (vs (vs (vs (vs vz))))))))) (jsub (⌜IMu⌝ KnotD IPair (pair sTm (var vz))) (symN (fst (var (vs (vs (vs (vs (vs (vs vz)))))))) (var vz)) (Tm-ordtrK (Tm-nsucK (var (vs (vs (vs (vs vz)))))) (Tm-nsucK (var (vs (vs (vs vz))))) Tm-nzeroK (var (vs (vs vz))) (var (vs vz))))
TelΛ7 : Ctx
TelΛ7 = TelΛ6 ▹ El GΛ6
GΛ7 : RTm ⌊ TelΛ7 ⌋
GΛ7 = ⌜Id⌝ (⌜IMu⌝ KnotD IPair (pair sTm (fst (var (vs (vs (vs (vs (vs (vs (vs vz))))))))))) (snd (snd (var (vs (vs (vs (vs (vs (vs (vs vz)))))))))) (jsub (⌜IMu⌝ KnotD IPair (pair sTm (var vz))) (symN (fst (var (vs (vs (vs (vs (vs (vs (vs vz))))))))) (var (vs vz))) (var (vs (vs vz))))
TelΛ8 : Ctx
TelΛ8 = TelΛ7 ▹ El GΛ7

aΛ7 : TelΛ7 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs vz)))))))) ∷ Nat
aΛ7 = ⊢fst (⊢var (∋lkp _ (vsⁿ 7 vz)))
CΛ7 : ICon ⌊ Λ7 ⌋
CΛ7 = iκ kΛ7 iι
W_Λ7 : IConWf IRed TelΛ7 (keep (keep (keep (keep (keep (keep (keep ρ₀))))))) (vs (vs (vs (vs (vs (vs (vs x₀))))))) CΛ7
W_Λ7 =
  iwf-κ kΛ7 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aΛ7))
           (toMu (⊢snd (⊢snd (⊢var (∋lkp _ (vsⁿ 7 vz))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (∋lkp _ (vsⁿ 6 vz)))))
                  (toI aΛ7)
                  (⊢symN aΛ7 (fromI (⊢var (∋lkp _ (vsⁿ 6 vz))))
                         (fordAs (⊢var (there here))))
                  (toMu (fromMu (⊢var (∋lkp _ (vsⁿ 2 vz)))))))
    iwf-ι

aΛ6 : TelΛ6 ⊢ fst (var (vs (vs (vs (vs (vs (vs vz))))))) ∷ Nat
aΛ6 = ⊢fst (⊢var (∋lkp _ (vsⁿ 6 vz)))
CΛ6 : ICon ⌊ Λ6 ⌋
CΛ6 = iκ kΛ6 CΛ7
W_Λ6 : IConWf IRed TelΛ6 (keep (keep (keep (keep (keep (keep ρ₀)))))) (vs (vs (vs (vs (vs (vs x₀)))))) CΛ6
W_Λ6 =
  iwf-κ kΛ6 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aΛ6))
           (toMu (⊢fst (⊢snd (⊢var (∋lkp _ (vsⁿ 6 vz))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (∋lkp _ (vsⁿ 5 vz)))))
                  (toI aΛ6)
                  (⊢symN aΛ6 (fromI (⊢var (∋lkp _ (vsⁿ 5 vz))))
                         (fordAs (⊢var here)))
                  (toMu (⊢Tm-ordtrKv (var (vs (vs (vs (vs (vs vz)))))) (fromI (⊢var (∋lkp _ (vsⁿ 5 vz)))) (⊢Tm-nsucKv (var (vs (vs (vs (vs (vs vz)))))) (fromI (⊢var (∋lkp _ (vsⁿ 5 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 4 vz))))) (⊢Tm-nsucKv (var (vs (vs (vs (vs (vs vz)))))) (fromI (⊢var (∋lkp _ (vsⁿ 5 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 3 vz))))) (⊢Tm-nzeroKv (var (vs (vs (vs (vs (vs vz)))))) (fromI (⊢var (∋lkp _ (vsⁿ 5 vz))))) (fromMu (⊢var (∋lkp _ (vsⁿ 2 vz)))) (fromMu (⊢var (there here)))))))
    W_Λ7

CΛ5 : ICon ⌊ Λ5 ⌋
CΛ5 = iκ kΛ5 CΛ6
W_Λ5 : IConWf IRed TelΛ5 (keep (keep (keep (keep (keep ρ₀))))) (vs (vs (vs (vs (vs x₀))))) CΛ5
W_Λ5 =
  iwf-κ kΛ5 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝ (toI (⊢fst (⊢var (∋lkp _ (vsⁿ 5 vz))))) (toI (fromI (⊢var (∋lkp _ (vsⁿ 4 vz))))))
    W_Λ6

CΛ4 : ICon ⌊ Λ4 ⌋
CΛ4 = iκ kΛ4 CΛ5
W_Λ4 : IConWf IRed TelΛ4 (keep (keep (keep (keep ρ₀)))) (vs (vs (vs (vs x₀)))) CΛ4
W_Λ4 =
  iwf-κ kΛ4 (icw-imu (pair sTm (var (vs (vs (vs vz))))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 3 vz))))))
    W_Λ5

CΛ3 : ICon ⌊ Λ3 ⌋
CΛ3 = iκ kΛ3 CΛ4
W_Λ3 : IConWf IRed TelΛ3 (keep (keep (keep ρ₀))) (vs (vs (vs x₀))) CΛ3
W_Λ3 =
  iwf-κ kΛ3 (icw-imu (pair sTm (var (vs (vs vz)))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 2 vz))))))
    W_Λ4

CΛ2 : ICon ⌊ Λ2 ⌋
CΛ2 = iκ kΛ2 CΛ3
W_Λ2 : IConWf IRed TelΛ2 (keep (keep ρ₀)) (vs (vs x₀)) CΛ2
W_Λ2 =
  iwf-κ kΛ2 (icw-imu (pair sTm (var (vs vz))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (there here)))))
    W_Λ3

CΛ1 : ICon ⌊ Λ1 ⌋
CΛ1 = iκ kΛ1 CΛ2
W_Λ1 : IConWf IRed TelΛ1 (keep ρ₀) (vs x₀) CΛ1
W_Λ1 =
  iwf-κ kΛ1 (icw-imu (pair sTm (var vz)) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
    W_Λ2

CΛ0 : ICon ⌊ Λ0 ⌋
CΛ0 = iκ kΛ0 CΛ1
W_Λ0 : IConWf IRed TelΛ0 (ρ₀) (x₀) CΛ0
W_Λ0 =
  iwf-κ kΛ0 (icw-clo ⌜Nat⌝ ⊢⌜Nat⌝) ⊢⌜Nat⌝
    W_Λ1

rdordtr-sszWf : IConWf IRed (Θ₀ IRed) ρ₀ x₀ rdordtr-ssz
rdordtr-sszWf = W_Λ0

-- ordtr-szs
-- ★ the telescope: the family, the index, then each field
--   read through the thinning that skips the family.
TelΜ0 : Ctx
TelΜ0 = Θ₀ IRed
GΜ0 : RTm ⌊ TelΜ0 ⌋
GΜ0 = ⌜Nat⌝
TelΜ1 : Ctx
TelΜ1 = TelΜ0 ▹ El GΜ0
GΜ1 : RTm ⌊ TelΜ1 ⌋
GΜ1 = ⌜IMu⌝ KnotD IPair (pair sTm (var vz))
TelΜ2 : Ctx
TelΜ2 = TelΜ1 ▹ El GΜ1
GΜ2 : RTm ⌊ TelΜ2 ⌋
GΜ2 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs vz)))
TelΜ3 : Ctx
TelΜ3 = TelΜ2 ▹ El GΜ2
GΜ3 : RTm ⌊ TelΜ3 ⌋
GΜ3 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs vz))))
TelΜ4 : Ctx
TelΜ4 = TelΜ3 ▹ El GΜ3
GΜ4 : RTm ⌊ TelΜ4 ⌋
GΜ4 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs (vs vz)))))
TelΜ5 : Ctx
TelΜ5 = TelΜ4 ▹ El GΜ4
GΜ5 : RTm ⌊ TelΜ5 ⌋
GΜ5 = ⌜Id⌝ ⌜Nat⌝ (fst (var (vs (vs (vs (vs (vs vz))))))) (var (vs (vs (vs (vs vz)))))
TelΜ6 : Ctx
TelΜ6 = TelΜ5 ▹ El GΜ5
GΜ6 : RTm ⌊ TelΜ6 ⌋
GΜ6 = ⌜Id⌝ (⌜IMu⌝ KnotD IPair (pair sTm (fst (var (vs (vs (vs (vs (vs (vs vz)))))))))) (fst (snd (var (vs (vs (vs (vs (vs (vs vz))))))))) (jsub (⌜IMu⌝ KnotD IPair (pair sTm (var vz))) (symN (fst (var (vs (vs (vs (vs (vs (vs vz)))))))) (var vz)) (Tm-ordtrK (Tm-nsucK (var (vs (vs (vs (vs vz)))))) Tm-nzeroK (Tm-nsucK (var (vs (vs (vs vz))))) (var (vs (vs vz))) (var (vs vz))))
TelΜ7 : Ctx
TelΜ7 = TelΜ6 ▹ El GΜ6
GΜ7 : RTm ⌊ TelΜ7 ⌋
GΜ7 = ⌜Id⌝ (⌜IMu⌝ KnotD IPair (pair sTm (fst (var (vs (vs (vs (vs (vs (vs (vs vz))))))))))) (snd (snd (var (vs (vs (vs (vs (vs (vs (vs vz)))))))))) (jsub (⌜IMu⌝ KnotD IPair (pair sTm (var vz))) (symN (fst (var (vs (vs (vs (vs (vs (vs (vs vz))))))))) (var (vs vz))) (Tm-absurdK (Tm-cHomK Tm-cNatK (var (vs (vs (vs (vs (vs vz)))))) (var (vs (vs (vs (vs vz)))))) (var (vs (vs (vs vz))))))
TelΜ8 : Ctx
TelΜ8 = TelΜ7 ▹ El GΜ7

aΜ7 : TelΜ7 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs vz)))))))) ∷ Nat
aΜ7 = ⊢fst (⊢var (∋lkp _ (vsⁿ 7 vz)))
CΜ7 : ICon ⌊ Μ7 ⌋
CΜ7 = iκ kΜ7 iι
W_Μ7 : IConWf IRed TelΜ7 (keep (keep (keep (keep (keep (keep (keep ρ₀))))))) (vs (vs (vs (vs (vs (vs (vs x₀))))))) CΜ7
W_Μ7 =
  iwf-κ kΜ7 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aΜ7))
           (toMu (⊢snd (⊢snd (⊢var (∋lkp _ (vsⁿ 7 vz))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (∋lkp _ (vsⁿ 6 vz)))))
                  (toI aΜ7)
                  (⊢symN aΜ7 (fromI (⊢var (∋lkp _ (vsⁿ 6 vz))))
                         (fordAs (⊢var (there here))))
                  (toMu (⊢Tm-absurdKv (var (vs (vs (vs (vs (vs (vs vz))))))) (fromI (⊢var (∋lkp _ (vsⁿ 6 vz)))) (⊢Tm-cHomKv (var (vs (vs (vs (vs (vs (vs vz))))))) (fromI (⊢var (∋lkp _ (vsⁿ 6 vz)))) (⊢Tm-cNatKv (var (vs (vs (vs (vs (vs (vs vz))))))) (fromI (⊢var (∋lkp _ (vsⁿ 6 vz))))) (fromMu (⊢var (∋lkp _ (vsⁿ 5 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 4 vz))))) (fromMu (⊢var (∋lkp _ (vsⁿ 3 vz))))))))
    iwf-ι

aΜ6 : TelΜ6 ⊢ fst (var (vs (vs (vs (vs (vs (vs vz))))))) ∷ Nat
aΜ6 = ⊢fst (⊢var (∋lkp _ (vsⁿ 6 vz)))
CΜ6 : ICon ⌊ Μ6 ⌋
CΜ6 = iκ kΜ6 CΜ7
W_Μ6 : IConWf IRed TelΜ6 (keep (keep (keep (keep (keep (keep ρ₀)))))) (vs (vs (vs (vs (vs (vs x₀)))))) CΜ6
W_Μ6 =
  iwf-κ kΜ6 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aΜ6))
           (toMu (⊢fst (⊢snd (⊢var (∋lkp _ (vsⁿ 6 vz))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (∋lkp _ (vsⁿ 5 vz)))))
                  (toI aΜ6)
                  (⊢symN aΜ6 (fromI (⊢var (∋lkp _ (vsⁿ 5 vz))))
                         (fordAs (⊢var here)))
                  (toMu (⊢Tm-ordtrKv (var (vs (vs (vs (vs (vs vz)))))) (fromI (⊢var (∋lkp _ (vsⁿ 5 vz)))) (⊢Tm-nsucKv (var (vs (vs (vs (vs (vs vz)))))) (fromI (⊢var (∋lkp _ (vsⁿ 5 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 4 vz))))) (⊢Tm-nzeroKv (var (vs (vs (vs (vs (vs vz)))))) (fromI (⊢var (∋lkp _ (vsⁿ 5 vz))))) (⊢Tm-nsucKv (var (vs (vs (vs (vs (vs vz)))))) (fromI (⊢var (∋lkp _ (vsⁿ 5 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 3 vz))))) (fromMu (⊢var (∋lkp _ (vsⁿ 2 vz)))) (fromMu (⊢var (there here)))))))
    W_Μ7

CΜ5 : ICon ⌊ Μ5 ⌋
CΜ5 = iκ kΜ5 CΜ6
W_Μ5 : IConWf IRed TelΜ5 (keep (keep (keep (keep (keep ρ₀))))) (vs (vs (vs (vs (vs x₀))))) CΜ5
W_Μ5 =
  iwf-κ kΜ5 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝ (toI (⊢fst (⊢var (∋lkp _ (vsⁿ 5 vz))))) (toI (fromI (⊢var (∋lkp _ (vsⁿ 4 vz))))))
    W_Μ6

CΜ4 : ICon ⌊ Μ4 ⌋
CΜ4 = iκ kΜ4 CΜ5
W_Μ4 : IConWf IRed TelΜ4 (keep (keep (keep (keep ρ₀)))) (vs (vs (vs (vs x₀)))) CΜ4
W_Μ4 =
  iwf-κ kΜ4 (icw-imu (pair sTm (var (vs (vs (vs vz))))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 3 vz))))))
    W_Μ5

CΜ3 : ICon ⌊ Μ3 ⌋
CΜ3 = iκ kΜ3 CΜ4
W_Μ3 : IConWf IRed TelΜ3 (keep (keep (keep ρ₀))) (vs (vs (vs x₀))) CΜ3
W_Μ3 =
  iwf-κ kΜ3 (icw-imu (pair sTm (var (vs (vs vz)))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 2 vz))))))
    W_Μ4

CΜ2 : ICon ⌊ Μ2 ⌋
CΜ2 = iκ kΜ2 CΜ3
W_Μ2 : IConWf IRed TelΜ2 (keep (keep ρ₀)) (vs (vs x₀)) CΜ2
W_Μ2 =
  iwf-κ kΜ2 (icw-imu (pair sTm (var (vs vz))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (there here)))))
    W_Μ3

CΜ1 : ICon ⌊ Μ1 ⌋
CΜ1 = iκ kΜ1 CΜ2
W_Μ1 : IConWf IRed TelΜ1 (keep ρ₀) (vs x₀) CΜ1
W_Μ1 =
  iwf-κ kΜ1 (icw-imu (pair sTm (var vz)) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
    W_Μ2

CΜ0 : ICon ⌊ Μ0 ⌋
CΜ0 = iκ kΜ0 CΜ1
W_Μ0 : IConWf IRed TelΜ0 (ρ₀) (x₀) CΜ0
W_Μ0 =
  iwf-κ kΜ0 (icw-clo ⌜Nat⌝ ⊢⌜Nat⌝) ⊢⌜Nat⌝
    W_Μ1

rdordtr-szsWf : IConWf IRed (Θ₀ IRed) ρ₀ x₀ rdordtr-szs
rdordtr-szsWf = W_Μ0

-- ordtr-sss
-- ★ the telescope: the family, the index, then each field
--   read through the thinning that skips the family.
TelΝ0 : Ctx
TelΝ0 = Θ₀ IRed
GΝ0 : RTm ⌊ TelΝ0 ⌋
GΝ0 = ⌜Nat⌝
TelΝ1 : Ctx
TelΝ1 = TelΝ0 ▹ El GΝ0
GΝ1 : RTm ⌊ TelΝ1 ⌋
GΝ1 = ⌜IMu⌝ KnotD IPair (pair sTm (var vz))
TelΝ2 : Ctx
TelΝ2 = TelΝ1 ▹ El GΝ1
GΝ2 : RTm ⌊ TelΝ2 ⌋
GΝ2 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs vz)))
TelΝ3 : Ctx
TelΝ3 = TelΝ2 ▹ El GΝ2
GΝ3 : RTm ⌊ TelΝ3 ⌋
GΝ3 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs vz))))
TelΝ4 : Ctx
TelΝ4 = TelΝ3 ▹ El GΝ3
GΝ4 : RTm ⌊ TelΝ4 ⌋
GΝ4 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs (vs vz)))))
TelΝ5 : Ctx
TelΝ5 = TelΝ4 ▹ El GΝ4
GΝ5 : RTm ⌊ TelΝ5 ⌋
GΝ5 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs (vs (vs vz))))))
TelΝ6 : Ctx
TelΝ6 = TelΝ5 ▹ El GΝ5
GΝ6 : RTm ⌊ TelΝ6 ⌋
GΝ6 = ⌜Id⌝ ⌜Nat⌝ (fst (var (vs (vs (vs (vs (vs (vs vz)))))))) (var (vs (vs (vs (vs (vs vz))))))
TelΝ7 : Ctx
TelΝ7 = TelΝ6 ▹ El GΝ6
GΝ7 : RTm ⌊ TelΝ7 ⌋
GΝ7 = ⌜Id⌝ (⌜IMu⌝ KnotD IPair (pair sTm (fst (var (vs (vs (vs (vs (vs (vs (vs vz))))))))))) (fst (snd (var (vs (vs (vs (vs (vs (vs (vs vz)))))))))) (jsub (⌜IMu⌝ KnotD IPair (pair sTm (var vz))) (symN (fst (var (vs (vs (vs (vs (vs (vs (vs vz))))))))) (var vz)) (Tm-ordtrK (Tm-nsucK (var (vs (vs (vs (vs (vs vz))))))) (Tm-nsucK (var (vs (vs (vs (vs vz)))))) (Tm-nsucK (var (vs (vs (vs vz))))) (var (vs (vs vz))) (var (vs vz))))
TelΝ8 : Ctx
TelΝ8 = TelΝ7 ▹ El GΝ7
GΝ8 : RTm ⌊ TelΝ8 ⌋
GΝ8 = ⌜Id⌝ (⌜IMu⌝ KnotD IPair (pair sTm (fst (var (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))) (snd (snd (var (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))) (jsub (⌜IMu⌝ KnotD IPair (pair sTm (var vz))) (symN (fst (var (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))) (var (vs vz))) (Tm-ordtrK (var (vs (vs (vs (vs (vs (vs vz))))))) (var (vs (vs (vs (vs (vs vz)))))) (var (vs (vs (vs (vs vz))))) (var (vs (vs (vs vz)))) (var (vs (vs vz)))))
TelΝ9 : Ctx
TelΝ9 = TelΝ8 ▹ El GΝ8

aΝ8 : TelΝ8 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))) ∷ Nat
aΝ8 = ⊢fst (⊢var (∋lkp _ (vsⁿ 8 vz)))
CΝ8 : ICon ⌊ Ν8 ⌋
CΝ8 = iκ kΝ8 iι
W_Ν8 : IConWf IRed TelΝ8 (keep (keep (keep (keep (keep (keep (keep (keep ρ₀)))))))) (vs (vs (vs (vs (vs (vs (vs (vs x₀)))))))) CΝ8
W_Ν8 =
  iwf-κ kΝ8 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aΝ8))
           (toMu (⊢snd (⊢snd (⊢var (∋lkp _ (vsⁿ 8 vz))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (∋lkp _ (vsⁿ 7 vz)))))
                  (toI aΝ8)
                  (⊢symN aΝ8 (fromI (⊢var (∋lkp _ (vsⁿ 7 vz))))
                         (fordAs (⊢var (there here))))
                  (toMu (⊢Tm-ordtrKv (var (vs (vs (vs (vs (vs (vs (vs vz)))))))) (fromI (⊢var (∋lkp _ (vsⁿ 7 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 6 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 5 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 4 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 3 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 2 vz))))))))
    iwf-ι

aΝ7 : TelΝ7 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs vz)))))))) ∷ Nat
aΝ7 = ⊢fst (⊢var (∋lkp _ (vsⁿ 7 vz)))
CΝ7 : ICon ⌊ Ν7 ⌋
CΝ7 = iκ kΝ7 CΝ8
W_Ν7 : IConWf IRed TelΝ7 (keep (keep (keep (keep (keep (keep (keep ρ₀))))))) (vs (vs (vs (vs (vs (vs (vs x₀))))))) CΝ7
W_Ν7 =
  iwf-κ kΝ7 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aΝ7))
           (toMu (⊢fst (⊢snd (⊢var (∋lkp _ (vsⁿ 7 vz))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (∋lkp _ (vsⁿ 6 vz)))))
                  (toI aΝ7)
                  (⊢symN aΝ7 (fromI (⊢var (∋lkp _ (vsⁿ 6 vz))))
                         (fordAs (⊢var here)))
                  (toMu (⊢Tm-ordtrKv (var (vs (vs (vs (vs (vs (vs vz))))))) (fromI (⊢var (∋lkp _ (vsⁿ 6 vz)))) (⊢Tm-nsucKv (var (vs (vs (vs (vs (vs (vs vz))))))) (fromI (⊢var (∋lkp _ (vsⁿ 6 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 5 vz))))) (⊢Tm-nsucKv (var (vs (vs (vs (vs (vs (vs vz))))))) (fromI (⊢var (∋lkp _ (vsⁿ 6 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 4 vz))))) (⊢Tm-nsucKv (var (vs (vs (vs (vs (vs (vs vz))))))) (fromI (⊢var (∋lkp _ (vsⁿ 6 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 3 vz))))) (fromMu (⊢var (∋lkp _ (vsⁿ 2 vz)))) (fromMu (⊢var (there here)))))))
    W_Ν8

CΝ6 : ICon ⌊ Ν6 ⌋
CΝ6 = iκ kΝ6 CΝ7
W_Ν6 : IConWf IRed TelΝ6 (keep (keep (keep (keep (keep (keep ρ₀)))))) (vs (vs (vs (vs (vs (vs x₀)))))) CΝ6
W_Ν6 =
  iwf-κ kΝ6 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝ (toI (⊢fst (⊢var (∋lkp _ (vsⁿ 6 vz))))) (toI (fromI (⊢var (∋lkp _ (vsⁿ 5 vz))))))
    W_Ν7

CΝ5 : ICon ⌊ Ν5 ⌋
CΝ5 = iκ kΝ5 CΝ6
W_Ν5 : IConWf IRed TelΝ5 (keep (keep (keep (keep (keep ρ₀))))) (vs (vs (vs (vs (vs x₀))))) CΝ5
W_Ν5 =
  iwf-κ kΝ5 (icw-imu (pair sTm (var (vs (vs (vs (vs vz)))))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 4 vz))))))
    W_Ν6

CΝ4 : ICon ⌊ Ν4 ⌋
CΝ4 = iκ kΝ4 CΝ5
W_Ν4 : IConWf IRed TelΝ4 (keep (keep (keep (keep ρ₀)))) (vs (vs (vs (vs x₀)))) CΝ4
W_Ν4 =
  iwf-κ kΝ4 (icw-imu (pair sTm (var (vs (vs (vs vz))))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 3 vz))))))
    W_Ν5

CΝ3 : ICon ⌊ Ν3 ⌋
CΝ3 = iκ kΝ3 CΝ4
W_Ν3 : IConWf IRed TelΝ3 (keep (keep (keep ρ₀))) (vs (vs (vs x₀))) CΝ3
W_Ν3 =
  iwf-κ kΝ3 (icw-imu (pair sTm (var (vs (vs vz)))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 2 vz))))))
    W_Ν4

CΝ2 : ICon ⌊ Ν2 ⌋
CΝ2 = iκ kΝ2 CΝ3
W_Ν2 : IConWf IRed TelΝ2 (keep (keep ρ₀)) (vs (vs x₀)) CΝ2
W_Ν2 =
  iwf-κ kΝ2 (icw-imu (pair sTm (var (vs vz))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (there here)))))
    W_Ν3

CΝ1 : ICon ⌊ Ν1 ⌋
CΝ1 = iκ kΝ1 CΝ2
W_Ν1 : IConWf IRed TelΝ1 (keep ρ₀) (vs x₀) CΝ1
W_Ν1 =
  iwf-κ kΝ1 (icw-imu (pair sTm (var vz)) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
    W_Ν2

CΝ0 : ICon ⌊ Ν0 ⌋
CΝ0 = iκ kΝ0 CΝ1
W_Ν0 : IConWf IRed TelΝ0 (ρ₀) (x₀) CΝ0
W_Ν0 =
  iwf-κ kΝ0 (icw-clo ⌜Nat⌝ ⊢⌜Nat⌝) ⊢⌜Nat⌝
    W_Ν1

rdordtr-sssWf : IConWf IRed (Θ₀ IRed) ρ₀ x₀ rdordtr-sss
rdordtr-sssWf = W_Ν0

-- ξ-ordtrᵃ
-- ★ the telescope: the family, the index, then each field
--   read through the thinning that skips the family.
TelΞ0 : Ctx
TelΞ0 = Θ₀ IRed
GΞ0 : RTm ⌊ TelΞ0 ⌋
GΞ0 = ⌜Nat⌝
TelΞ1 : Ctx
TelΞ1 = TelΞ0 ▹ El GΞ0
GΞ1 : RTm ⌊ TelΞ1 ⌋
GΞ1 = ⌜IMu⌝ KnotD IPair (pair sTm (var vz))
TelΞ2 : Ctx
TelΞ2 = TelΞ1 ▹ El GΞ1
GΞ2 : RTm ⌊ TelΞ2 ⌋
GΞ2 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs vz)))
TelΞ3 : Ctx
TelΞ3 = TelΞ2 ▹ El GΞ2
GΞ3 : RTm ⌊ TelΞ3 ⌋
GΞ3 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs vz))))
TelΞ4 : Ctx
TelΞ4 = TelΞ3 ▹ El GΞ3
GΞ4 : RTm ⌊ TelΞ4 ⌋
GΞ4 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs (vs vz)))))
TelΞ5 : Ctx
TelΞ5 = TelΞ4 ▹ El GΞ4
GΞ5 : RTm ⌊ TelΞ5 ⌋
GΞ5 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs (vs (vs vz))))))
TelΞ6 : Ctx
TelΞ6 = TelΞ5 ▹ El GΞ5
GΞ6 : RTm ⌊ TelΞ6 ⌋
GΞ6 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs (vs (vs (vs vz)))))))
TelΞ7 : Ctx
TelΞ7 = TelΞ6 ▹ El GΞ6
GΞ7 : RTm ⌊ TelΞ7 ⌋
GΞ7 = pair (var (vs (vs (vs (vs (vs (vs vz))))))) (pair (var (vs (vs (vs (vs (vs vz)))))) (var (vs (vs (vs (vs vz))))))
TelΞ8 : Ctx
TelΞ8 = TelΞ7 ▹ El (app (var (vs (vs (vs (vs (vs (vs (vs x₀)))))))) GΞ7)
GΞ8 : RTm ⌊ TelΞ8 ⌋
GΞ8 = ⌜Id⌝ ⌜Nat⌝ (fst (var (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))) (var (vs (vs (vs (vs (vs (vs (vs vz))))))))
TelΞ9 : Ctx
TelΞ9 = TelΞ8 ▹ El GΞ8
GΞ9 : RTm ⌊ TelΞ9 ⌋
GΞ9 = ⌜Id⌝ (⌜IMu⌝ KnotD IPair (pair sTm (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))))) (fst (snd (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))) (jsub (⌜IMu⌝ KnotD IPair (pair sTm (var vz))) (symN (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))) (var vz)) (Tm-ordtrK (var (vs (vs (vs (vs (vs (vs (vs vz)))))))) (var (vs (vs (vs (vs (vs vz)))))) (var (vs (vs (vs (vs vz))))) (var (vs (vs (vs vz)))) (var (vs (vs vz)))))
TelΞ10 : Ctx
TelΞ10 = TelΞ9 ▹ El GΞ9
GΞ10 : RTm ⌊ TelΞ10 ⌋
GΞ10 = ⌜Id⌝ (⌜IMu⌝ KnotD IPair (pair sTm (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))))) (snd (snd (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))))) (jsub (⌜IMu⌝ KnotD IPair (pair sTm (var vz))) (symN (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))) (var (vs vz))) (Tm-ordtrK (var (vs (vs (vs (vs (vs (vs (vs vz)))))))) (var (vs (vs (vs (vs (vs (vs vz))))))) (var (vs (vs (vs (vs (vs vz)))))) (var (vs (vs (vs (vs vz))))) (var (vs (vs (vs vz))))))
TelΞ11 : Ctx
TelΞ11 = TelΞ10 ▹ El GΞ10

aΞ10 : TelΞ10 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))) ∷ Nat
aΞ10 = ⊢fst (⊢var (∋lkp _ (vsⁿ 10 vz)))
CΞ10 : ICon XΞ10
CΞ10 = iκ kΞ10 iι
W_Ξ10 : IConWf IRed TelΞ10 (keep (keep (keep (keep (keep (keep (keep (keep (keep (keep ρ₀)))))))))) (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs x₀)))))))))) CΞ10
W_Ξ10 =
  iwf-κ kΞ10 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aΞ10))
           (toMu (⊢snd (⊢snd (⊢var (∋lkp _ (vsⁿ 10 vz))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (∋lkp _ (vsⁿ 9 vz)))))
                  (toI aΞ10)
                  (⊢symN aΞ10 (fromI (⊢var (∋lkp _ (vsⁿ 9 vz))))
                         (fordAs (⊢var (there here))))
                  (toMu (⊢Tm-ordtrKv (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))) (fromI (⊢var (∋lkp _ (vsⁿ 9 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 7 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 6 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 5 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 4 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 3 vz))))))))
    iwf-ι

aΞ9 : TelΞ9 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))) ∷ Nat
aΞ9 = ⊢fst (⊢var (∋lkp _ (vsⁿ 9 vz)))
CΞ9 : ICon XΞ9
CΞ9 = iκ kΞ9 CΞ10
W_Ξ9 : IConWf IRed TelΞ9 (keep (keep (keep (keep (keep (keep (keep (keep (keep ρ₀))))))))) (vs (vs (vs (vs (vs (vs (vs (vs (vs x₀))))))))) CΞ9
W_Ξ9 =
  iwf-κ kΞ9 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aΞ9))
           (toMu (⊢fst (⊢snd (⊢var (∋lkp _ (vsⁿ 9 vz))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (∋lkp _ (vsⁿ 8 vz)))))
                  (toI aΞ9)
                  (⊢symN aΞ9 (fromI (⊢var (∋lkp _ (vsⁿ 8 vz))))
                         (fordAs (⊢var here)))
                  (toMu (⊢Tm-ordtrKv (var (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))) (fromI (⊢var (∋lkp _ (vsⁿ 8 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 7 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 5 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 4 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 3 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 2 vz))))))))
    W_Ξ10

CΞ8 : ICon XΞ8
CΞ8 = iκ kΞ8 CΞ9
W_Ξ8 : IConWf IRed TelΞ8 (keep (keep (keep (keep (keep (keep (keep (keep ρ₀)))))))) (vs (vs (vs (vs (vs (vs (vs (vs x₀)))))))) CΞ8
W_Ξ8 =
  iwf-κ kΞ8 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝ (toI (⊢fst (⊢var (∋lkp _ (vsⁿ 8 vz))))) (toI (fromI (⊢var (∋lkp _ (vsⁿ 7 vz))))))
    W_Ξ9

CΞ7 : ICon ⌊ Ξ7 ⌋
CΞ7 = iρ kΞ7 CΞ8
W_Ξ7 : IConWf IRed TelΞ7 (keep (keep (keep (keep (keep (keep (keep ρ₀))))))) (vs (vs (vs (vs (vs (vs (vs x₀))))))) CΞ7
W_Ξ7 =
  iwf-ρ kΞ7
    (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢var here))) (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢var (there here))))) (fromI (⊢var (∋lkp _ (vsⁿ 6 vz))))
      (⊢pair (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢wk (fromI (⊢var (∋lkp _ (vsⁿ 6 vz))))))) (fromMu (⊢var (∋lkp _ (vsⁿ 5 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 4 vz))))))
    W_Ξ8

CΞ6 : ICon ⌊ Ξ6 ⌋
CΞ6 = iκ kΞ6 CΞ7
W_Ξ6 : IConWf IRed TelΞ6 (keep (keep (keep (keep (keep (keep ρ₀)))))) (vs (vs (vs (vs (vs (vs x₀)))))) CΞ6
W_Ξ6 =
  iwf-κ kΞ6 (icw-imu (pair sTm (var (vs (vs (vs (vs (vs vz))))))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 5 vz))))))
    W_Ξ7

CΞ5 : ICon ⌊ Ξ5 ⌋
CΞ5 = iκ kΞ5 CΞ6
W_Ξ5 : IConWf IRed TelΞ5 (keep (keep (keep (keep (keep ρ₀))))) (vs (vs (vs (vs (vs x₀))))) CΞ5
W_Ξ5 =
  iwf-κ kΞ5 (icw-imu (pair sTm (var (vs (vs (vs (vs vz)))))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 4 vz))))))
    W_Ξ6

CΞ4 : ICon ⌊ Ξ4 ⌋
CΞ4 = iκ kΞ4 CΞ5
W_Ξ4 : IConWf IRed TelΞ4 (keep (keep (keep (keep ρ₀)))) (vs (vs (vs (vs x₀)))) CΞ4
W_Ξ4 =
  iwf-κ kΞ4 (icw-imu (pair sTm (var (vs (vs (vs vz))))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 3 vz))))))
    W_Ξ5

CΞ3 : ICon ⌊ Ξ3 ⌋
CΞ3 = iκ kΞ3 CΞ4
W_Ξ3 : IConWf IRed TelΞ3 (keep (keep (keep ρ₀))) (vs (vs (vs x₀))) CΞ3
W_Ξ3 =
  iwf-κ kΞ3 (icw-imu (pair sTm (var (vs (vs vz)))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 2 vz))))))
    W_Ξ4

CΞ2 : ICon ⌊ Ξ2 ⌋
CΞ2 = iκ kΞ2 CΞ3
W_Ξ2 : IConWf IRed TelΞ2 (keep (keep ρ₀)) (vs (vs x₀)) CΞ2
W_Ξ2 =
  iwf-κ kΞ2 (icw-imu (pair sTm (var (vs vz))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (there here)))))
    W_Ξ3

CΞ1 : ICon ⌊ Ξ1 ⌋
CΞ1 = iκ kΞ1 CΞ2
W_Ξ1 : IConWf IRed TelΞ1 (keep ρ₀) (vs x₀) CΞ1
W_Ξ1 =
  iwf-κ kΞ1 (icw-imu (pair sTm (var vz)) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
    W_Ξ2

CΞ0 : ICon ⌊ Ξ0 ⌋
CΞ0 = iκ kΞ0 CΞ1
W_Ξ0 : IConWf IRed TelΞ0 (ρ₀) (x₀) CΞ0
W_Ξ0 =
  iwf-κ kΞ0 (icw-clo ⌜Nat⌝ ⊢⌜Nat⌝) ⊢⌜Nat⌝
    W_Ξ1

rdξ-ordtrᵃWf : IConWf IRed (Θ₀ IRed) ρ₀ x₀ rdξ-ordtrᵃ
rdξ-ordtrᵃWf = W_Ξ0

-- ξ-ordtrᵗ
-- ★ the telescope: the family, the index, then each field
--   read through the thinning that skips the family.
TelΟ0 : Ctx
TelΟ0 = Θ₀ IRed
GΟ0 : RTm ⌊ TelΟ0 ⌋
GΟ0 = ⌜Nat⌝
TelΟ1 : Ctx
TelΟ1 = TelΟ0 ▹ El GΟ0
GΟ1 : RTm ⌊ TelΟ1 ⌋
GΟ1 = ⌜IMu⌝ KnotD IPair (pair sTm (var vz))
TelΟ2 : Ctx
TelΟ2 = TelΟ1 ▹ El GΟ1
GΟ2 : RTm ⌊ TelΟ2 ⌋
GΟ2 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs vz)))
TelΟ3 : Ctx
TelΟ3 = TelΟ2 ▹ El GΟ2
GΟ3 : RTm ⌊ TelΟ3 ⌋
GΟ3 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs vz))))
TelΟ4 : Ctx
TelΟ4 = TelΟ3 ▹ El GΟ3
GΟ4 : RTm ⌊ TelΟ4 ⌋
GΟ4 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs (vs vz)))))
TelΟ5 : Ctx
TelΟ5 = TelΟ4 ▹ El GΟ4
GΟ5 : RTm ⌊ TelΟ5 ⌋
GΟ5 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs (vs (vs vz))))))
TelΟ6 : Ctx
TelΟ6 = TelΟ5 ▹ El GΟ5
GΟ6 : RTm ⌊ TelΟ6 ⌋
GΟ6 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs (vs (vs (vs vz)))))))
TelΟ7 : Ctx
TelΟ7 = TelΟ6 ▹ El GΟ6
GΟ7 : RTm ⌊ TelΟ7 ⌋
GΟ7 = pair (var (vs (vs (vs (vs (vs (vs vz))))))) (pair (var (vs (vs (vs (vs vz))))) (var (vs (vs (vs vz)))))
TelΟ8 : Ctx
TelΟ8 = TelΟ7 ▹ El (app (var (vs (vs (vs (vs (vs (vs (vs x₀)))))))) GΟ7)
GΟ8 : RTm ⌊ TelΟ8 ⌋
GΟ8 = ⌜Id⌝ ⌜Nat⌝ (fst (var (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))) (var (vs (vs (vs (vs (vs (vs (vs vz))))))))
TelΟ9 : Ctx
TelΟ9 = TelΟ8 ▹ El GΟ8
GΟ9 : RTm ⌊ TelΟ9 ⌋
GΟ9 = ⌜Id⌝ (⌜IMu⌝ KnotD IPair (pair sTm (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))))) (fst (snd (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))) (jsub (⌜IMu⌝ KnotD IPair (pair sTm (var vz))) (symN (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))) (var vz)) (Tm-ordtrK (var (vs (vs (vs (vs (vs (vs (vs vz)))))))) (var (vs (vs (vs (vs (vs (vs vz))))))) (var (vs (vs (vs (vs vz))))) (var (vs (vs (vs vz)))) (var (vs (vs vz)))))
TelΟ10 : Ctx
TelΟ10 = TelΟ9 ▹ El GΟ9
GΟ10 : RTm ⌊ TelΟ10 ⌋
GΟ10 = ⌜Id⌝ (⌜IMu⌝ KnotD IPair (pair sTm (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))))) (snd (snd (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))))) (jsub (⌜IMu⌝ KnotD IPair (pair sTm (var vz))) (symN (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))) (var (vs vz))) (Tm-ordtrK (var (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))) (var (vs (vs (vs (vs (vs (vs vz))))))) (var (vs (vs (vs (vs (vs vz)))))) (var (vs (vs (vs (vs vz))))) (var (vs (vs (vs vz))))))
TelΟ11 : Ctx
TelΟ11 = TelΟ10 ▹ El GΟ10

aΟ10 : TelΟ10 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))) ∷ Nat
aΟ10 = ⊢fst (⊢var (∋lkp _ (vsⁿ 10 vz)))
CΟ10 : ICon XΟ10
CΟ10 = iκ kΟ10 iι
W_Ο10 : IConWf IRed TelΟ10 (keep (keep (keep (keep (keep (keep (keep (keep (keep (keep ρ₀)))))))))) (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs x₀)))))))))) CΟ10
W_Ο10 =
  iwf-κ kΟ10 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aΟ10))
           (toMu (⊢snd (⊢snd (⊢var (∋lkp _ (vsⁿ 10 vz))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (∋lkp _ (vsⁿ 9 vz)))))
                  (toI aΟ10)
                  (⊢symN aΟ10 (fromI (⊢var (∋lkp _ (vsⁿ 9 vz))))
                         (fordAs (⊢var (there here))))
                  (toMu (⊢Tm-ordtrKv (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))) (fromI (⊢var (∋lkp _ (vsⁿ 9 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 8 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 6 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 5 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 4 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 3 vz))))))))
    iwf-ι

aΟ9 : TelΟ9 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))) ∷ Nat
aΟ9 = ⊢fst (⊢var (∋lkp _ (vsⁿ 9 vz)))
CΟ9 : ICon XΟ9
CΟ9 = iκ kΟ9 CΟ10
W_Ο9 : IConWf IRed TelΟ9 (keep (keep (keep (keep (keep (keep (keep (keep (keep ρ₀))))))))) (vs (vs (vs (vs (vs (vs (vs (vs (vs x₀))))))))) CΟ9
W_Ο9 =
  iwf-κ kΟ9 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aΟ9))
           (toMu (⊢fst (⊢snd (⊢var (∋lkp _ (vsⁿ 9 vz))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (∋lkp _ (vsⁿ 8 vz)))))
                  (toI aΟ9)
                  (⊢symN aΟ9 (fromI (⊢var (∋lkp _ (vsⁿ 8 vz))))
                         (fordAs (⊢var here)))
                  (toMu (⊢Tm-ordtrKv (var (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))) (fromI (⊢var (∋lkp _ (vsⁿ 8 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 7 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 6 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 4 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 3 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 2 vz))))))))
    W_Ο10

CΟ8 : ICon XΟ8
CΟ8 = iκ kΟ8 CΟ9
W_Ο8 : IConWf IRed TelΟ8 (keep (keep (keep (keep (keep (keep (keep (keep ρ₀)))))))) (vs (vs (vs (vs (vs (vs (vs (vs x₀)))))))) CΟ8
W_Ο8 =
  iwf-κ kΟ8 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝ (toI (⊢fst (⊢var (∋lkp _ (vsⁿ 8 vz))))) (toI (fromI (⊢var (∋lkp _ (vsⁿ 7 vz))))))
    W_Ο9

CΟ7 : ICon ⌊ Ο7 ⌋
CΟ7 = iρ kΟ7 CΟ8
W_Ο7 : IConWf IRed TelΟ7 (keep (keep (keep (keep (keep (keep (keep ρ₀))))))) (vs (vs (vs (vs (vs (vs (vs x₀))))))) CΟ7
W_Ο7 =
  iwf-ρ kΟ7
    (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢var here))) (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢var (there here))))) (fromI (⊢var (∋lkp _ (vsⁿ 6 vz))))
      (⊢pair (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢wk (fromI (⊢var (∋lkp _ (vsⁿ 6 vz))))))) (fromMu (⊢var (∋lkp _ (vsⁿ 4 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 3 vz))))))
    W_Ο8

CΟ6 : ICon ⌊ Ο6 ⌋
CΟ6 = iκ kΟ6 CΟ7
W_Ο6 : IConWf IRed TelΟ6 (keep (keep (keep (keep (keep (keep ρ₀)))))) (vs (vs (vs (vs (vs (vs x₀)))))) CΟ6
W_Ο6 =
  iwf-κ kΟ6 (icw-imu (pair sTm (var (vs (vs (vs (vs (vs vz))))))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 5 vz))))))
    W_Ο7

CΟ5 : ICon ⌊ Ο5 ⌋
CΟ5 = iκ kΟ5 CΟ6
W_Ο5 : IConWf IRed TelΟ5 (keep (keep (keep (keep (keep ρ₀))))) (vs (vs (vs (vs (vs x₀))))) CΟ5
W_Ο5 =
  iwf-κ kΟ5 (icw-imu (pair sTm (var (vs (vs (vs (vs vz)))))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 4 vz))))))
    W_Ο6

CΟ4 : ICon ⌊ Ο4 ⌋
CΟ4 = iκ kΟ4 CΟ5
W_Ο4 : IConWf IRed TelΟ4 (keep (keep (keep (keep ρ₀)))) (vs (vs (vs (vs x₀)))) CΟ4
W_Ο4 =
  iwf-κ kΟ4 (icw-imu (pair sTm (var (vs (vs (vs vz))))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 3 vz))))))
    W_Ο5

CΟ3 : ICon ⌊ Ο3 ⌋
CΟ3 = iκ kΟ3 CΟ4
W_Ο3 : IConWf IRed TelΟ3 (keep (keep (keep ρ₀))) (vs (vs (vs x₀))) CΟ3
W_Ο3 =
  iwf-κ kΟ3 (icw-imu (pair sTm (var (vs (vs vz)))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 2 vz))))))
    W_Ο4

CΟ2 : ICon ⌊ Ο2 ⌋
CΟ2 = iκ kΟ2 CΟ3
W_Ο2 : IConWf IRed TelΟ2 (keep (keep ρ₀)) (vs (vs x₀)) CΟ2
W_Ο2 =
  iwf-κ kΟ2 (icw-imu (pair sTm (var (vs vz))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (there here)))))
    W_Ο3

CΟ1 : ICon ⌊ Ο1 ⌋
CΟ1 = iκ kΟ1 CΟ2
W_Ο1 : IConWf IRed TelΟ1 (keep ρ₀) (vs x₀) CΟ1
W_Ο1 =
  iwf-κ kΟ1 (icw-imu (pair sTm (var vz)) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
    W_Ο2

CΟ0 : ICon ⌊ Ο0 ⌋
CΟ0 = iκ kΟ0 CΟ1
W_Ο0 : IConWf IRed TelΟ0 (ρ₀) (x₀) CΟ0
W_Ο0 =
  iwf-κ kΟ0 (icw-clo ⌜Nat⌝ ⊢⌜Nat⌝) ⊢⌜Nat⌝
    W_Ο1

rdξ-ordtrᵗWf : IConWf IRed (Θ₀ IRed) ρ₀ x₀ rdξ-ordtrᵗ
rdξ-ordtrᵗWf = W_Ο0

-- ξ-ordtrᵘ
-- ★ the telescope: the family, the index, then each field
--   read through the thinning that skips the family.
TelΠ0 : Ctx
TelΠ0 = Θ₀ IRed
GΠ0 : RTm ⌊ TelΠ0 ⌋
GΠ0 = ⌜Nat⌝
TelΠ1 : Ctx
TelΠ1 = TelΠ0 ▹ El GΠ0
GΠ1 : RTm ⌊ TelΠ1 ⌋
GΠ1 = ⌜IMu⌝ KnotD IPair (pair sTm (var vz))
TelΠ2 : Ctx
TelΠ2 = TelΠ1 ▹ El GΠ1
GΠ2 : RTm ⌊ TelΠ2 ⌋
GΠ2 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs vz)))
TelΠ3 : Ctx
TelΠ3 = TelΠ2 ▹ El GΠ2
GΠ3 : RTm ⌊ TelΠ3 ⌋
GΠ3 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs vz))))
TelΠ4 : Ctx
TelΠ4 = TelΠ3 ▹ El GΠ3
GΠ4 : RTm ⌊ TelΠ4 ⌋
GΠ4 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs (vs vz)))))
TelΠ5 : Ctx
TelΠ5 = TelΠ4 ▹ El GΠ4
GΠ5 : RTm ⌊ TelΠ5 ⌋
GΠ5 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs (vs (vs vz))))))
TelΠ6 : Ctx
TelΠ6 = TelΠ5 ▹ El GΠ5
GΠ6 : RTm ⌊ TelΠ6 ⌋
GΠ6 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs (vs (vs (vs vz)))))))
TelΠ7 : Ctx
TelΠ7 = TelΠ6 ▹ El GΠ6
GΠ7 : RTm ⌊ TelΠ7 ⌋
GΠ7 = pair (var (vs (vs (vs (vs (vs (vs vz))))))) (pair (var (vs (vs (vs vz)))) (var (vs (vs vz))))
TelΠ8 : Ctx
TelΠ8 = TelΠ7 ▹ El (app (var (vs (vs (vs (vs (vs (vs (vs x₀)))))))) GΠ7)
GΠ8 : RTm ⌊ TelΠ8 ⌋
GΠ8 = ⌜Id⌝ ⌜Nat⌝ (fst (var (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))) (var (vs (vs (vs (vs (vs (vs (vs vz))))))))
TelΠ9 : Ctx
TelΠ9 = TelΠ8 ▹ El GΠ8
GΠ9 : RTm ⌊ TelΠ9 ⌋
GΠ9 = ⌜Id⌝ (⌜IMu⌝ KnotD IPair (pair sTm (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))))) (fst (snd (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))) (jsub (⌜IMu⌝ KnotD IPair (pair sTm (var vz))) (symN (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))) (var vz)) (Tm-ordtrK (var (vs (vs (vs (vs (vs (vs (vs vz)))))))) (var (vs (vs (vs (vs (vs (vs vz))))))) (var (vs (vs (vs (vs (vs vz)))))) (var (vs (vs (vs vz)))) (var (vs (vs vz)))))
TelΠ10 : Ctx
TelΠ10 = TelΠ9 ▹ El GΠ9
GΠ10 : RTm ⌊ TelΠ10 ⌋
GΠ10 = ⌜Id⌝ (⌜IMu⌝ KnotD IPair (pair sTm (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))))) (snd (snd (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))))) (jsub (⌜IMu⌝ KnotD IPair (pair sTm (var vz))) (symN (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))) (var (vs vz))) (Tm-ordtrK (var (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))) (var (vs (vs (vs (vs (vs (vs (vs vz)))))))) (var (vs (vs (vs (vs (vs vz)))))) (var (vs (vs (vs (vs vz))))) (var (vs (vs (vs vz))))))
TelΠ11 : Ctx
TelΠ11 = TelΠ10 ▹ El GΠ10

aΠ10 : TelΠ10 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))) ∷ Nat
aΠ10 = ⊢fst (⊢var (∋lkp _ (vsⁿ 10 vz)))
CΠ10 : ICon XΠ10
CΠ10 = iκ kΠ10 iι
W_Π10 : IConWf IRed TelΠ10 (keep (keep (keep (keep (keep (keep (keep (keep (keep (keep ρ₀)))))))))) (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs x₀)))))))))) CΠ10
W_Π10 =
  iwf-κ kΠ10 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aΠ10))
           (toMu (⊢snd (⊢snd (⊢var (∋lkp _ (vsⁿ 10 vz))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (∋lkp _ (vsⁿ 9 vz)))))
                  (toI aΠ10)
                  (⊢symN aΠ10 (fromI (⊢var (∋lkp _ (vsⁿ 9 vz))))
                         (fordAs (⊢var (there here))))
                  (toMu (⊢Tm-ordtrKv (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))) (fromI (⊢var (∋lkp _ (vsⁿ 9 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 8 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 7 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 5 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 4 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 3 vz))))))))
    iwf-ι

aΠ9 : TelΠ9 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))) ∷ Nat
aΠ9 = ⊢fst (⊢var (∋lkp _ (vsⁿ 9 vz)))
CΠ9 : ICon XΠ9
CΠ9 = iκ kΠ9 CΠ10
W_Π9 : IConWf IRed TelΠ9 (keep (keep (keep (keep (keep (keep (keep (keep (keep ρ₀))))))))) (vs (vs (vs (vs (vs (vs (vs (vs (vs x₀))))))))) CΠ9
W_Π9 =
  iwf-κ kΠ9 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aΠ9))
           (toMu (⊢fst (⊢snd (⊢var (∋lkp _ (vsⁿ 9 vz))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (∋lkp _ (vsⁿ 8 vz)))))
                  (toI aΠ9)
                  (⊢symN aΠ9 (fromI (⊢var (∋lkp _ (vsⁿ 8 vz))))
                         (fordAs (⊢var here)))
                  (toMu (⊢Tm-ordtrKv (var (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))) (fromI (⊢var (∋lkp _ (vsⁿ 8 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 7 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 6 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 5 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 3 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 2 vz))))))))
    W_Π10

CΠ8 : ICon XΠ8
CΠ8 = iκ kΠ8 CΠ9
W_Π8 : IConWf IRed TelΠ8 (keep (keep (keep (keep (keep (keep (keep (keep ρ₀)))))))) (vs (vs (vs (vs (vs (vs (vs (vs x₀)))))))) CΠ8
W_Π8 =
  iwf-κ kΠ8 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝ (toI (⊢fst (⊢var (∋lkp _ (vsⁿ 8 vz))))) (toI (fromI (⊢var (∋lkp _ (vsⁿ 7 vz))))))
    W_Π9

CΠ7 : ICon ⌊ Π7 ⌋
CΠ7 = iρ kΠ7 CΠ8
W_Π7 : IConWf IRed TelΠ7 (keep (keep (keep (keep (keep (keep (keep ρ₀))))))) (vs (vs (vs (vs (vs (vs (vs x₀))))))) CΠ7
W_Π7 =
  iwf-ρ kΠ7
    (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢var here))) (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢var (there here))))) (fromI (⊢var (∋lkp _ (vsⁿ 6 vz))))
      (⊢pair (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢wk (fromI (⊢var (∋lkp _ (vsⁿ 6 vz))))))) (fromMu (⊢var (∋lkp _ (vsⁿ 3 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 2 vz))))))
    W_Π8

CΠ6 : ICon ⌊ Π6 ⌋
CΠ6 = iκ kΠ6 CΠ7
W_Π6 : IConWf IRed TelΠ6 (keep (keep (keep (keep (keep (keep ρ₀)))))) (vs (vs (vs (vs (vs (vs x₀)))))) CΠ6
W_Π6 =
  iwf-κ kΠ6 (icw-imu (pair sTm (var (vs (vs (vs (vs (vs vz))))))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 5 vz))))))
    W_Π7

CΠ5 : ICon ⌊ Π5 ⌋
CΠ5 = iκ kΠ5 CΠ6
W_Π5 : IConWf IRed TelΠ5 (keep (keep (keep (keep (keep ρ₀))))) (vs (vs (vs (vs (vs x₀))))) CΠ5
W_Π5 =
  iwf-κ kΠ5 (icw-imu (pair sTm (var (vs (vs (vs (vs vz)))))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 4 vz))))))
    W_Π6

CΠ4 : ICon ⌊ Π4 ⌋
CΠ4 = iκ kΠ4 CΠ5
W_Π4 : IConWf IRed TelΠ4 (keep (keep (keep (keep ρ₀)))) (vs (vs (vs (vs x₀)))) CΠ4
W_Π4 =
  iwf-κ kΠ4 (icw-imu (pair sTm (var (vs (vs (vs vz))))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 3 vz))))))
    W_Π5

CΠ3 : ICon ⌊ Π3 ⌋
CΠ3 = iκ kΠ3 CΠ4
W_Π3 : IConWf IRed TelΠ3 (keep (keep (keep ρ₀))) (vs (vs (vs x₀))) CΠ3
W_Π3 =
  iwf-κ kΠ3 (icw-imu (pair sTm (var (vs (vs vz)))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 2 vz))))))
    W_Π4

CΠ2 : ICon ⌊ Π2 ⌋
CΠ2 = iκ kΠ2 CΠ3
W_Π2 : IConWf IRed TelΠ2 (keep (keep ρ₀)) (vs (vs x₀)) CΠ2
W_Π2 =
  iwf-κ kΠ2 (icw-imu (pair sTm (var (vs vz))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (there here)))))
    W_Π3

CΠ1 : ICon ⌊ Π1 ⌋
CΠ1 = iκ kΠ1 CΠ2
W_Π1 : IConWf IRed TelΠ1 (keep ρ₀) (vs x₀) CΠ1
W_Π1 =
  iwf-κ kΠ1 (icw-imu (pair sTm (var vz)) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
    W_Π2

CΠ0 : ICon ⌊ Π0 ⌋
CΠ0 = iκ kΠ0 CΠ1
W_Π0 : IConWf IRed TelΠ0 (ρ₀) (x₀) CΠ0
W_Π0 =
  iwf-κ kΠ0 (icw-clo ⌜Nat⌝ ⊢⌜Nat⌝) ⊢⌜Nat⌝
    W_Π1

rdξ-ordtrᵘWf : IConWf IRed (Θ₀ IRed) ρ₀ x₀ rdξ-ordtrᵘ
rdξ-ordtrᵘWf = W_Π0

-- ξ-ordtrᵖ
-- ★ the telescope: the family, the index, then each field
--   read through the thinning that skips the family.
TelΡ0 : Ctx
TelΡ0 = Θ₀ IRed
GΡ0 : RTm ⌊ TelΡ0 ⌋
GΡ0 = ⌜Nat⌝
TelΡ1 : Ctx
TelΡ1 = TelΡ0 ▹ El GΡ0
GΡ1 : RTm ⌊ TelΡ1 ⌋
GΡ1 = ⌜IMu⌝ KnotD IPair (pair sTm (var vz))
TelΡ2 : Ctx
TelΡ2 = TelΡ1 ▹ El GΡ1
GΡ2 : RTm ⌊ TelΡ2 ⌋
GΡ2 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs vz)))
TelΡ3 : Ctx
TelΡ3 = TelΡ2 ▹ El GΡ2
GΡ3 : RTm ⌊ TelΡ3 ⌋
GΡ3 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs vz))))
TelΡ4 : Ctx
TelΡ4 = TelΡ3 ▹ El GΡ3
GΡ4 : RTm ⌊ TelΡ4 ⌋
GΡ4 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs (vs vz)))))
TelΡ5 : Ctx
TelΡ5 = TelΡ4 ▹ El GΡ4
GΡ5 : RTm ⌊ TelΡ5 ⌋
GΡ5 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs (vs (vs vz))))))
TelΡ6 : Ctx
TelΡ6 = TelΡ5 ▹ El GΡ5
GΡ6 : RTm ⌊ TelΡ6 ⌋
GΡ6 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs (vs (vs (vs vz)))))))
TelΡ7 : Ctx
TelΡ7 = TelΡ6 ▹ El GΡ6
GΡ7 : RTm ⌊ TelΡ7 ⌋
GΡ7 = pair (var (vs (vs (vs (vs (vs (vs vz))))))) (pair (var (vs (vs vz))) (var (vs vz)))
TelΡ8 : Ctx
TelΡ8 = TelΡ7 ▹ El (app (var (vs (vs (vs (vs (vs (vs (vs x₀)))))))) GΡ7)
GΡ8 : RTm ⌊ TelΡ8 ⌋
GΡ8 = ⌜Id⌝ ⌜Nat⌝ (fst (var (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))) (var (vs (vs (vs (vs (vs (vs (vs vz))))))))
TelΡ9 : Ctx
TelΡ9 = TelΡ8 ▹ El GΡ8
GΡ9 : RTm ⌊ TelΡ9 ⌋
GΡ9 = ⌜Id⌝ (⌜IMu⌝ KnotD IPair (pair sTm (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))))) (fst (snd (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))) (jsub (⌜IMu⌝ KnotD IPair (pair sTm (var vz))) (symN (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))) (var vz)) (Tm-ordtrK (var (vs (vs (vs (vs (vs (vs (vs vz)))))))) (var (vs (vs (vs (vs (vs (vs vz))))))) (var (vs (vs (vs (vs (vs vz)))))) (var (vs (vs (vs (vs vz))))) (var (vs (vs vz)))))
TelΡ10 : Ctx
TelΡ10 = TelΡ9 ▹ El GΡ9
GΡ10 : RTm ⌊ TelΡ10 ⌋
GΡ10 = ⌜Id⌝ (⌜IMu⌝ KnotD IPair (pair sTm (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))))) (snd (snd (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))))) (jsub (⌜IMu⌝ KnotD IPair (pair sTm (var vz))) (symN (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))) (var (vs vz))) (Tm-ordtrK (var (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))) (var (vs (vs (vs (vs (vs (vs (vs vz)))))))) (var (vs (vs (vs (vs (vs (vs vz))))))) (var (vs (vs (vs (vs vz))))) (var (vs (vs (vs vz))))))
TelΡ11 : Ctx
TelΡ11 = TelΡ10 ▹ El GΡ10

aΡ10 : TelΡ10 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))) ∷ Nat
aΡ10 = ⊢fst (⊢var (∋lkp _ (vsⁿ 10 vz)))
CΡ10 : ICon XΡ10
CΡ10 = iκ kΡ10 iι
W_Ρ10 : IConWf IRed TelΡ10 (keep (keep (keep (keep (keep (keep (keep (keep (keep (keep ρ₀)))))))))) (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs x₀)))))))))) CΡ10
W_Ρ10 =
  iwf-κ kΡ10 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aΡ10))
           (toMu (⊢snd (⊢snd (⊢var (∋lkp _ (vsⁿ 10 vz))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (∋lkp _ (vsⁿ 9 vz)))))
                  (toI aΡ10)
                  (⊢symN aΡ10 (fromI (⊢var (∋lkp _ (vsⁿ 9 vz))))
                         (fordAs (⊢var (there here))))
                  (toMu (⊢Tm-ordtrKv (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))) (fromI (⊢var (∋lkp _ (vsⁿ 9 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 8 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 7 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 6 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 4 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 3 vz))))))))
    iwf-ι

aΡ9 : TelΡ9 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))) ∷ Nat
aΡ9 = ⊢fst (⊢var (∋lkp _ (vsⁿ 9 vz)))
CΡ9 : ICon XΡ9
CΡ9 = iκ kΡ9 CΡ10
W_Ρ9 : IConWf IRed TelΡ9 (keep (keep (keep (keep (keep (keep (keep (keep (keep ρ₀))))))))) (vs (vs (vs (vs (vs (vs (vs (vs (vs x₀))))))))) CΡ9
W_Ρ9 =
  iwf-κ kΡ9 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aΡ9))
           (toMu (⊢fst (⊢snd (⊢var (∋lkp _ (vsⁿ 9 vz))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (∋lkp _ (vsⁿ 8 vz)))))
                  (toI aΡ9)
                  (⊢symN aΡ9 (fromI (⊢var (∋lkp _ (vsⁿ 8 vz))))
                         (fordAs (⊢var here)))
                  (toMu (⊢Tm-ordtrKv (var (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))) (fromI (⊢var (∋lkp _ (vsⁿ 8 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 7 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 6 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 5 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 4 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 2 vz))))))))
    W_Ρ10

CΡ8 : ICon XΡ8
CΡ8 = iκ kΡ8 CΡ9
W_Ρ8 : IConWf IRed TelΡ8 (keep (keep (keep (keep (keep (keep (keep (keep ρ₀)))))))) (vs (vs (vs (vs (vs (vs (vs (vs x₀)))))))) CΡ8
W_Ρ8 =
  iwf-κ kΡ8 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝ (toI (⊢fst (⊢var (∋lkp _ (vsⁿ 8 vz))))) (toI (fromI (⊢var (∋lkp _ (vsⁿ 7 vz))))))
    W_Ρ9

CΡ7 : ICon ⌊ Ρ7 ⌋
CΡ7 = iρ kΡ7 CΡ8
W_Ρ7 : IConWf IRed TelΡ7 (keep (keep (keep (keep (keep (keep (keep ρ₀))))))) (vs (vs (vs (vs (vs (vs (vs x₀))))))) CΡ7
W_Ρ7 =
  iwf-ρ kΡ7
    (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢var here))) (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢var (there here))))) (fromI (⊢var (∋lkp _ (vsⁿ 6 vz))))
      (⊢pair (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢wk (fromI (⊢var (∋lkp _ (vsⁿ 6 vz))))))) (fromMu (⊢var (∋lkp _ (vsⁿ 2 vz)))) (fromMu (⊢var (there here)))))
    W_Ρ8

CΡ6 : ICon ⌊ Ρ6 ⌋
CΡ6 = iκ kΡ6 CΡ7
W_Ρ6 : IConWf IRed TelΡ6 (keep (keep (keep (keep (keep (keep ρ₀)))))) (vs (vs (vs (vs (vs (vs x₀)))))) CΡ6
W_Ρ6 =
  iwf-κ kΡ6 (icw-imu (pair sTm (var (vs (vs (vs (vs (vs vz))))))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 5 vz))))))
    W_Ρ7

CΡ5 : ICon ⌊ Ρ5 ⌋
CΡ5 = iκ kΡ5 CΡ6
W_Ρ5 : IConWf IRed TelΡ5 (keep (keep (keep (keep (keep ρ₀))))) (vs (vs (vs (vs (vs x₀))))) CΡ5
W_Ρ5 =
  iwf-κ kΡ5 (icw-imu (pair sTm (var (vs (vs (vs (vs vz)))))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 4 vz))))))
    W_Ρ6

CΡ4 : ICon ⌊ Ρ4 ⌋
CΡ4 = iκ kΡ4 CΡ5
W_Ρ4 : IConWf IRed TelΡ4 (keep (keep (keep (keep ρ₀)))) (vs (vs (vs (vs x₀)))) CΡ4
W_Ρ4 =
  iwf-κ kΡ4 (icw-imu (pair sTm (var (vs (vs (vs vz))))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 3 vz))))))
    W_Ρ5

CΡ3 : ICon ⌊ Ρ3 ⌋
CΡ3 = iκ kΡ3 CΡ4
W_Ρ3 : IConWf IRed TelΡ3 (keep (keep (keep ρ₀))) (vs (vs (vs x₀))) CΡ3
W_Ρ3 =
  iwf-κ kΡ3 (icw-imu (pair sTm (var (vs (vs vz)))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 2 vz))))))
    W_Ρ4

CΡ2 : ICon ⌊ Ρ2 ⌋
CΡ2 = iκ kΡ2 CΡ3
W_Ρ2 : IConWf IRed TelΡ2 (keep (keep ρ₀)) (vs (vs x₀)) CΡ2
W_Ρ2 =
  iwf-κ kΡ2 (icw-imu (pair sTm (var (vs vz))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (there here)))))
    W_Ρ3

CΡ1 : ICon ⌊ Ρ1 ⌋
CΡ1 = iκ kΡ1 CΡ2
W_Ρ1 : IConWf IRed TelΡ1 (keep ρ₀) (vs x₀) CΡ1
W_Ρ1 =
  iwf-κ kΡ1 (icw-imu (pair sTm (var vz)) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
    W_Ρ2

CΡ0 : ICon ⌊ Ρ0 ⌋
CΡ0 = iκ kΡ0 CΡ1
W_Ρ0 : IConWf IRed TelΡ0 (ρ₀) (x₀) CΡ0
W_Ρ0 =
  iwf-κ kΡ0 (icw-clo ⌜Nat⌝ ⊢⌜Nat⌝) ⊢⌜Nat⌝
    W_Ρ1

rdξ-ordtrᵖWf : IConWf IRed (Θ₀ IRed) ρ₀ x₀ rdξ-ordtrᵖ
rdξ-ordtrᵖWf = W_Ρ0

-- ξ-ordtrq
-- ★ the telescope: the family, the index, then each field
--   read through the thinning that skips the family.
TelΣ0 : Ctx
TelΣ0 = Θ₀ IRed
GΣ0 : RTm ⌊ TelΣ0 ⌋
GΣ0 = ⌜Nat⌝
TelΣ1 : Ctx
TelΣ1 = TelΣ0 ▹ El GΣ0
GΣ1 : RTm ⌊ TelΣ1 ⌋
GΣ1 = ⌜IMu⌝ KnotD IPair (pair sTm (var vz))
TelΣ2 : Ctx
TelΣ2 = TelΣ1 ▹ El GΣ1
GΣ2 : RTm ⌊ TelΣ2 ⌋
GΣ2 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs vz)))
TelΣ3 : Ctx
TelΣ3 = TelΣ2 ▹ El GΣ2
GΣ3 : RTm ⌊ TelΣ3 ⌋
GΣ3 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs vz))))
TelΣ4 : Ctx
TelΣ4 = TelΣ3 ▹ El GΣ3
GΣ4 : RTm ⌊ TelΣ4 ⌋
GΣ4 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs (vs vz)))))
TelΣ5 : Ctx
TelΣ5 = TelΣ4 ▹ El GΣ4
GΣ5 : RTm ⌊ TelΣ5 ⌋
GΣ5 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs (vs (vs vz))))))
TelΣ6 : Ctx
TelΣ6 = TelΣ5 ▹ El GΣ5
GΣ6 : RTm ⌊ TelΣ6 ⌋
GΣ6 = ⌜IMu⌝ KnotD IPair (pair sTm (var (vs (vs (vs (vs (vs vz)))))))
TelΣ7 : Ctx
TelΣ7 = TelΣ6 ▹ El GΣ6
GΣ7 : RTm ⌊ TelΣ7 ⌋
GΣ7 = pair (var (vs (vs (vs (vs (vs (vs vz))))))) (pair (var (vs vz)) (var vz))
TelΣ8 : Ctx
TelΣ8 = TelΣ7 ▹ El (app (var (vs (vs (vs (vs (vs (vs (vs x₀)))))))) GΣ7)
GΣ8 : RTm ⌊ TelΣ8 ⌋
GΣ8 = ⌜Id⌝ ⌜Nat⌝ (fst (var (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))) (var (vs (vs (vs (vs (vs (vs (vs vz))))))))
TelΣ9 : Ctx
TelΣ9 = TelΣ8 ▹ El GΣ8
GΣ9 : RTm ⌊ TelΣ9 ⌋
GΣ9 = ⌜Id⌝ (⌜IMu⌝ KnotD IPair (pair sTm (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))))) (fst (snd (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))) (jsub (⌜IMu⌝ KnotD IPair (pair sTm (var vz))) (symN (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))) (var vz)) (Tm-ordtrK (var (vs (vs (vs (vs (vs (vs (vs vz)))))))) (var (vs (vs (vs (vs (vs (vs vz))))))) (var (vs (vs (vs (vs (vs vz)))))) (var (vs (vs (vs (vs vz))))) (var (vs (vs (vs vz))))))
TelΣ10 : Ctx
TelΣ10 = TelΣ9 ▹ El GΣ9
GΣ10 : RTm ⌊ TelΣ10 ⌋
GΣ10 = ⌜Id⌝ (⌜IMu⌝ KnotD IPair (pair sTm (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))))) (snd (snd (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))))) (jsub (⌜IMu⌝ KnotD IPair (pair sTm (var vz))) (symN (fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))))) (var (vs vz))) (Tm-ordtrK (var (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))) (var (vs (vs (vs (vs (vs (vs (vs vz)))))))) (var (vs (vs (vs (vs (vs (vs vz))))))) (var (vs (vs (vs (vs (vs vz)))))) (var (vs (vs (vs vz))))))
TelΣ11 : Ctx
TelΣ11 = TelΣ10 ▹ El GΣ10

aΣ10 : TelΣ10 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))))) ∷ Nat
aΣ10 = ⊢fst (⊢var (∋lkp _ (vsⁿ 10 vz)))
CΣ10 : ICon XΣ10
CΣ10 = iκ kΣ10 iι
W_Σ10 : IConWf IRed TelΣ10 (keep (keep (keep (keep (keep (keep (keep (keep (keep (keep ρ₀)))))))))) (vs (vs (vs (vs (vs (vs (vs (vs (vs (vs x₀)))))))))) CΣ10
W_Σ10 =
  iwf-κ kΣ10 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aΣ10))
           (toMu (⊢snd (⊢snd (⊢var (∋lkp _ (vsⁿ 10 vz))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (∋lkp _ (vsⁿ 9 vz)))))
                  (toI aΣ10)
                  (⊢symN aΣ10 (fromI (⊢var (∋lkp _ (vsⁿ 9 vz))))
                         (fordAs (⊢var (there here))))
                  (toMu (⊢Tm-ordtrKv (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))) (fromI (⊢var (∋lkp _ (vsⁿ 9 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 8 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 7 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 6 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 5 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 3 vz))))))))
    iwf-ι

aΣ9 : TelΣ9 ⊢ fst (var (vs (vs (vs (vs (vs (vs (vs (vs (vs vz)))))))))) ∷ Nat
aΣ9 = ⊢fst (⊢var (∋lkp _ (vsⁿ 9 vz)))
CΣ9 : ICon XΣ9
CΣ9 = iκ kΣ9 CΣ10
W_Σ9 : IConWf IRed TelΣ9 (keep (keep (keep (keep (keep (keep (keep (keep (keep ρ₀))))))))) (vs (vs (vs (vs (vs (vs (vs (vs (vs x₀))))))))) CΣ9
W_Σ9 =
  iwf-κ kΣ9 (icw-ford _ _ _)
    (⊢⌜Id⌝ (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm aΣ9))
           (toMu (⊢fst (⊢snd (⊢var (∋lkp _ (vsⁿ 9 vz))))))
           (⊢jsub (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
                  (toI (fromI (⊢var (∋lkp _ (vsⁿ 8 vz)))))
                  (toI aΣ9)
                  (⊢symN aΣ9 (fromI (⊢var (∋lkp _ (vsⁿ 8 vz))))
                         (fordAs (⊢var here)))
                  (toMu (⊢Tm-ordtrKv (var (vs (vs (vs (vs (vs (vs (vs (vs vz))))))))) (fromI (⊢var (∋lkp _ (vsⁿ 8 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 7 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 6 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 5 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 4 vz)))) (fromMu (⊢var (∋lkp _ (vsⁿ 3 vz))))))))
    W_Σ10

CΣ8 : ICon XΣ8
CΣ8 = iκ kΣ8 CΣ9
W_Σ8 : IConWf IRed TelΣ8 (keep (keep (keep (keep (keep (keep (keep (keep ρ₀)))))))) (vs (vs (vs (vs (vs (vs (vs (vs x₀)))))))) CΣ8
W_Σ8 =
  iwf-κ kΣ8 (icw-ford _ _ _)
    (⊢⌜Id⌝ ⊢⌜Nat⌝ (toI (⊢fst (⊢var (∋lkp _ (vsⁿ 8 vz))))) (toI (fromI (⊢var (∋lkp _ (vsⁿ 7 vz))))))
    W_Σ9

CΣ7 : ICon ⌊ Σ7 ⌋
CΣ7 = iρ kΣ7 CΣ8
W_Σ7 : IConWf IRed TelΣ7 (keep (keep (keep (keep (keep (keep (keep ρ₀))))))) (vs (vs (vs (vs (vs (vs (vs x₀))))))) CΣ7
W_Σ7 =
  iwf-ρ kΣ7
    (⊢pair (ty-Σ (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢var here))) (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢var (there here))))) (fromI (⊢var (∋lkp _ (vsⁿ 6 vz))))
      (⊢pair (ty-IMu KnotWf (⊢ixP ⊢sTm (⊢wk (fromI (⊢var (∋lkp _ (vsⁿ 6 vz))))))) (fromMu (⊢var (there here))) (fromMu (⊢var here))))
    W_Σ8

CΣ6 : ICon ⌊ Σ6 ⌋
CΣ6 = iκ kΣ6 CΣ7
W_Σ6 : IConWf IRed TelΣ6 (keep (keep (keep (keep (keep (keep ρ₀)))))) (vs (vs (vs (vs (vs (vs x₀)))))) CΣ6
W_Σ6 =
  iwf-κ kΣ6 (icw-imu (pair sTm (var (vs (vs (vs (vs (vs vz))))))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 5 vz))))))
    W_Σ7

CΣ5 : ICon ⌊ Σ5 ⌋
CΣ5 = iκ kΣ5 CΣ6
W_Σ5 : IConWf IRed TelΣ5 (keep (keep (keep (keep (keep ρ₀))))) (vs (vs (vs (vs (vs x₀))))) CΣ5
W_Σ5 =
  iwf-κ kΣ5 (icw-imu (pair sTm (var (vs (vs (vs (vs vz)))))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 4 vz))))))
    W_Σ6

CΣ4 : ICon ⌊ Σ4 ⌋
CΣ4 = iκ kΣ4 CΣ5
W_Σ4 : IConWf IRed TelΣ4 (keep (keep (keep (keep ρ₀)))) (vs (vs (vs (vs x₀)))) CΣ4
W_Σ4 =
  iwf-κ kΣ4 (icw-imu (pair sTm (var (vs (vs (vs vz))))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 3 vz))))))
    W_Σ5

CΣ3 : ICon ⌊ Σ3 ⌋
CΣ3 = iκ kΣ3 CΣ4
W_Σ3 : IConWf IRed TelΣ3 (keep (keep (keep ρ₀))) (vs (vs (vs x₀))) CΣ3
W_Σ3 =
  iwf-κ kΣ3 (icw-imu (pair sTm (var (vs (vs vz)))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (∋lkp _ (vsⁿ 2 vz))))))
    W_Σ4

CΣ2 : ICon ⌊ Σ2 ⌋
CΣ2 = iκ kΣ2 CΣ3
W_Σ2 : IConWf IRed TelΣ2 (keep (keep ρ₀)) (vs (vs x₀)) CΣ2
W_Σ2 =
  iwf-κ kΣ2 (icw-imu (pair sTm (var (vs vz))) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var (there here)))))
    W_Σ3

CΣ1 : ICon ⌊ Σ1 ⌋
CΣ1 = iκ kΣ1 CΣ2
W_Σ1 : IConWf IRed TelΣ1 (keep ρ₀) (vs x₀) CΣ1
W_Σ1 =
  iwf-κ kΣ1 (icw-imu (pair sTm (var vz)) KnotWf)
    (⊢⌜IMu⌝ KnotWf (⊢ixP ⊢sTm (fromI (⊢var here))))
    W_Σ2

CΣ0 : ICon ⌊ Σ0 ⌋
CΣ0 = iκ kΣ0 CΣ1
W_Σ0 : IConWf IRed TelΣ0 (ρ₀) (x₀) CΣ0
W_Σ0 =
  iwf-κ kΣ0 (icw-clo ⌜Nat⌝ ⊢⌜Nat⌝) ⊢⌜Nat⌝
    W_Σ1

rdξ-ordtrqWf : IConWf IRed (Θ₀ IRed) ρ₀ x₀ rdξ-ordtrq
rdξ-ordtrqWf = W_Σ0

