--- GENERATED by tools/gen-knot.py — do not edit.
------------------------------------------------------------------------
-- OCP-0009 · EXAMPLES — ★★★ `sub-agree`, TIED: ALL 30 `RTm` ROWS.
--
--     sub-agree : Represents σ s → (t : RTm Γ) →
--                 subAtK sTm ⌈Γ⌉ ⌈Δ⌉ s ⌈t⌉ ⟶* ⌈ subTm σ t ⌉
--
-- ★★★ STEP 3 OF `PLAN-RENAMING.md`, COMPLETE — both halves.
--   `Knot/SubAgreeRows` supplies the 25 same-sort rows (generated),
--   `Knot/SubAgreeX` the four cross-sort ones and the given `var` row,
--   `Knot/SubClosed` the closed-sort identities they lean on.
--
-- ⚠ AND THE SUBSTITUTION HALF IS BUILT ON THE RENAMING HALF, not parallel
--   to it: a binder row needs `Knot/SubExt.extS-Represents`, whose `vs`
--   case composes with `wkTmK-agree`, which is `ren-agree` at `vs`.
------------------------------------------------------------------------

{-# OPTIONS --safe #-}
module DirectedHoTT.Examples.Knot.SubAgreeTie where
open import Agda.Builtin.Nat using ( zero; suc ) renaming ( Nat to ℕ )
open import DirectedHoTT.Spec.Syntax
  using ( Cx; RTm; Var; Sub; subTm
        ; absurd
        ; ap
        ; app
        ; con
        ; elim
        ; fst
        ; hrefl
        ; icon
        ; idrefl
        ; ielim
        ; jsub
        ; lam
        ; natrec
        ; nsuc
        ; nzero
        ; ordtr
        ; pair
        ; snd
        ; tr
        ; unit
        ; var
        ; ⌜Hom⌝
        ; ⌜IMu⌝
        ; ⌜Id⌝
        ; ⌜Mu⌝
        ; ⌜Nat⌝
        ; ⌜Unit⌝
        ; ⌜base⌝
        ; ⌜Π⌝
        ; ⌜Σ⌝
        )
open import DirectedHoTT.Spec.Typing using ( _⟶*_ )
open import DirectedHoTT.Examples.Knot.Map using ( enTm )
open import DirectedHoTT.Examples.Knot.Sorts using ( num; len; sTm )
open import DirectedHoTT.Examples.Knot.SubApp using ( subAtK )
open import DirectedHoTT.Examples.Knot.SubAgree using ( Represents )
open import DirectedHoTT.Examples.Knot.SubAgreeRows
  using ( row-lam; row-app; row-pair; row-absurd; row-ordtr; row-fst; row-snd; row-cbase; row-cPi; row-cSg; row-cHom; row-hrefl; row-tr; row-ap; row-cId; row-idrefl; row-jsub; row-unit; row-nzero; row-nsuc; row-natrec; row-con; row-icon; row-cNat; row-cUnit )
open import DirectedHoTT.Examples.Knot.SubAgreeX
  using ( row-cMu; row-elim; row-ielim; row-cIMu; row-var )


sub-agree : {Γ Δ Θ : Cx} {σ : Sub Γ Δ} {s : RTm Θ} →
            Represents σ s → (t : RTm Γ) →
            subAtK sTm (num (len Γ)) (num (len Δ)) s (enTm {Γ} {Θ} t)
            ⟶* enTm {Δ} {Θ} (subTm σ t)
sub-agree h (var y0) = row-var h y0
sub-agree h (lam y0) = row-lam h y0 (λ h' → sub-agree h' y0)
sub-agree h (app y0 y1) = row-app h y0 y1 (λ h' → sub-agree h' y0) (λ h' → sub-agree h' y1)
sub-agree h (pair y0 y1) = row-pair h y0 y1 (λ h' → sub-agree h' y0) (λ h' → sub-agree h' y1)
sub-agree h (absurd y0 y1) = row-absurd h y0 y1 (λ h' → sub-agree h' y0) (λ h' → sub-agree h' y1)
sub-agree h (ordtr y0 y1 y2 y3 y4) = row-ordtr h y0 y1 y2 y3 y4 (λ h' → sub-agree h' y0) (λ h' → sub-agree h' y1) (λ h' → sub-agree h' y2) (λ h' → sub-agree h' y3) (λ h' → sub-agree h' y4)
sub-agree h (fst y0) = row-fst h y0 (λ h' → sub-agree h' y0)
sub-agree h (snd y0) = row-snd h y0 (λ h' → sub-agree h' y0)
sub-agree h ⌜base⌝ = row-cbase h 
sub-agree h (⌜Π⌝ y0 y1) = row-cPi h y0 y1 (λ h' → sub-agree h' y0) (λ h' → sub-agree h' y1)
sub-agree h (⌜Σ⌝ y0 y1) = row-cSg h y0 y1 (λ h' → sub-agree h' y0) (λ h' → sub-agree h' y1)
sub-agree h (⌜Hom⌝ y0 y1 y2) = row-cHom h y0 y1 y2 (λ h' → sub-agree h' y0) (λ h' → sub-agree h' y1) (λ h' → sub-agree h' y2)
sub-agree h (hrefl y0 y1) = row-hrefl h y0 y1 (λ h' → sub-agree h' y0) (λ h' → sub-agree h' y1)
sub-agree h (tr y0 y1 y2) = row-tr h y0 y1 y2 (λ h' → sub-agree h' y0) (λ h' → sub-agree h' y1) (λ h' → sub-agree h' y2)
sub-agree h (ap y0 y1 y2) = row-ap h y0 y1 y2 (λ h' → sub-agree h' y0) (λ h' → sub-agree h' y1) (λ h' → sub-agree h' y2)
sub-agree h (⌜Id⌝ y0 y1 y2) = row-cId h y0 y1 y2 (λ h' → sub-agree h' y0) (λ h' → sub-agree h' y1) (λ h' → sub-agree h' y2)
sub-agree h (idrefl y0 y1) = row-idrefl h y0 y1 (λ h' → sub-agree h' y0) (λ h' → sub-agree h' y1)
sub-agree h (jsub y0 y1 y2) = row-jsub h y0 y1 y2 (λ h' → sub-agree h' y0) (λ h' → sub-agree h' y1) (λ h' → sub-agree h' y2)
sub-agree h unit = row-unit h 
sub-agree h nzero = row-nzero h 
sub-agree h (nsuc y0) = row-nsuc h y0 (λ h' → sub-agree h' y0)
sub-agree h (natrec y0 y1 y2) = row-natrec h y0 y1 y2 (λ h' → sub-agree h' y0) (λ h' → sub-agree h' y1) (λ h' → sub-agree h' y2)
sub-agree h (con y0 y1) = row-con h y0 y1 (λ h' → sub-agree h' y1)
sub-agree h (elim y0 y1 y2) = row-elim h y0 y1 y2 (λ h' → sub-agree h' y1) (λ h' → sub-agree h' y2)
sub-agree h (icon y0 y1) = row-icon h y0 y1 (λ h' → sub-agree h' y1)
sub-agree h (ielim y0 y1 y2 y3) = row-ielim h y0 y1 y2 y3 (λ h' → sub-agree h' y1) (λ h' → sub-agree h' y2) (λ h' → sub-agree h' y3)
sub-agree h ⌜Nat⌝ = row-cNat h 
sub-agree h (⌜Mu⌝ y0) = row-cMu h y0
sub-agree h (⌜IMu⌝ y0 y1 y2) = row-cIMu h y0 y1 y2 (λ h' → sub-agree h' y2)
sub-agree h ⌜Unit⌝ = row-cUnit h 
