-- SPDX-License-Identifier: AGPL-3.0-or-later
-- Copyright (C) 2025-2026 Jonas Claesson

------------------------------------------------------------------------
-- ⚠⚠ GENERATED by tools/gen-knot.py — DO NOT EDIT BY HAND. ⚠⚠
--
-- The kernel's syntax as a SIGNATURE of `Lib/Syn` (sorts 0 RTy · 1 RTm,
-- index (sort, depth), fibred by sort — D075), rows parsed out of
-- `Spec/Syntax.agda`.  The encoding is documented in the generator's header.
------------------------------------------------------------------------

{-# OPTIONS --safe #-}
module DirectedHoTT.Examples.Knot.Terms where
open import Agda.Builtin.Nat using ( zero; suc ) renaming ( Nat to ℕ )
open import DirectedHoTT.Spec.Syntax
open import DirectedHoTT.Spec.Typing hiding ( _×_; _,,_ )
open import DirectedHoTT.Lib.FinFam using ( FinI; ffz; ffs; ⊢ffz; ⊢ffs; toI; ⊢isuc )
open import DirectedHoTT.Lib.Syn
open import DirectedHoTT.Examples.Knot.Sig

------------------------------------------------------------------------
-- The QUOTATION of the kernel's syntax into the Knot: a term of depth
-- `|Γ|` becomes a Knot term at `(sort, |Γ|)`, a variable a `Fin |Γ|`.
------------------------------------------------------------------------

-- the depth of a context, as an object numeral
dep : Cx → {Θ : Cx} → RTm Θ
dep ε       = nzero
dep (Γ ∙)   = nsuc (dep Γ)

⊢dep' : (Γ : Cx) {Θ : Ctx} → Θ ⊢ dep Γ ∷ El ⌜Nat⌝
⊢dep' ε       = toI ⊢nzero
⊢dep' (Γ ∙)   = ⊢isuc (⊢dep' Γ)

-- a meta-level natural, as an object numeral
quoteℕ : ℕ → {Θ : Cx} → RTm Θ
quoteℕ zero    = nzero
quoteℕ (suc n) = nsuc (quoteℕ n)

⊢quoteℕ : (n : ℕ) {Θ : Ctx} → Θ ⊢ quoteℕ n ∷ El ⌜Nat⌝
⊢quoteℕ zero    = toI ⊢nzero
⊢quoteℕ (suc n) = ⊢isuc (⊢quoteℕ n)

-- a variable is a `Fin` of the depth
quoteVar : {Γ : Cx} → Var Γ → {Θ : Cx} → RTm Θ
quoteVar {Γ ∙} vz     = ffz
quoteVar {Γ ∙} (vs x) = ffs (quoteVar x)

⊢quoteVar : {Γ : Cx} (x : Var Γ) {Θ : Ctx} → Θ ⊢ quoteVar x ∷ FinI (dep Γ)
⊢quoteVar {Γ ∙} vz     = ⊢ffz (⊢dep' Γ)
⊢quoteVar {Γ ∙} (vs x) = ⊢ffs (⊢dep' Γ) (⊢quoteVar x)

quoteTy : {Γ : Cx} → RTy Γ → {Θ : Cx} → RTm Θ
quoteTm : {Γ : Cx} → RTm Γ → {Θ : Cx} → RTm Θ

quoteTy base = kbase
quoteTy U = kU
quoteTy (Π a0 a1) = kPi (quoteTy a0) (quoteTy a1)
quoteTy (Σ' a0 a1) = kSg (quoteTy a0) (quoteTy a1)
quoteTy (El a0) = kEl (quoteTm a0)
quoteTy (Hom a0 a1 a2) = kHom (quoteTy a0) (quoteTm a1) (quoteTm a2)
quoteTy Unit = kUnit
quoteTy Nat = kNat
quoteTy (Id a0 a1 a2) = kId (quoteTy a0) (quoteTm a1) (quoteTm a2)
quoteTy (IMu a0 a1 a2) = kIMu (quoteTm a0) (quoteTm a1) (quoteTm a2)
quoteTy (Desc a0) = kDesc (quoteTm a0)
quoteTy (DIh a0 a1 a2 a3) = kDIh (quoteTm a0) (quoteTy a1) (quoteTm a2) (quoteTm a3)
quoteTy (Fin a0) = kFin (quoteℕ a0)

quoteTm (var a0) = kvar (quoteVar a0)
quoteTm (lam a0) = klam (quoteTm a0)
quoteTm (app a0 a1) = kapp (quoteTm a0) (quoteTm a1)
quoteTm (pair a0 a1) = kpair (quoteTm a0) (quoteTm a1)
quoteTm (absurd a0 a1) = kabsurd (quoteTm a0) (quoteTm a1)
quoteTm (ordtr a0 a1 a2 a3 a4) = kordtr (quoteTm a0) (quoteTm a1) (quoteTm a2) (quoteTm a3) (quoteTm a4)
quoteTm (fst a0) = kfst (quoteTm a0)
quoteTm (snd a0) = ksnd (quoteTm a0)
quoteTm ⌜base⌝ = kcbase
quoteTm (⌜Π⌝ a0 a1) = kcPi (quoteTm a0) (quoteTm a1)
quoteTm (⌜Σ⌝ a0 a1) = kcSg (quoteTm a0) (quoteTm a1)
quoteTm (⌜Hom⌝ a0 a1 a2) = kcHom (quoteTm a0) (quoteTm a1) (quoteTm a2)
quoteTm (hrefl a0 a1) = khrefl (quoteTm a0) (quoteTm a1)
quoteTm (tr a0 a1 a2) = ktr (quoteTm a0) (quoteTm a1) (quoteTm a2)
quoteTm (ap a0 a1 a2) = kap (quoteTm a0) (quoteTm a1) (quoteTm a2)
quoteTm (⌜Id⌝ a0 a1 a2) = kcId (quoteTm a0) (quoteTm a1) (quoteTm a2)
quoteTm (idrefl a0 a1) = kidrefl (quoteTm a0) (quoteTm a1)
quoteTm (jsub a0 a1 a2) = kjsub (quoteTm a0) (quoteTm a1) (quoteTm a2)
quoteTm unit = kunit
quoteTm nzero = knzero
quoteTm (nsuc a0) = knsuc (quoteTm a0)
quoteTm (natrec a0 a1 a2) = knatrec (quoteTm a0) (quoteTm a1) (quoteTm a2)
quoteTm (con a0) = kcon (quoteTm a0)
quoteTm (ielim a0 a1 a2 a3) = kielim (quoteTm a0) (quoteTm a1) (quoteTm a2) (quoteTm a3)
quoteTm dι = kdI
quoteTm (dσ a0 a1) = kdS (quoteTm a0) (quoteTm a1)
quoteTm (dρ a0 a1) = kdR (quoteTm a0) (quoteTm a1)
quoteTm (dpay a0 a1 a2) = kdpay (quoteTm a0) (quoteTm a1) (quoteTm a2)
quoteTm (dih a0 a1 a2 a3) = kdih (quoteTm a0) (quoteTm a1) (quoteTm a2) (quoteTm a3)
quoteTm fzero = kfzero
quoteTm (fsuc a0) = kfsuc (quoteTm a0)
quoteTm (fcase a0 a1 a2) = kfcase (quoteTm a0) (quoteTm a1) (quoteTm a2)
quoteTm (fcase0 a0) = kfcase0 (quoteTm a0)
quoteTm (psplit a0 a1) = kpsplit (quoteTm a0) (quoteTm a1)
quoteTm ⌜Nat⌝ = kcNat
quoteTm (⌜IMu⌝ a0 a1 a2) = kcIMu (quoteTm a0) (quoteTm a1) (quoteTm a2)
quoteTm (⌜Fin⌝ a0) = kcFin (quoteℕ a0)
quoteTm ⌜Unit⌝ = kcUnit

⊢quoteTy : {Γ : Cx} (A : RTy Γ) {Θ : Ctx} → Θ ⊢ quoteTy A ∷ K 0 (dep Γ)
⊢quoteTm : {Γ : Cx} (t : RTm Γ) {Θ : Ctx} → Θ ⊢ quoteTm t ∷ K 1 (dep Γ)
⊢quoteTy {Γ} base =
  ⊢conSyn {sg = KSig} {shs = TyShs} {sh = sh-kbase} KOK nthᵍ-z nthʰ-z (⊢dep' Γ) a[]
⊢quoteTy {Γ} U =
  ⊢conSyn {sg = KSig} {shs = TyShs} {sh = sh-kU} KOK nthᵍ-z (nthʰ-s nthʰ-z) (⊢dep' Γ) a[]
⊢quoteTy {Γ} (Π a0 a1) =
  ⊢conSyn {sg = KSig} {shs = TyShs} {sh = sh-kPi} KOK nthᵍ-z (nthʰ-s (nthʰ-s nthʰ-z)) (⊢dep' Γ) (a-rec (⊢quoteTy a0) (a-rec (⊢quoteTy a1) a[]))
⊢quoteTy {Γ} (Σ' a0 a1) =
  ⊢conSyn {sg = KSig} {shs = TyShs} {sh = sh-kSg} KOK nthᵍ-z (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z))) (⊢dep' Γ) (a-rec (⊢quoteTy a0) (a-rec (⊢quoteTy a1) a[]))
⊢quoteTy {Γ} (El a0) =
  ⊢conSyn {sg = KSig} {shs = TyShs} {sh = sh-kEl} KOK nthᵍ-z (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z)))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) a[])
⊢quoteTy {Γ} (Hom a0 a1 a2) =
  ⊢conSyn {sg = KSig} {shs = TyShs} {sh = sh-kHom} KOK nthᵍ-z (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z))))) (⊢dep' Γ) (a-rec (⊢quoteTy a0) (a-rec (⊢quoteTm a1) (a-rec (⊢quoteTm a2) a[])))
⊢quoteTy {Γ} Unit =
  ⊢conSyn {sg = KSig} {shs = TyShs} {sh = sh-kUnit} KOK nthᵍ-z (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z)))))) (⊢dep' Γ) a[]
⊢quoteTy {Γ} Nat =
  ⊢conSyn {sg = KSig} {shs = TyShs} {sh = sh-kNat} KOK nthᵍ-z (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z))))))) (⊢dep' Γ) a[]
⊢quoteTy {Γ} (Id a0 a1 a2) =
  ⊢conSyn {sg = KSig} {shs = TyShs} {sh = sh-kId} KOK nthᵍ-z (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z)))))))) (⊢dep' Γ) (a-rec (⊢quoteTy a0) (a-rec (⊢quoteTm a1) (a-rec (⊢quoteTm a2) a[])))
⊢quoteTy {Γ} (IMu a0 a1 a2) =
  ⊢conSyn {sg = KSig} {shs = TyShs} {sh = sh-kIMu} KOK nthᵍ-z (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z))))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) (a-rec (⊢quoteTm a1) (a-rec (⊢quoteTm a2) a[])))
⊢quoteTy {Γ} (Desc a0) =
  ⊢conSyn {sg = KSig} {shs = TyShs} {sh = sh-kDesc} KOK nthᵍ-z (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z)))))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) a[])
⊢quoteTy {Γ} (DIh a0 a1 a2 a3) =
  ⊢conSyn {sg = KSig} {shs = TyShs} {sh = sh-kDIh} KOK nthᵍ-z (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z))))))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) (a-rec (⊢quoteTy a1) (a-rec (⊢quoteTm a2) (a-rec (⊢quoteTm a3) a[]))))
⊢quoteTy {Γ} (Fin a0) =
  ⊢conSyn {sg = KSig} {shs = TyShs} {sh = sh-kFin} KOK nthᵍ-z (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z)))))))))))) (⊢dep' Γ) (a-nat (⊢quoteℕ a0) a[])

⊢quoteTm {Γ} (var a0) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kvar} KOK (nthᵍ-s nthᵍ-z) nthʰ-z (⊢dep' Γ) (a-v (⊢quoteVar a0))
⊢quoteTm {Γ} (lam a0) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-klam} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s nthʰ-z) (⊢dep' Γ) (a-rec (⊢quoteTm a0) a[])
⊢quoteTm {Γ} (app a0 a1) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kapp} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s nthʰ-z)) (⊢dep' Γ) (a-rec (⊢quoteTm a0) (a-rec (⊢quoteTm a1) a[]))
⊢quoteTm {Γ} (pair a0 a1) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kpair} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) (a-rec (⊢quoteTm a1) a[]))
⊢quoteTm {Γ} (absurd a0 a1) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kabsurd} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z)))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) (a-rec (⊢quoteTm a1) a[]))
⊢quoteTm {Γ} (ordtr a0 a1 a2 a3 a4) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kordtr} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) (a-rec (⊢quoteTm a1) (a-rec (⊢quoteTm a2) (a-rec (⊢quoteTm a3) (a-rec (⊢quoteTm a4) a[])))))
⊢quoteTm {Γ} (fst a0) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kfst} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z)))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) a[])
⊢quoteTm {Γ} (snd a0) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-ksnd} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) a[])
⊢quoteTm {Γ} ⌜base⌝ =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kcbase} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z)))))))) (⊢dep' Γ) a[]
⊢quoteTm {Γ} (⌜Π⌝ a0 a1) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kcPi} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z))))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) (a-rec (⊢quoteTm a1) a[]))
⊢quoteTm {Γ} (⌜Σ⌝ a0 a1) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kcSg} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z)))))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) (a-rec (⊢quoteTm a1) a[]))
⊢quoteTm {Γ} (⌜Hom⌝ a0 a1 a2) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kcHom} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z))))))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) (a-rec (⊢quoteTm a1) (a-rec (⊢quoteTm a2) a[])))
⊢quoteTm {Γ} (hrefl a0 a1) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-khrefl} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z)))))))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) (a-rec (⊢quoteTm a1) a[]))
⊢quoteTm {Γ} (tr a0 a1 a2) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-ktr} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z))))))))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) (a-rec (⊢quoteTm a1) (a-rec (⊢quoteTm a2) a[])))
⊢quoteTm {Γ} (ap a0 a1 a2) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kap} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z)))))))))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) (a-rec (⊢quoteTm a1) (a-rec (⊢quoteTm a2) a[])))
⊢quoteTm {Γ} (⌜Id⌝ a0 a1 a2) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kcId} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z))))))))))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) (a-rec (⊢quoteTm a1) (a-rec (⊢quoteTm a2) a[])))
⊢quoteTm {Γ} (idrefl a0 a1) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kidrefl} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z)))))))))))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) (a-rec (⊢quoteTm a1) a[]))
⊢quoteTm {Γ} (jsub a0 a1 a2) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kjsub} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z))))))))))))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) (a-rec (⊢quoteTm a1) (a-rec (⊢quoteTm a2) a[])))
⊢quoteTm {Γ} unit =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kunit} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z)))))))))))))))))) (⊢dep' Γ) a[]
⊢quoteTm {Γ} nzero =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-knzero} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z))))))))))))))))))) (⊢dep' Γ) a[]
⊢quoteTm {Γ} (nsuc a0) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-knsuc} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z)))))))))))))))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) a[])
⊢quoteTm {Γ} (natrec a0 a1 a2) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-knatrec} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z))))))))))))))))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) (a-rec (⊢quoteTm a1) (a-rec (⊢quoteTm a2) a[])))
⊢quoteTm {Γ} (con a0) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kcon} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z)))))))))))))))))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) a[])
⊢quoteTm {Γ} (ielim a0 a1 a2 a3) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kielim} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z))))))))))))))))))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) (a-rec (⊢quoteTm a1) (a-rec (⊢quoteTm a2) (a-rec (⊢quoteTm a3) a[]))))
⊢quoteTm {Γ} dι =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kdI} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z)))))))))))))))))))))))) (⊢dep' Γ) a[]
⊢quoteTm {Γ} (dσ a0 a1) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kdS} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z))))))))))))))))))))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) (a-rec (⊢quoteTm a1) a[]))
⊢quoteTm {Γ} (dρ a0 a1) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kdR} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z)))))))))))))))))))))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) (a-rec (⊢quoteTm a1) a[]))
⊢quoteTm {Γ} (dpay a0 a1 a2) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kdpay} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z))))))))))))))))))))))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) (a-rec (⊢quoteTm a1) (a-rec (⊢quoteTm a2) a[])))
⊢quoteTm {Γ} (dih a0 a1 a2 a3) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kdih} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z)))))))))))))))))))))))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) (a-rec (⊢quoteTm a1) (a-rec (⊢quoteTm a2) (a-rec (⊢quoteTm a3) a[]))))
⊢quoteTm {Γ} fzero =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kfzero} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z))))))))))))))))))))))))))))) (⊢dep' Γ) a[]
⊢quoteTm {Γ} (fsuc a0) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kfsuc} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z)))))))))))))))))))))))))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) a[])
⊢quoteTm {Γ} (fcase a0 a1 a2) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kfcase} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z))))))))))))))))))))))))))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) (a-rec (⊢quoteTm a1) (a-rec (⊢quoteTm a2) a[])))
⊢quoteTm {Γ} (fcase0 a0) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kfcase0} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z)))))))))))))))))))))))))))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) a[])
⊢quoteTm {Γ} (psplit a0 a1) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kpsplit} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z))))))))))))))))))))))))))))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) (a-rec (⊢quoteTm a1) a[]))
⊢quoteTm {Γ} ⌜Nat⌝ =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kcNat} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z)))))))))))))))))))))))))))))))))) (⊢dep' Γ) a[]
⊢quoteTm {Γ} (⌜IMu⌝ a0 a1 a2) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kcIMu} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z))))))))))))))))))))))))))))))))))) (⊢dep' Γ) (a-rec (⊢quoteTm a0) (a-rec (⊢quoteTm a1) (a-rec (⊢quoteTm a2) a[])))
⊢quoteTm {Γ} (⌜Fin⌝ a0) =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kcFin} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z)))))))))))))))))))))))))))))))))))) (⊢dep' Γ) (a-nat (⊢quoteℕ a0) a[])
⊢quoteTm {Γ} ⌜Unit⌝ =
  ⊢conSyn {sg = KSig} {shs = TmShs} {sh = sh-kcUnit} KOK (nthᵍ-s nthᵍ-z) (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s (nthʰ-s nthʰ-z))))))))))))))))))))))))))))))))))))) (⊢dep' Γ) a[]
