#!/usr/bin/env bash
# ============================================================================
# Regenerate the `Trust/` roots — together they import every module the
# sweep builds.
#
# ★★★ WHY THIS EXISTS.  `--safe` is CO-INFECTIVE (measured: a `--safe`
#   module importing a non-`--safe` one is `CoInfectiveImport`), and it
#   BANS `postulate` outright (`SafeFlagPostulate`).  So a `--safe` module
#   that imports the tree makes AGDA enforce the trust surface — no
#   scanner required.
# ⚠ `Trust.agda` claimed to be that module for weeks and imported ZERO.
#
# ⚠ `import`, NOT `open import`: we want the DEPENDENCY EDGE, not the
#   names — 240 modules opened would collide immediately.
#
# ⚠⚠ AND IT IS **SEVERAL ROOTS**, NOT ONE (2026-09-05).  `--safe`
#   propagation is EDGE-LOCAL, so N roots enforce exactly what one did,
#   provided every module is reachable from SOME root — which is the
#   COVERAGE question `check-trust.sh` diffs.  ⇒ a partition, not a
#   weakening.
#   ★ THE SINGLE ROOT STOPPED BUILDING when `Knot/RenAgree` landed:
#     OOM-killed (143) at `-A64m` on a QUIET box with 4.8 GB free, and
#     still grinding past 23 min at `-A8m -c`.  It imported all 239
#     modules and type-checked nothing, so its entire cost was loading
#     every interface at once — the one module that can never benefit
#     from `PERF.md` §6.
#   ⚠ `Knot` is split AGAIN because 116 roots was still too much; the
#     other four build in 2–7s.
#
# ⚠⚠ THERE MUST BE NO ROOT IMPORTING THE OTHERS.  That restores the old
#   closure and buys back nothing.
#
# ⚠ `Negative/` is EXCLUDED, deliberately: it holds refuted results that
#   must NOT build.
# ============================================================================
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
exec python3 - "$ROOT" <<'PY'
import io, os, sys
ROOT = sys.argv[1]
mods = []
for r, d, fs in os.walk(ROOT):
    if "/Negative" in r or "_build" in r or os.path.basename(r) == "Trust": continue
    for f in fs:
        if f.endswith(".agda"):
            p = os.path.relpath(os.path.join(r, f), ROOT)[:-5]
            mods.append("DirectedHoTT." + p.replace("/", "."))
mods.sort()
knot = [m for m in mods if m.startswith("DirectedHoTT.Examples.Knot.")]
# ⚠⚠ THE KNOT IS SLICED, AND THE COUNT IS EMPIRICAL.  One root over all
#   116 Knot modules is OOM-killed (143); so is each HALF (58), at
#   `-A64m`, at `-A64m -c`, and grinding past 10 min at `-A8m -c`.  The
#   closures do NOT shrink with the root — every Knot leaf drags the same
#   ~40-module base — so what must come down is how many LEAF CLOSURES a
#   single check unions.
NK = 8
step = (len(knot) + NK - 1) // NK
named = [
  ("Kernel",     lambda m: m.startswith(("DirectedHoTT.Spec.", "DirectedHoTT.Metatheory.", "DirectedHoTT.Algorithm."))),
  ("Lib",        lambda m: m.startswith("DirectedHoTT.Lib.")),
  ("Comparison", lambda m: m.startswith("DirectedHoTT.Comparison.")),
]
for i in range(NK):
    s = set(knot[i*step:(i+1)*step])
    named.append(("Knot%d" % (i+1), (lambda s: (lambda m: m in s))(s)))
first = [p for _, p in named]
named.append(("Examples", lambda m: not any(p(m) for p in first)))
HDR = """--- GENERATED by tools/gen-trust.sh — do not edit.
------------------------------------------------------------------------
-- DirectedHoTT · TRUST SURFACE — the **%s** root.
--
-- ★★★ WHAT A REVIEWER MUST TAKE ON FAITH TO BELIEVE THIS KERNEL:
--        Agda itself, `--safe`, and nothing else.
--   These roots are DELIBERATELY EMPTY OF CONTENT.  That is their content.
--
-- ⚠⚠ WHY SEVERAL ROOTS COST NO GUARANTEE.  `--safe` BANS `postulate` and
--   PROPAGATES through imports, and that propagation is EDGE-LOCAL, not
--   root-local — it happens on every import edge regardless of where the
--   walk starts.  So N roots enforce exactly what one root did, provided
--   every module is reachable from SOME root; `tools/check-trust.sh`
--   diffs the union of these files against the module list to check
--   precisely that.  ⇒ a partition, not a weakening.
--
-- ⚠ A module in NO root is invisible to `--safe` however sound the
--   language is.  COVERAGE, not correctness — the same class as a stale
--   generated file the sweep still globs.
--
-- ⚠⚠ THERE MUST BE NO ROOT IMPORTING THE OTHERS.
------------------------------------------------------------------------

{-# OPTIONS --safe #-}
module DirectedHoTT.Trust.%s where

"""
os.makedirs(os.path.join(ROOT, "Trust"), exist_ok=True)
seen = set()
for name, pred in named:
    sel = [m for m in mods if pred(m)]
    seen |= set(sel)
    io.open(os.path.join(ROOT, "Trust", name + ".agda"), "w", encoding="utf-8").write(
        (HDR % (name, name)) + "\n".join("import " + m for m in sel) + "\n")
assert seen == set(mods), "partition missed: %r" % (set(mods) - seen)
sys.stderr.write("Trust/ roots regenerated: %d modules\n" % len(mods))
PY
