------------------------------------------------------------------------
-- Once.Backend.Common.ApplyPostulate
--
-- Backend apply postulate pattern documentation.
--
-- This module documents the standard pattern for the apply calling
-- convention postulate that all backends (X86, AArch64, RiscV64) should
-- follow.
--
-- Unlike Once.Backend.Common.Star (which provides shared definitions),
-- this module provides DOCUMENTATION and SEMANTIC SPECIFICATION.
-- Each backend must define its own run-apply-star postulate, but they
-- should all follow the pattern and justification documented here.
--
-- WHY NOT PARAMETERIZED?
--   The postulate involves Size-polymorphic types (IRStarResult) that
--   cannot be cleanly parameterized at the module level due to Size
--   unification constraints. Documentation sharing is more practical.
--
-- SEMANTIC BOUNDARY: This postulate states that the curry/apply calling
-- convention works correctly - closures created by curry can be invoked
-- by apply to produce the expected result.
--
-- WHY NEEDED: For arbitrary programs with:
--   - External closures (FFI, dynamic loading, separate compilation)
--   - Higher-order functions from unknown sources
-- We cannot prove closures are well-formed without a semantic assumption.
--
-- WHOLE-PROGRAM ELIMINATION: For closed programs where every apply has
-- a corresponding curry, this postulate can be eliminated by using
-- ClosureWellFormed threading and run-apply-with-wf.
--
-- TWO PROOF PATHS:
--
-- PATH 1: Whole-Program Proofs (POSTULATE-FREE)
--   For closed programs where every apply has a corresponding curry:
--   1. run-curry-star-with-wf produces ClosureWellFormed proof
--   2. Thread WF proof through compose/pair/case via ir-output-wf
--   3. run-apply-with-wf consumes the WF proof
--   4. Result: Zero postulates needed for closed programs
--
-- PATH 2: Modular Proofs (USES THIS POSTULATE)
--   For open program fragments or modular reasoning:
--   1. Apply may receive closures from external sources
--   2. Cannot construct ClosureWellFormed without curry context
--   3. This axiom captures the calling convention semantics
--
-- RUNTIME EFFECT: None (proof-only - captures semantic calling convention)
--
-- STANDARD PATTERN (what each backend should define):
--
-- postulate
--   run-apply-star : ∀ {i A B} (prefix suffix : Program) (x : ⟦ (A ⇒ B) * A ⟧) (s : State) →
--     halted s ≡ false →
--     pc s ≡ length prefix →
--     readReg (regs s) a0 ≡ encode {(A ⇒ B) * A} x →
--     let prog = (prefix ++ compile-ARCH (apply {i} {A} {B})) ++ suffix
--     in ∃[ s' ] IRStarResult (apply {i} {A} {B}) prog s s' x (length prefix)
--
-- Where ARCH is replaced with the backend name (riscv, x86, aarch64).
--
-- VALIDATION STRATEGIES:
--   1. Implement curry/apply in C, compile with gcc, test empirically
--   2. Use GDB to verify calling convention matches postulate assumptions
--   3. Property testing: random closures + arguments → correct results
--   4. Cross-reference with architecture ABIs (LP64, System V, etc.)
--
-- ARCHITECTURE-SPECIFIC DETAILS:
--   Each backend should document its specific register usage and
--   calling convention details in comments near the postulate.
--
-- PRIORITIZATION (from problems-and-solutions.md):
--   - Priority 1 (Best): Eliminate postulate (use ClosureWellFormed)
--   - Priority 2 (Acceptable): Generalize pattern (THIS MODULE)
--   - Priority 3 (Worst): Architecture-specific with no guidance
------------------------------------------------------------------------

module Once.Backend.Common.ApplyPostulate where

-- This module intentionally contains no code, only documentation.
-- Each backend defines its own run-apply-star following the pattern above.
