------------------------------------------------------------------------
-- OCP-0009 · W2 (option a) item 3 — IS NATURALITY DERIVABLE FROM `Hom`'S
--                                    ELIMINATOR?  `U` checked first, as
--                                    scoped.  NO — and not for want of an
--                                    eliminator: at `U` it is REFUTABLE.
--
-- HANDOFF §4.2 item 3.  Item 2 took the pointwise reading and turned
-- naturality into a statement to PROVE OR REFUTE from the eliminator, on the
-- HoTT precedent (Lemma 2.4.3: naturality is a THEOREM, by path induction).
-- The flagged weak link: directed J is weaker, and `U` — where
-- `Hom U c d = El c ⇒ El d` is a FUNCTION, not an inductive datum — was named
-- the case expected to fail, hence the one that decides whether anything is
-- owed.  Both halves are measured here:
--
--   §2  POSITIVE CONTROL — where every hom is an IDENTITY (refl-generated,
--       i.e. `base` under choice (i)), naturality of EVERY pointwise family
--       is derived from the eliminator: `J` is the only elimination used,
--       plus the two functor identity laws.  HoTT 2.4.3 survives the
--       directed setting exactly this far.
--
--   §3  ★★ AT `U` NATURALITY IS FALSE, not merely underivable.  A two-code
--       universe, two functors out of it, and a pointwise family whose
--       square does not commute.  Reading (i) makes `Hom (Π U B) f g` the
--       plain family TYPE, so that family is a legitimate inhabitant; no
--       eliminator, present or future, derives a false statement.  The
--       question at `U` closes NEGATIVELY without waiting for W2 to fix the
--       eliminator's shape — which is what made this spike cheap.
--
-- ★ A CORRECTION TO THE FORECAST.  The prediction (commit e62520f7) was
-- "derivable where paths are INDUCTIVELY GENERATED, not at `U`".  Wrong
-- abstraction: `SpikeHomNat` §2's domain — the walking arrow — IS inductively
-- generated, and naturality still fails there: induction on its hom reaches
-- the constructor `a01`, where nothing forces the square.  The dividing line
-- is IDENTITIES-ONLY vs everything else.  A pointwise family can ignore any
-- NON-IDENTITY hom in the domain, and a functor pair that disagrees on that
-- hom sees it.  What path induction buys in HoTT is not "the hom is
-- inductive" but "the hom is generated by refl ALONE" — and directed homs
-- exist precisely to escape that.
--
-- SCOPE.  Semantic, like `SpikeHomNat`, and for the same reason: the
-- question is about what structure `Hom` HAS, not how it is spelt.
-- Self-contained, own prelude (PLAN §1.2).
--
-- `--safe`, zero postulates, zero holes, zero imports, no pragmas.
------------------------------------------------------------------------

{-# OPTIONS --safe #-}
module poc.OCP0009.SpikeHomNatU where

------------------------------------------------------------------------
-- 0. PRELUDE.
------------------------------------------------------------------------

infix 4 _≡_
data _≡_ {A : Set} (x : A) : A → Set where
  refl : x ≡ x

data ⊥ : Set where

⊥-elim : {A : Set} → ⊥ → A
⊥-elim ()

record ⊤ : Set where
  constructor tt

infix 3 ¬_
¬_ : Set → Set
¬ P = P → ⊥

------------------------------------------------------------------------
-- 1. THE CODOMAIN, shared by both halves: the one-object category on the
--    idempotent monoid `{e, s}` (SpikeHomNat's `B`).  One object means the
--    codomain family is CONSTANT — chosen deliberately, so that no
--    transport, dependency or variance is even in sight.  Whatever fails
--    below fails for a simpler reason than any open item.
------------------------------------------------------------------------

data M : Set where
  e s : M

infixr 9 _·_
_·_ : M → M → M
e · y = y
s · y = s

·-unitʳ : ∀ x → x · e ≡ x
·-unitʳ e = refl
·-unitʳ s = refl

------------------------------------------------------------------------
-- 2. ★ POSITIVE CONTROL — identities-only homs: naturality IS derived
--    from the eliminator.
--
-- `Path` is `Hom` at a DISCRETE type — `base` under choice (i).  Its
-- eliminator is directed J; pattern matching would be the same thing, but
-- `J` is written out so the derivation below can consume it LITERALLY and
-- the claim "from the eliminator" is the code, not a gloss.
------------------------------------------------------------------------

data Path {A : Set} (x : A) : A → Set where
  prefl : Path x x

J : {A : Set} {x : A} (P : (y : A) → Path x y → Set)
  → P x prefl
  → ∀ {y} (p : Path x y) → P y p
J P d prefl = d

-- ★ HoTT Lemma 2.4.3, directed, over a refl-generated hom: for ANY two
-- functor actions that preserve identities and ANY pointwise family θ, the
-- square commutes.  The proof is `J` + the functor identity laws + a unit
-- law of the codomain — nothing else, exactly as in the book.
naturality-discrete :
  {A : Set}
  (F G : ∀ {x y : A} → Path x y → M)       -- two functors' hom actions
  → (∀ {x : A} → F {x} {x} prefl ≡ e)      -- ...preserving identities
  → (∀ {x : A} → G {x} {x} prefl ≡ e)
  → (θ : A → M)                            -- ANY pointwise family
  → ∀ {x y : A} (p : Path x y)
  → (θ y · F p) ≡ (G p · θ x)
naturality-discrete F G F-id G-id θ {x} p =
  J (λ y q → (θ y · F q) ≡ (G q · θ x)) (square F-id G-id) p
  where
  square : ∀ {fx gx} → fx ≡ e → gx ≡ e → (θ _ · fx) ≡ (gx · θ _)
  square refl refl = ·-unitʳ (θ _)

------------------------------------------------------------------------
-- 3. ★★ THE DECISIVE CASE — domain `U`: naturality is REFUTABLE.
--
-- The universe, cut to two codes.  `Hom` at `U` is the decided clause
-- (`SpikeHomTy`): a path between codes is a MAP between their decodings.
-- On the codes `{⊥, ⊤}` that hom structure IS SpikeHomNat's walking arrow —
-- one non-identity hom, `⊥ ⇒ ⊤` — except that here nothing is stipulated:
-- the arrow EXISTS because the function does.  That is the point.  At
-- `base` the owner may choose discreteness; at `U` the maps are already
-- there, and no choice can remove them.
------------------------------------------------------------------------

data Code : Set where
  c⊥ c⊤ : Code

El : Code → Set
El c⊥ = ⊥
El c⊤ = ⊤

-- `Hom U c d = El c ⇒ El d` — directed univalence as a computation rule
HomU : Code → Code → Set
HomU c d = El c → El d

idU : (c : Code) → HomU c c
idU c = λ z → z

_∘U_ : ∀ {c d k} → HomU d k → HomU c d → HomU c k
h ∘U h' = λ z → h (h' z)

-- the one non-identity hom of this fragment
arrow : HomU c⊥ c⊤
arrow ()

-- ★ two functors `U → B`.  `f` is blind to the arrow; `g` sees it.  The
-- object parts are trivial (one object), so a functor is its hom action.
actf actg : ∀ {c d} → HomU c d → M
actf _ = e
actg {c⊥} {c⊥} _ = e
actg {c⊥} {c⊤} _ = s              -- `g` sends the arrow to `s`
actg {c⊤} {c⊥} h = ⊥-elim (h tt)  -- vacuous hom-set: no map `⊤ ⇒ ⊥`
actg {c⊤} {c⊤} _ = e

-- both really are functors — identities and composition, all eight code
-- triangles; the vacuous hom-set `⊤ ⇒ ⊥` discharges its cases itself
actf-id : ∀ (c : Code) → actf (idU c) ≡ e
actf-id _ = refl

actf-comp : ∀ {c d k} (h : HomU d k) (h' : HomU c d)
          → actf (h ∘U h') ≡ (actf h · actf h')
actf-comp _ _ = refl

actg-id : ∀ (c : Code) → actg (idU c) ≡ e
actg-id c⊥ = refl
actg-id c⊤ = refl

actg-comp : ∀ {c d k} (h : HomU d k) (h' : HomU c d)
          → actg (h ∘U h') ≡ (actg h · actg h')
actg-comp {c⊥} {c⊥} {c⊥} h h' = refl               -- e ≡ e · e
actg-comp {c⊥} {c⊥} {c⊤} h h' = refl               -- s ≡ s · e
actg-comp {c⊥} {c⊤} {c⊥} h h' = ⊥-elim (h tt)
actg-comp {c⊥} {c⊤} {c⊤} h h' = refl               -- s ≡ e · s
actg-comp {c⊤} {c⊥} {k}  h h' = ⊥-elim (h' tt)
actg-comp {c⊤} {c⊤} {c⊥} h h' = ⊥-elim (h tt)
actg-comp {c⊤} {c⊤} {c⊤} h h' = refl               -- e ≡ e · e

-- ★ the POINTWISE FAMILY over domain `U` — exactly what reading (i) admits
-- as an inhabitant of `Hom (Π U B) f g`: at each code, a hom of `B`.
-- Constant `e`, as in SpikeHomNat; nothing rules it out.
θU : Code → M
θU _ = e

-- ★★ THE SQUARE FOR `arrow` DOES NOT COMMUTE.
--
--        f c⊥ --θ c⊥--> g c⊥
--          |              |
--     f arrow          g arrow
--          ↓              ↓
--        f c⊤ --θ c⊤--> g c⊤
nat-lhs nat-rhs : M
nat-lhs = θU c⊤ · actf arrow      -- = e · e = e
nat-rhs = actg arrow · θU c⊥      -- = s · e = s

e≢s : ¬ (e ≡ s)
e≢s ()

-- ★★★ THE RESULT.  A legitimate inhabitant of the pointwise `Hom (Π U B)`
-- whose naturality square is FALSE.  Nothing an eliminator can do about a
-- false statement: item 3's `U` check closes negatively, and definitively.
U-naturality-refuted : ¬ (nat-lhs ≡ nat-rhs)
U-naturality-refuted = e≢s

------------------------------------------------------------------------
-- 4. WHAT THIS SETTLES, and the table it produces.
--
-- ★ THE `U` QUESTION IS CLOSED, and more strongly than scoped.  "Not
-- derivable from the eliminator" could have meant "the proof method runs
-- out" — an invitation to look for a stronger eliminator.  §3 says the
-- STATEMENT fails: under reading (i) the non-natural family INHABITS
-- `Hom (Π U B) f g`, so any eliminator whose rules are validated by the
-- categorical semantics this whole line is built on (`SpikeHom`: "the two
-- `Hom`s meet at the universe") cannot derive naturality.  W2 is free to
-- design the eliminator without a naturality obligation hanging over it.
--
--   ⚠ Strength, precisely: the model facts are MEASURED (§2, §3).  The
--   bridge "hence no future eliminator" rests on that eliminator being
--   sound for the intended semantics — the standing assumption of option
--   (a) itself, not a new one made here.
--
-- ★ THE HANDOFF'S FORECAST TABLE, corrected and filled in:
--
--   domain former     homs                    naturality of pointwise families
--   ---------------   ---------------------   --------------------------------
--   base, choice (i)  identities only         ✅ DERIVED from J           (§2)
--   base, choice (ii) a carried order         ❌ REFUTED — SpikeHomNat §2 IS
--                                                this case: the walking arrow
--                                                is an ordered 2-element base
--   U                 maps `El c ⇒ El d`      ❌ REFUTED                  (§3)
--   Π / Σ' as domain  families / pairs        ❌ expected — ARGUED, not
--                                                measured: their homs contain
--                                                non-identities whenever the
--                                                components' do, same shape
--                                                as `U`
--   El c, c a code    recurses                inherits the decoded former's row
--   El n neutral,     stuck                   n/a — neutral types, no homs to
--   Hom (higher)                                  induct on yet
--
-- ★★ ITEM 4 IS NO LONGER "CHEAP EITHER WAY".  The discrete-vs-ordered
-- choice at `base` is still the owner's call and still cheap in CODE, but
-- the table shows it now carries structure: (i) keeps `base` in the
-- functorial column — every pointwise family out of it is natural, by §2 —
-- while (ii) moves `base` into the pointwise-only column, by exactly
-- SpikeHomNat's counterexample re-read as a base type.  The choice decides
-- which column `base` lands in, and should be made knowing that.
--
-- ★ WHAT IS **NOT** LOST.  Everything item 2 secured survives untouched:
-- the congruence floor (`ap` along any hom), directed funext definitionally,
-- decidable conversion, directed univalence at `U` as a computation rule.
-- The cost of pointwise-only at `U` is precise and local: `Π U B` is the
-- PRODUCT category, not the exponential.  A consumer that needs natural
-- transformations at `U` states naturality as its own side condition — the
-- equation is statable (it lives in `Hom` at the codomain, the same smaller
-- call item 1 measured); it is just not CARRIED by the type.
--
-- ⇒ THE "HONEST OUTCOME" NAMED IN THE HANDOFF IS THE OUTCOME: a kernel that
-- documents which formers are functorial and which are only pointwise —
-- labelled, not silent.  This file is the label's evidence.  Remaining
-- before the cascade: item 4 (the owner's call above), nothing else.
------------------------------------------------------------------------
